### ISSUE TITLE
Write API - Utilities Login - Returning incorrect data when checking login credentials

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/NodeBB#10112]
- **NodeBB version:** v1.18.6
- **NodeBB git hash:** 22e74dc0bb9cf296f548ad3b67ba1d297e4a7dc1
- **NodeJS version:** v14.18.1

I seem to be experiencing an issue with the write API.

I'm using the following method:
https://docs.nodebb.org/api/write/#tag/utilities/paths/~1utilities~1login/post

URL example: `http://my-domain.com/api/v3/utilities/login?_uid=26` 

However, instead of returning the user against the credentials used (for example, my user "brophy", id 1), it returns the user with the same id as _uid defined in the url (in this case "icarus", id 26")

Expecting:
```
{"status":{"code":"ok","message":"OK"},"response":{"uid":1,"username":"Brophy","userslug":"brophy","picture":"/assets/uploads/profile/1-profileavatar-1637311938870.jpeg","status":"online","postcount":29,"reputation":18,"email:confirmed":1,"lastonline":1640868303552,"flags":null,"banned":false,"banned:expire":0,"joindate":1576075035316,"displayname":"Brophy","icon:text":"B","icon:bgColor":"#795548","joindateISO":"2019-12-11T14:37:15.316Z","lastonlineISO":"2021-12-30T12:45:03.552Z","banned_until":0,"banned_until_readable":"Not Banned"}}
```

Getting:
```
{"status":{"code":"ok","message":"OK"},"response":{"uid":26,"username":"Icarus","userslug":"icarus","picture":"/assets/uploads/profile/26-profileavatar.png","status":"online","postcount":0,"reputation":0,"email:confirmed":1,"lastonline":1640868373072,"flags":null,"banned":false,"banned:expire":0,"joindate":1579605888428,"displayname":"Icarus","icon:text":"I","icon:bgColor":"#607d8b","joindateISO":"2020-01-21T11:24:48.428Z","lastonlineISO":"2021-12-30T12:46:13.072Z","banned_until":0,"banned_until_readable":"Not Banned"}}
```

**Comment by julianlam** [comment]
Any particular reason you're passing _uid in? It isn't necessary

**Comment by saesrpg** [comment]
@julianlam apologies, we are upgrading from the old write API to the new one.

So none of the new write API needs `_uid` passing anymore?

**Comment by saesrpg** [comment]
getting this without passing the _uid

```
{"status":{"code":"bad-request","message":"A master token was received without a corresponding `_uid` in the request body"},"response":{}}
```

**Comment by pitaj** [comment]
Have you tried it without a bearer token?

**Comment by julianlam** [comment]
Come to think of it, the route itself really should work irrespective of whether a bearer token and `_uid` are passed in, or not.

... but yes, as @pitaj suggests, please don't pass a bearer token in to this route :smile:

**Comment by julianlam** [comment]
Ah, interesting.

Okay, so looking in the code, we call `setupApiRoute` which calls `helpers.tryRoute`, same as any other route in the write api controllers. This runs the same set of middlewares run on all other routes, doing things like checking for maintenance mode, redirecting someone to registration interstitial, firing off plugin hooks, and **authenticating the session**.

So if you call `POST /api/v3/utilities/login` with valid authentication, e.g. cookie, or bearer token, it will log that user in, and when the actual route goes to check username and password, it will find that you're already logged in, and just return that user :smile: 

Funny enough, the old Write API had logic to specifically look for the login route, and *not* log the user in, but I removed that when the write API was migrated into core, since it was a handler for a use case that was only called in one logical path, and wasn't worth the complexity of maintaining.

So to @saesrpg's credit, this was *not* exhibited in the old Write API.

**Comment by saesrpg** [comment]
Thanks everyone and thanks for the breakdown @julianlam , turns out removing the uid and auth bearer token for this method works.

Might be worth adding this as a comment on the documentation?

**Comment by julianlam** [comment]
> Might be worth adding this as a comment on the documentation?

I think I am going to re-introduce logic so the request is not authenticated for this particular route. Still thinking on the best way to implement.

**Comment by julianlam** [comment]
## :rotating_light: Breaking Change Alert

The commit associated with this issue changes the order of middlewares across all routes using `setup*Route` helpers. 

This sounds serious, but in practice the only thing this affects is that prior to the change, all api requests using bearer token were automatically refused if the site was in maintenance mode. Now, just as admins are able to access the site during maintenance mode, **admins can make bearer call authenticated API calls as well**.
