### ISSUE TITLE
Can't see emoji menu in zen mode

### ISSUE THREAD

**Issue by Jane-N** [NodeBB/NodeBB#10181]
- **NodeBB version:** v1.18.6, but has been there for many versions
- **NodeBB git hash:** 
- **NodeJS version:**

- **Installed NodeBB Plugins:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** 

- **Exact steps to cause this issue:**

1. Reply to a topic or create a new one.
2. Go into Zen Mode.
3. Try adding an emoji from the menu.

- **What you expected:** 
The menu with all emojis to show

- **What happened instead:**
Nothing. The menu probably opens, but is behind the Zen mode window due to Zen mode's z-index value.

**Comment by barisusakli** [comment]
This wasn't a zindex issue, it was related to the fullscreen api since the emoji dialog wasn't a child of the composer element it wasn't showing up when the composer was in fullscreen mode, the thumb upload dialog had the same issue as well. https://github.com/NodeBB/nodebb-plugin-composer-default/commit/1e331e255470f0ca63b9652299cb7c392e69a66a
