### ISSUE TITLE
Make upgrade script process in parallel?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10410]
We have a couple of million records in user:joindate sorted set. Running the below script takes hours to run. Could this be made to process the data parallel? 

https://github.com/NodeBB/NodeBB/blob/2f2ed6c3ad82b8a91b7430c34a0d91f466991224/src/upgrades/1.19.3/fix_user_uploads_zset.js#L22

There are a few scripts mainly from versions ago that do the same type of for loop processing that could benefit with parallelization but likely not affecting anyone else but as this is a recent one, I thought Id mention it and ask incase I'm missing something that could break the upgrade script?

**Comment by julianlam** [comment]
Probably.

However, this script is of minor importance. If you like you can just add a `return;` to line 16 so that it is skipped (but recorded as run), and complete the upgrade, and bring the forum back up.

At your own convenience, you can run `./nodebb upgrade fix_user_uploads_zset` and have it run while your NodeBB is running.

The only artifact you'll see in the interim is that file paths in `/me/uploads` will be incorrect.

**Comment by julianlam** [comment]
Yes, I knew a `for` loop looked odd. I don't tend to use them. It looks like [@barisusakli fixed my shoddy code](https://github.com/NodeBB/NodeBB/commit/770fcd9ea82630df2fe3ca9e41421f25fbeb83f5) because it threw some duplicate key errors :smile: 

I'll let him explain if need be.

**Comment by uplift** [comment]
Thanks for the details. If order isn't important I can switch it locally to a Promise.all without issue. Id like to get all of the scripts run prior to opening up the forum again (though I'm only working on backups currently)

**Comment by barisusakli** [comment]
Yeah we don't need the for loop here, the duplicate key issue was fixed in another commit.
