### ISSUE TITLE
Replace csurf library

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11046]
As of September of this year, [it seems work on csurf has been abandoned by the maintainer](https://github.com/expressjs/csurf/blob/master/README.md).

A new library is needed, and a couple were created in the meantime to fill the gap:

* https://github.com/Psifi-Solutions/csrf-csrf
* https://github.com/valexandersaulys/tiny-csrf

The latter is meant to be a drop-in(-ish) replacement for csurf, but [could potentially suffer from the same potential security vulnerabilities as csurf](https://github.com/valexandersaulys/tiny-csrf/issues/1).

csrf-csrf would require more effort to integrate as our implementation may need refactoring to support the increased security measures (hashing, etc.?)

**Comment by oplik0** [comment]
NodeBB appears to be currently using the Synchronizer Token Pattern (without cookies) - the reason csrf-csrf would require refactoring is that it's meant for the Double Submit Cookie pattern instead, however, the author also has the [csrf-sync](https://github.com/Psifi-Solutions/csrf-sync) package that should be closer to a drop-in replacement (not exactly since the API is different, but closeish enough).

A lot of the difficulty comes from the statelessness - the server not only has to verify that the two values the client sends are the same, but also that they originate from it (hence the cookie hashing/encryption). The stateful case is easier, and since NodeBB has been working that way for quite some time it shouldn't be problematic here.

**Comment by psibean** [comment]
Hey! I've taken a bit of a look, and I can see that this is the current setup in NodeBB:

```
const csrfMiddleware = csrf();

middleware.applyCSRF = function (req, res, next) {
    if (req.uid >= 0) {
        csrfMiddleware(req, res, next);
    } else {
        next();
    }
};
middleware.applyCSRFasync = util.promisify(middleware.applyCSRF);
```

So this is where the code change would need to happen, at [src/middleware/index.js, line 37](https://github.com/NodeBB/NodeBB/blob/master/src/middleware/index.js#L37).

I can see that NodeBB is using a default csurf configuration, which as previously mentioned here, means NodeBB is utilising the `synchroniser` pattern code path of csurf. Since there is not "cookie" option passed into csurf, it defaults to this pattern. I have just done a second inspection, and this should still be secure. The security problems with csurf primarily come from the double-submit pattern code path.

I mostly wrote both csrf-sync and csrf-csrf to provide csurf alternatives which did not contain the overhead of accommodating both patterns through config. Explicit modules with a very clear purpose.

**Comment by Sankar1100** [comment]
@psibean
we tried to update the same as per your suggestion, first time the chat is working and able to sent the message but while try to send the message with same person it's giving error. 

Console error:
POST https://URL/api/v3/chats/74 403
Network tab:
preview and response is "Forbidden"

Could you please any check and give your suggestions for replacing csrf?

**Comment by psibean** [comment]
> I have integrated csrf-sync library, it loads the home page but the login/registration fails saying invalid csrf token. It generates Please assist. Thanks in Advance.

@Sankar1100  I can't see a PR, got a link to the changed code?
