### ISSUE TITLE
Option to disable and hide the voting system please.

### ISSUE THREAD

**Issue by Qws** [NodeBB/NodeBB#11295]
### Description

I don't like the voting system. It's annoying to receive downvote, it's annoying to see upvotes. It creates toxic or competitive environment between users. The forum should be about text messages between users, not upvote/downvotes.

I want to have a simple forum, like in the old days... not something like Reddit.

I would like to have forum similar to GameFaqs. Clean and simple.

**Comment by barisusakli** [comment]
The setting is in the ACP. 
![image](https://user-images.githubusercontent.com/2583394/218572999-02fc2b27-1cc2-4ec9-a1ae-264feb95fc74.png)

**Comment by Qws** [comment]
If I do that, will it still be possible to reward users based on activity?

**Comment by barisusakli** [comment]
Not out of the box, the only way to get reputation is by upvotes

**Comment by julianlam** [comment]
Rewards system can grant reputation I think?

**Comment by Qws** [comment]
I assume something like this?

![image](https://user-images.githubusercontent.com/3944421/218586827-2630ced6-5268-4c15-af3d-67dcdd8cb2e5.png)
(Actually not sure what I have to put in the condition)

It feels like reputation system is too tied to the upvote/downvote system. Is there a way to reward users for creating topics, placing comments, chatting etc?

**Comment by oplik0** [comment]
I was doing something like this to lift new user restrictions and it seemed to work just fine
![obraz](https://user-images.githubusercontent.com/25460763/218732769-2cf1cb3c-c415-4bba-a24c-a81e9ca82822.png)

Your condition unfortunately won't work as you expecct, as last logged in time is the absolute time, not relative to now (so it's literally the time user last logged in, in milliseconds since January 1 1970 - so what this is testing is that user last logged within 10 milliseconds after 1970 started). Adding a reward condition with relative time user last logged in would require either modifying the rewards-essentials plugin or writing a new one with this functionality.

If you want to reward activity you could add an infinitely claimable reward for posting - this only triggers on post, so after the threshold it will award reputation on each post.

**Comment by julianlam** [comment]
Feel free to continue comment, but will close this for now.
