### ISSUE TITLE
Websites are often attacked by ddos. Can we create a tutorial for deploying to vercel

### ISSUE THREAD

**Issue by zlff** [NodeBB/NodeBB#11581]
### Description

Websites are often attacked by ddos. Can we create a tutorial for deploying to vercel

**Comment by oplik0** [comment]
1. What is the logical connection between these two statements? Vercel does have some DDoS protections (I hope), but it's not special in that regard - many other cloud providers do, including hopefully all OpenShift instances (which has an existing guide) and most services providing virtual private servers. You can also just put your instance behind an external DDoS protection provider like Cloudflare.
2. Arguably FaaS is more vulnerable to DoS attacks because of the usage-based pricing - there is even a specific term for the attacks that target that aspect of them (Denial of Wallet)
3. None of this matters because NodeBB would require substantial changes to work on a serverlees platform like Vercel. Currently, NodeBB is assumed to be constantly running for some parts to work correctly and has a fairly long startup. Modifying it to be primarily reactive with eventual cron tasks being easy to queue outside of the process itself is not simple.

**Comment by julianlam** [comment]
I think this is a spammer...
