### ISSUE TITLE
Improve User Registration Process – Email Verification Prior to User Creation

### ISSUE THREAD

**Issue by astontek** [NodeBB/NodeBB#11808]
### Description

Dear Team,

I'd like to bring to your attention an aspect of the user registration process that could be enhanced. Presently, when email verification is set as a mandatory step for registration, the process first creates a user in the database, followed by the user providing and confirming their email address to gain full site access.

However, this approach may lead to inefficiencies. For instance, consider a scenario where a user initiates the registration process but abandons it after the user profile is created but before providing their email address. This leaves a user profile in the database, leading to an increased nextUid and an occupied username, potentially resulting in a surplus of unused user profiles in the database. Even worse, if the user decided to not provide the email address and just to browse the website as a guest, it become impossible since the system requires a registered user to verify the email otherwise redirect any page to the registerComplete page, unless the user click the sign out button which it hard to figure out. This results in a subpar user experience, with users finding themselves unable to explore the website even as guests.

Feature Request:
I propose that we modify the registration process to require email provision and verification prior to creating the user in the database.

Suggested Registration Flow:
When email verification is required, upon clicking the registration button, an email address form should popup for the user to verify their email address. An entry, such as "emailConfirm:{code}", should be created in the database, associated with the user's email and an expiration time.

Following this, when the user clicks the link from the verification email (e.g., http://xample..come/register?code={code}), they would be directed to the registration page where the verified email address, fetched from the database, is displayed in a non-editable field. On form submission, the system should create the user profile using the verified email address.

Note: A popup for email entry, as opposed to a URL, will help to enhance security by ensuring that the email post originates from the website rather than from a bot. This approach also opens up the possibility for third-party plugins to add reCAPTCHA, further enhancing the spam prevention measures.

Your kind consideration of this proposal is greatly appreciated.

Best Regards,

**Comment by julianlam** [comment]
Hi @astontek, thanks for this detailed feature request. A couple thoughts:

1. [This a a primer on why NodeBB handles emails the way it does](https://community.nodebb.org/topic/16962/all-about-emails-and-how-they-re-used-in-nodebb), and it's likely something you've already read. I include it here for others who may want to comment on this issue.

1. **When email is required**, and a new registrant steps through the registration step, they are asked to provide their email. At that point, they still do not have an account registered with the system, so `nextUid` is not incremented, no username is reserved, etc.

1. Only when an email is provided (and a confirmation email is sent out), is the user actually created, although at this point the email is not associated with the account until confirmed (see point 1 as to why)

There are a couple flows that will cause a user to have an account with no email:

* User registers, provides an email, but does not confirm
* User registers via SSO method (if plugin does not provide and confirm email, then it is left empty)
* System email requirement is enabled and existing users have no email

Important to remember that even then, that's still a legitimate use case, that could be a real user whose email didn't get fully captured.

----

**However**, there is one defect that you highlighted that I agree with: When email is required, the user provides one, but has not confirmed it, then they are forcibly redirected to the email confirmation page. This is overzealous since forums can contain categories that should be accessible (and even postable) by guests. At that point, guest have even more privileges than that registered user!

NodeBB should only redirect to registerComplete controller if privileges deem it so.

e.g.

1. Email required + user w/ no email; accesses category where `registered-users` has `read` privilege, **no redirect**
2. Email required + user w/ no email; accesses topic where `verified-users` has `topics:read` but `registered-users` does not, **redirect to `registerComplete`.

**Comment by julianlam** [comment]
I also apologize for my late response, it could be that since July the email system was refactored to account for some of your changes. Checking now...

**Comment by julianlam** [comment]
Regarding the "Require new users to specify an email address" options, here is a rough timeline of how it worked:

1. Prior to 5 May, when enabled, an email entry is required, forum access allowed even if not confirmed
2. After 5 May, when enabled, an email entry **and confirmation** is required before forum access is granted.

A more flexible option is needed, where when email entry is required, forum access is allowed based on privilege setting. We already have groups for `registered-users`, `verified-users` and `unverified-users`, so we will be using those privileges, assuming it is feasible to do so.

**Comment by julianlam** [comment]
Let me know if this is a sufficient remediation.
