### ISSUE TITLE
already-posting error because lockPosting can  lock user forever

### ISSUE THREAD

**Issue by nesro** [NodeBB/NodeBB#11849]
This was a result of either a restart or an unexpected database error.

We had a user complaining about `[[error:already-posting]]` message. I looked into a code and the locking mechanism in 
 `src/controllers/write/topics.js` seems not to be able to recover after the lock is made and not unlocked immediately.

**Comment by barisusakli** [comment]
Any errors in the logs? When nodebb restarts it clears the `locks` object so it is likely something else.

**Comment by nesro** [comment]
Ok, thanks for the info. I tried to look to the code if something clears `locks` object but I probably missed it.

I don't see any errors related to this issue, but again, I might be looking for wrong keywords.

It probably happen in the time we deployed new nodebb instance to the production, so there was probably some bad timing. I will keep an eye if the issue will occur again.

**Comment by barisusakli** [comment]
For reference clearing happens here https://github.com/NodeBB/NodeBB/blob/master/src/start.js#L42

**Comment by julianlam** [comment]
@barisusakli looks like the locks system can be inadvertently engaged if someone tries to `await Promise.all(makePost);` (or maybe that's very deliberate heh).

So in the case of perhaps a bot trying to make multiple posts in rapid succession, it would trigger the lock because the id (in this case, the uid) is the same for each request.

I ran into something similar with the user registration lock, because the id _there_ is the requested username. If I tried to create users all at once but two happened to have the same username, then the lock would trigger.

**Comment by julianlam** [comment]
@nesro in your case it could be something like the user made two requests to post accidentally (something like double-clicking on submit button, although that shouldn't be allowed anyway), in which case the error is correct.

It would be problematic if the lock is _never_ dropped, but I don't think there is evidence of that, yes?

**Comment by julianlam** [comment]
Please re-open if you see evidence of this happening again :smile:

**Comment by julianlam** [comment]
@nesro I ran into this issue today because NodeBB crashed during a topic post. It didn't get to the point in the logic where the lock was cleared, so that was the issue. I had to fix the underlying issue (crash via plugin).

**Comment by barisusakli** [comment]
Should fix it I think 🤔 locks will be cleared on shutdown or when an uncaughtException happens.
https://github.com/NodeBB/NodeBB/commit/615b2f0fa06232dae2194bbcac72051bbf5b4674
