### ISSUE TITLE
administrator changes a user's email, the password field should not be displayed

### ISSUE THREAD

**Issue by Mordechay0000** [NodeBB/NodeBB#11855]
### Description

administrator changes a user's email, the password field should not be displayed
<img width="1112" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/086fc785-59f3-4c79-b38d-5c050af24628">

**Comment by DarshanDixit05** [comment]
Hey, i wanted to work on this issue. Can you please assign it to me?

**Comment by julianlam** [comment]
No? We get a lot of comments like these, it's weird.

If you want to fix it, PRs are welcome. We're not going to help you feign involvement in this project for some job ad or application.

**Comment by oplik0** [comment]
To explain as a contributor, since I feel @julianlam comment might sound a bit aggressive:

Some projects might be using the assignee system for all contributors to keep track of whether issues are worked on, however, NodeBB (and most other OSS I've seen) only uses it preemptively for core contributors to divide work.

The reason is that, to put it plainly, random people stating they will work on something are unreliable. Until there is a pull request there is basically no practical way for maintainers to know if they even started working on the issue, or just stated they will, then forgot and moved on to something else. And I'd say most people don't blame them - things just happen, it's not like they had any specific legal or moral obligations to help.

So usually the workflow is that issues are assigned to people in some kind of core team when someone plans to work on them because that is the relatively reliable kind of labor - they have *some* kind of obligation to work on it, be it social, financial, or even legal (in case the software is maintained by a company they work at).

You might think that issues not being distributed properly can lead to duplicated labor - and if the issue requires a lot of work it can be the case - but another part of OSS workflow is that most contributions are relatively small. For example this issue isn't about a huge change that will take many hours to make. Rarely will it happen, and even less commonly will it matter. Honestly, the sum of time wasted on trying to find out if someone who was assigned is still working on the issue, even for said contributors and not maintainers would end up larger than the time wasted on the rare duplicated PRs.

So most projects I know assign after a PR, sometimes even after it's merged (which isn't even always some logical decision, it might just be about someone with access having time/remembering to do so). Since at this point there was actually some involvement, and even if someone doesn't finish the PR, if someone else picks up the work they still were involved in the process.

But the truth is, it doesn't really matter. From my understanding GitHub counts contributors by commits, so it's not like being assigned is even a good way to show involvement. PRs - even closed ones - would be far better.

Ultimately, I'm also not sure why people add comments like this, especially on relatively simple issues. I never felt like it's necessary or even useful in most cases. Even if I just started work, a draft PR seems like a better idea (e.g. #11820 started as a halfway done draft PR). And if you have some questions about the issue or codebase you can ask them just fine without being assigned to anything.

**Comment by DarshanDixit05** [comment]
I apologize @julianlam @oplik0 , i will not repeat this mistake. I will try working on this issue.
