### ISSUE TITLE
add "reply to your own topics" permission

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#12102]
### Description

There are many usage scenarios in which we would like to create a category where users can open a private topic, a kind of **gallery**, where they can publish a **portfolio**, or a kind of **blog**, or **updates** on a certain topic, and the like, and only they (or administrators) can respond to the topic they created, but normal users cannot They will be able to respond and ask questions about what is creating a mess.
**Today** there is no solution for this in the permissions system - you can only define at the category level:
1. if can a user/group open new topics in the category
2. if can a user/group respond to topics in the category

I suggest adding a "**Reply to your own topics**" permission.
It will work in such a way that if there is the old "replay" permission, it will be possible to respond to any topic, but if there is no comment permission but there is the "reply to your own topics" permission, it will be possible to respond only to topics that you are the creator of.

I'd love to hear your thoughts on this!

**Comment by julianlam** [comment]
I think that this sort of usage of the privilege system is uncommon. I may be wrong about that. I do know that back in the day, people did use forums as a blog platform, and there is some value in that.

I think this might be better suited as a plugin to expose the new privilege values. 

We have the [support forum plugin](https://github.com/julianlam/nodebb-plugin-support-forum), but this goes one step further, and restricts viewership to that user, so that's not quite the same.

But a blog engine plugin could be built along the same principle. The support forum itself is not compatible with latest version of NodeBB, but should serve as a good starting point.

**Comment by barisusakli** [comment]
I have a feeling this would be better if implemented on a per topic basis instead of a category privilege, for example giving the topic creator the option to restrict replies from regular users while creating the topic. Or maybe adding it into the topic tools dropdown to toggle the state like marking a topic as question etc.

**Comment by julianlam** [comment]
:+1: That also makes sense. It really depends on the forum admin's vision of how they want to structure the blog/gallery/whatevert

**Comment by ShlomoCode** [comment]
> I think that this sort of usage of the privilege system is uncommon. I may be wrong about that. I do know that back in the day, people did use forums as a blog platform, and there is some value in that.

I think it's good not only for a blog but also in a normal forum, if you want a category of organized tutorials
Maybe we'll ask the folks at community.nodebb.org if this would be useful to them 😅
