### ISSUE TITLE
API to get post voters

### ISSUE THREAD

**Issue by nesro** [NodeBB/NodeBB#12423]
### Description

We used the v2 API that GET `/api/v2/posts/{pid}/vote` and it returned a list of upvoters. This stopped working when we updated NodeBB to v3.x.x.

As I'm looking at the current API, there is no way how to get the list of upvoters. I can load them directly from the database with `{_key: 'pid:{pid}:upvote'}`, but an API would be much better.

**Comment by julianlam** [comment]
Hi @nesro, @barisusakli did some digging but didn't see that particular `GET` in the write api. The naming is peculiar, since it's `vote`.

Since the v2 and v3 APIs were _designed_, I personally wouldn't have attached a `GET` method to a verb. That said, I could be wrong :laughing: 

----

Currently, the only way to retrieve post voters would be to call the websocket with message `posts.getVoters`.

If you're needing this in the v3 api, please let me know and I will try to get this made available.

**Comment by nesro** [comment]
We want to call this from one of our backends, so the v3 API would be great. I would much appreciate if you could provide it.
