### ISSUE TITLE
wrong css added around the url in remote fediverse post

### ISSUE THREAD

**Issue by wakest** [NodeBB/NodeBB#12508]
heres how one of my Mastodon posts is being picked up by NodeBB
<img width="1045" alt="image" src="https://github.com/NodeBB/NodeBB/assets/7890201/f4c60f16-e6ed-4d3f-bc4a-20c6e7e29c37"> [source link on NodeBB](https://community.nodebb.org/post/https%3A%2F%2Fsocial.wake.st%2Fusers%2Fliaizon%2Fstatuses%2F112263320320234811)

this CSS is being added to the front and back urls
`.invisible {
  visibility: hidden !important;
}`

<img width="506" alt="image" src="https://github.com/NodeBB/NodeBB/assets/7890201/9d4f0cfa-ae34-40fb-b646-669e63eed9d3">

if you replace `visibility: hidden !important;` with `display: none;` it mostly fixes this issue

<img width="981" alt="image" src="https://github.com/NodeBB/NodeBB/assets/7890201/4d6d4ff1-f4ab-4f5d-b00b-4f3b32d7cb80">

### Anything else?
the only additional thing is whatever is looking for the unnecessary end of the URL to hide is breaking it at a strange place, if you want to prettify this url I would imagine it to look like `search.f-droid.org` but insdead its `search.f-droid.org/?q=gemini&l` and breaking it in the middle of a slug seems strange, would make more sense to hide everything after a `?`

**Comment by julianlam** [comment]
The problem here is Mastodon adding the classes. That implementation uses those classes within their CSS, and it properly renders a shortened URL text. In NodeBB, those classes are attached to different CSS directives (or none at all, in the case of `.ellipsis`), which is why it looks funny.

It looks like NodeBB will need to do some strict sanitization of incoming HTML for display purposes...

**Comment by julianlam** [comment]
Fixed via #12573
