### ISSUE TITLE
Local & ActivityPub accounts by the same user

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#12514]
### Exact steps to cause this issue

Go to:
https://community.nodebb.org/

To see local account and ActivityPub for the same person: 
![local](https://github.com/NodeBB/NodeBB/assets/11160550/8452c39a-782b-48ad-bb03-2d1f8738245b)

At this early stage (pre-alpha build) it breaks showing some user info:
![local2](https://github.com/NodeBB/NodeBB/assets/11160550/ade89c2e-ab87-46b5-9f00-e730f9b5cb46)

### What you expected

Local & ActivityPub activity to be merged.

### What happened instead

Joined and Last Online info missing.

**Comment by AliCihan** [comment]
I am not sure if these two accounts should merge, since they are two separate accounts that are created on two separate platforms...  maybe, this can be done by the user just like topic merge action... 

but we have this "two accounts problem" that probably will be fixed soon: https://community.nodebb.org/post/99055

**Comment by julianlam** [comment]
They are two separate accounts.
