### ISSUE TITLE
Allow users to delete or "close" their accounts

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#1284]

**Comment by phoenixlzx** [comment]
Hello... but, is there anyway to disable this feature?

Users deleted their posts after problem get solved, but I think these posts should last.

Thanks.

**Comment by FaizanZahid** [comment]
I am also in favour that even after account deletion, the posts must last in the db and on forum as a guest user. is this the case?

**Comment by juan-g** [comment]
@FaizanZahid It appears that currently, when the admin deletes a user account, for example of a spammer, all the posts of the account are also deleted.

On the other hand, when users delete their own accounts without removing their posts first, then the posts are not deleted and keep the `uid` (user id number), appearing the removed user as _"Guest"_ on the post.

I think it would be better as e.g. _"Guest 123"_, that is with the `uid` number, unique for each deleted user account.

**Comment by FaizanZahid** [comment]
totally agree with the unique 123 user id thing.

**Comment by julianlam** [comment]
That's harder to do, as a "guest" account is just `uid 0`. We don't have the ability to maintain post history for guests, because... well, they're not users anymore!

We could possibly _fake_ it, in a way, by saving the old uid, but in general, users are deleted for a specific reason, no?

Also I should point out that admins have the choice of retaining posts or removing all posts when deleting a user via admin panel.

**Comment by juan-g** [comment]
>  admins have the choice of retaining posts or removing all posts when deleting a user via admin panel.

@julianlam You are right, I've just tested it again and there are:
- Delete User(s)
- Delete User(s) and Content

The second is of course useful for spam accounts. The first option is useful when -for any reason such as privacy- a legitimate user wants her/his account removed by us instead of doing it her/himself, but agreeing to keep the useful posts.

> We don't have the ability to maintain post history for guests, because... well, they're not users anymore!

I meant, even after the user account is deleted, when of course the user's database record is not there anymore, the post's database record still includes the user id.

For example, in my test, the post's record after deleting the user is the following:
```
{
    "_id" : ObjectId("5ab66b1b7865486708b0b196"),
    "_key" : "post:2578",
    "content" : "Testing...",
    "deleted" : 0,
    (...)
    "pid" : 2578,
    "tid" : 173,
    "timestamp" : 1521904411907.0,
    "uid" : 2839
}
```
I've created a user called "Test User" (`uid` 2839), then published this post (`pid` 2578) with the short text "Testing...", and deleted the user but not the post with the useful option you mentioned. It appears now as a Guest's post.

The user's record is gone, but the post's record still contains the user's `uid` number. So the post could appear attributed to "Guest 2839" instead of only "Guest" for all past accounts.
