### ISSUE TITLE
How to support Chinese search？

### ISSUE THREAD

**Issue by wzyxdwll** [NodeBB/NodeBB#12908]
### Description

* NodeBB version: 3.10.3

I have tried all the Chinese search support plugins on the plugin market, such as:
@veronikya/nodebb-plugin-meilisearch
nodebb-plugin-solr
These basically have various problems on version 3.x. Does the official have any recommended plugins? Or is there any guidance document to guide users on how to integrate third-party search engines?

**Comment by barisusakli** [comment]
What's the problem with @veronikya/nodebb-plugin-meilisearch? Someone mentioned it works on 3.7.4 so it should work on 3.10.3 if it's setup properly, https://community.nodebb.org/post/99445

**Comment by wzyxdwll** [comment]
> What's the problem with @veronikya/nodebb-plugin-meilisearch? Someone mentioned it works on 3.7.4 so it should work on 3.10.3 if it's setup properly, https://community.nodebb.org/post/99445

I had report an issue to the author:
https://github.com/oplik0/nodebb-plugin-meilisearch/issues/45#issue-2649146158

It looks like some interface has changed

**Comment by oplik0** [comment]
Yeah, I'll try to update it this week, ideally tomorrow but it might take until the weekend

**Comment by oplik0** [comment]
Should be fixed in [nodebb-plugin-meilisearch](https://www.npmjs.com/package/nodebb-plugin-meilisearch)@[0.7.2](https://www.npmjs.com/package/nodebb-plugin-meilisearch/v/0.7.2).

Fortunately it was just a dependency update - unfortunately my tests started hitting a race condition they haven't hit before (did NodeBB tests get faster? :) but it's now fixed. I also resolved oplik0/nodebb-plugin-meilisearch#42 so now it respects the match words setting.

**Comment by barisusakli** [comment]
Thank you @oplik0
