### ISSUE TITLE
Subcategories could be great

### ISSUE THREAD

**Issue by ghost** [NodeBB/NodeBB#1299]
Hi,

As some categories need to be organized, it could be great if you add subcategories in NodeBB.

**MORE** : Subcategories in subcategories too.

**Comment by bratags** [comment]
Any thoughts on adding subcategories to the purge list when purging a parent category?!  I just ran into this issue where I couldn't figure out why the category purge feature "wasn't working", when I realized it's because of the way I've structured my forum (i.e. nested subcategories).

Anyway, has any thought been given to this?

**Comment by julianlam** [comment]
Categories are all mutually exclusive to one another, and that keeps things simple and reduces side effects.

They can be nested and this is purely for UI organization purposes.

But that said, purging a category should give better errors when subcategories exist.

Secondly, a checkbox option could allow you to instruct the backend to purge all subcategories on request.
