### ISSUE TITLE
Shift-click on checkboxes should allow multiple topic selection

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1441]
Compare the behaviour exhibited in the following two videos:

[NodeBB](http://webmup.com/up/oZ7hB.webm) vs [GMail](http://webmup.com/up/N7B2e.webm)

**Comment by yamikuronue** [comment]
Wait WHAT?! Checkboxes don't WORK that way. Why is this worth breaking link selection over? This is not an accepted standard; Gmail is the only app I've ever seen work this way, and I only found out it did because of this issue. Just because google does something doesn't make it the right option for your context....

**Comment by julianlam** [comment]
Replied via #5335. Let's keep discussion there 😄
