### ISSUE TITLE
Search within a topic

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#1800]
Searching terms will help you quickly find specifically what you're looking for within a topic.

**Comment by FaizanZahid** [comment]
Hi @julianlam ,

I was trying to search for the word "persona" on this topic, but since this topic has many posts, and i am sure he must have mentioned how to put profile rewards to use on user profiles on persona.

but i am unable to search within the entire posts of this topic. I tried global search but that doesn't do the trick.. do you know how can i search for ALL posts containing a phrase e.g  "persona" within a single topic?
https://community.nodebb.org/topic/4397/nodebb-plugin-ns-awards-ns-awards-give-medals/119

since everything is paginated so i can't do a ctrl+f even if i turn on infinite scroll i still have to manuall scroll ALL the way to the end to do the ctrl+f thing but this topic has 500+ posts, so how to do it?

**Comment by pitaj** [comment]
Did you turn on the override search option in the user settings?

**Comment by FaizanZahid** [comment]
Thanks pita, yes i enabled that in my settings, but how do i exactly search inside a particular topic and for all posts inside that topic.

On the topic page itself i see no search.

**Comment by pitaj** [comment]
It would override the behavior of Ctrl+F
