### ISSUE TITLE
chat inbox limit

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2475]
We have a setting in the ACP for chat message inbox size but we don't delete old messages.

**Comment by pitaj** [comment]
How much database space do messages take? Is there a way to reduce this space so more messages can be kept? 

Ideally, keep all of the messages.

**Comment by TedRinehart** [comment]
@pitaj, the number of messages to keep should always be in the hands of the administrator. A blanket solution of keeping all of the messages is far from ideal. Setting a ridiculously high number of messages to keep is the best solution to keep messages stored at this time, as this number is for each set of messages between users, not a total count of all messages sent/received by  user.

**Comment by pitaj** [comment]
How about this, give the admin the ability to either save all of them or to
set a limit.

>

**Comment by julianlam** [comment]
The thing that bothers me about keeping all this data is that the great
majority of it is never ever queried again.

I'd be happier if we had a plugin that acted as a long term storage
solution for chats, instead of storing it in the primary db. (gzipped flat
file perhaps?) The downside is that this system would probably be fragile.

**Comment by pitaj** [comment]
Well, in that case, just move chats in general to a plugin

**Comment by julianlam** [comment]
I see what you did there ;)

**Comment by TedRinehart** [comment]
I believe someone made the case of moving chat to a plugin previously, rather than incorporating it as a core feature. Granted, it should be a plugin installed by default if such action were ever implemented.

@julianlam, I think you're onto something with storing this information outside of the DB. That would be extremely fragile, and administration of it could be difficult to implement. However at this stage in NodeBB's life, it seems to me that simply finding a way to get rid of all chats (as configured by the administrator) is a lacking feature.
