### ISSUE TITLE
NodeBB is hardlinked with Bootstrap

### ISSUE THREAD

**Issue by Ribesg** [NodeBB/NodeBB#2567]
## Context
I'm attempting to get rid of Bootstrap, building a theme using Semantic UI.

## Problem
I encounter multiple issues due to the fact that NodeBB is hardlinked with Bootstrap. Sometimes, I'm not sure I can do anything else than patching NodeBB itself to get something to work

## Example
Let's take an example. I'm working on the topbar. I'm trying to reproduce the Notification system using Semantic UI. But at some point I see this:
````js
/* [...] */ + '<span class="pull-right relTime">' + /* [...] */
````
and this:
````js
if (count > 0) {
	notifIcon.removeClass('fa-bell-o').addClass('fa-bell');
} else {
	notifIcon.removeClass('fa-bell').addClass('fa-bell-o');
}
````
([Source](https://github.com/NodeBB/NodeBB/blob/v0.6.x/public/src/modules/notifications.js))

## Solution?
What could I do? I'm not sure I can override those behaviours in my *theme*... I'm pretty sure there should be some kind of hook here or something, rather than harcoded Bootstrap / Font Awesome references.

Note that this is certainly not the only place this occurs, just one of the few I encountered today.

**Comment by baerrus** [comment]
+1 nodebb core should not reference any specific UI elements. That should be left exclusively to themes. I guess the problem here is all the client side code is written without any indirection. It refers to bootstrap to modify behaviors. Instead, client side should receive a dictionary which went through the template expansion. In other words, client side code should be data driven. That data can be compiled on the server side and passed to the client. That does add quite a bit of complexity and, if sloppily implemented, a performance penalty too.
That begs the question. Can client side code be attached to a theme and not to nodebb core?

**Comment by julianlam** [comment]
> +1 nodebb core should not reference any specific UI elements.

Yes, this is a stretch goal for the NodeBB team. Originally, we did not envision using a competitor to Bootstrap in our design, so many front-end aspects rely on bootstrap classnames.

This is a work in progress -- the first step was completed awhile back, when we divorced client-side scripts from the templates themselves (scripts are now found on a per-route basis in `public/src/forum`)

We have to work these issues out one at a time, because opening a large meta-issue like this means it will just be ignored (a sad reality).

Here's a quick guide:
* If you see a place where we toggle a FontAwesome asset class name on and off, it should be removed and toggling `.active` should be the suggested course of action. `.active` is then defined in the theme with `font-family: FontAwesome` and the corresponding charCode.
* If you see a place where we reference an element by its FontAwesome/Bootstrap class name, submit a PR to reference that element using a different identifier if possible
* If it is too complex to sort out, submit an issue, but limit it to a single instance (or a group of related instances) at a time, of the issue will risk being forgotten.

**Comment by cnvo** [comment]
I can assure you that this will be *one* of the most complicated things to sort out, but it can be done and should be done carefully. 

@julianlam that's only a grain of sand compared what you'd really have to do. After futher review on I came to the conclusion that you'd have to modify the core with default class names; You guys have done a remarkable job in doing this, but it's still much work to be done since we're still using things like ``.col-md-`` (BS), ``button-`` (BS), ``fa-`` (FontAwesome), not only in the core, but in plugins as well.

You mention performance @baerrus, well we're already taking a performance hit by using the many unused classes in Bootstrap itself.

If we are to move forward with this, we should create a comprehensive list of things we'd have to modify, remove, add.

**Comment by jlukic** [comment]
+1 :wink:
