### ISSUE TITLE
0.5.x -> 0.6.x upgrade issue (schema upgrade)

### ISSUE THREAD

**Issue by EvSpirit** [NodeBB/NodeBB#2673]
Hello,

I used 0.5.x community (0.5.5 to be clear) and I tried to upgrade to 0.6.x, but I got the following error: 
```
30/1 15:15 [9515] - info: [2014/12/20] Updating digest settings
30/1 15:15 [9515] - error: undefined
```

I tried both 0.5.5 -> 0.6.x and 0.5.5 -> 0.5.7 -> 0.6.x ways - the results are the same. Are there any ideas? Is it possible to enable upgrade trace-level logging somehow?

Thanks in advance!

**Comment by cnvo** [comment]
I ran into the same issue when I had to use my backup database (redis), and the schema was around 0.4.x (something around there). It wasn't like I could just jump from 0.4.x to 0.6.x because I tried and it gave me an error. So I thought about it for a while (perhaps ~30 min or so) and then I came up with a solution...

What I did was download 0.4.x - 0.6.x and took the ``NODEBB/src/upgrade.js`` from each of those versions and replaced them -- version by version and ran ``./nodebb upgrade`` each time until I made it to 0.6.x. After that, it took care of this same problem.

In your particular case, I think you're missing an upgrade somewhere in 0.5.x you may have skipped or something. Let me know if that helps.

**Comment by cnvo** [comment]
@julianlam @barisusakli Perhaps we can make upgrades from lower versions to the latest more friendlier in the future because it definitely was a pain to upgrade if you aren't consistently following along on GH. 

Also it would be nice to have change logs. Change logs in the docs, and on the community forum.

**Comment by EvSpirit** [comment]
@cnvo , thanks for your reply! Hm, but I upgraded to 0.5.7 successfully (0.5.5 -> 0.5.7 -> 0.6.x), so what should I do? At the moment my 0.5.5 instance is stable and there are no errors at all.

**Comment by cnvo** [comment]
If you want the latest, I would recommend using ``git pull`` if you haven't already to get the new files, then progressively upgrading using my method https://github.com/NodeBB/NodeBB/issues/2673#issuecomment-72197783. 

Let me know how that works for you.

**Comment by EvSpirit** [comment]
@cnvo, thank you once again! But anyway, that was not the reason. I checked upgrade.js and surrounded a couple of lines with try-catch here:

```
                                        async.eachLimit(userSettings, 50, function(setting, next) {
                                                if (setting.dailyDigestFreq !== 'off') {
                                                        db.sortedSetAdd('digest:' + setting.dailyDigestFreq + ':uids', now, setting.uid, next);
                                                } else {
                                                        next(false);
                                                }
                                        }, function(err) {
                                                if (err) {
                                                        winston.error('[2014/12/20] Error encountered while updating digest settings');
                                                        return next(err);
                                                }
                                                winston.info('[2014/12/20] Updating digest settings done');
                                                Upgrade.update(thisSchemaDate, next);
                                        });
```

The problem in in the lines:
```
else {
           next(false);
}
```

When surrounded with try/catch, it gives something like:
```
RangeError: Maximum call stack size exceeded nodejs
```

I have ~8k users and thats the reason. The easiest workaround is to increase NodeJS stack limit with the following parameter:
```
--stack-size=32000
```

But anyway - it is not a good solution.

**Comment by julianlam** [comment]
1. Upgrade scripts should always work between singular minor versions. If
not, it is a bug, and you are correct to report it.

2. Does it work if you reduce the 50 to 20?

**Comment by EvSpirit** [comment]
@julianlam Unfortunately, no, if param is 20, the problem is still the same. I checked in twice - everything works like a charm doing it like 0.5.5 -> 0.5.7 -> 0.6.0, if I try to upgrade 0.5.5 -> 0.6.0 directly, I have to manually install mime-db module, but its not a problem. I haven't noticed any other problems yet.
