### ISSUE TITLE
Modernizr

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2857]
About time we included this lib imo. So far we've just been testing against user-agent and Bootstrap environment, amongst other things, because we haven't done anything too crazy for the most part.

A basic build that should cover most of NodeBB's core stuff is about 10kb minified, but I'm contemplating getting the full version for 14kb all-in, this way theme and plugin dev's don't have to worry - the whole suite is available. 

http://modernizr.com/download/

**Comment by julianlam** [comment]
In what circumstances do we need this? We do environment detection with bootstrap only because detecting by screen size is the best available option.

[This SO question eschews Modernizr and suggests detected by page width anyway](http://stackoverflow.com/questions/7928200/using-modernizr-to-test-for-tablet-and-mobile-opinions-wanted)

Also, I'm against integrating Modernizr (10-14kb) purely because you're against integrating async :trollface:

**Comment by psychobunny** [comment]
Modernizr (you can choose exactly what functions you need) for things we are patching in utils already anyways

Yeah, I do agree that we shouldn't be adding 20kb libraries that we'd only use one or two functions from. If you didn't get my secret troll, then there's no fixing this
