### ISSUE TITLE
Prepare `disney` for merging

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2860]
The majority of the issues have been fixed, and runs well on latest `master` code. :clap: 

Here are some bugs I ran into, which may or may not be applicable:

* [x] [This pull request](https://github.com/psychobunny/templates.js/pull/30)
* [ ] Typing `Home` and `End` moves the paginator up and down as expected, but the label does not change (e.g. from the top of the page, hit `End`, and the label is now at the bottom, but still says "1 of 61"
* [ ] `Home`/`End`/`PgUp`/`PgDn` behaviour is on and off... doesn't work on cold load, but starts working after the scrollbar is clicked (and another "page" in the topic is loaded)

... and this one's just a nitpick:

* [ ] Given the nature of the scrollbar, I expect `Home` to bring me to the top couple posts, and `End` to bring me to the last couple. Instead right now, it is:
    * `Home` goes to top of page, and loads more posts if applicable. So if you were viewing 51-61 before, now you're viewing post indices `1, 40-50`
    * `End` takes you to the bottom, and the infinite loader triggers
    * Perhaps it would be easier to hijack the `Home` and `End` keys to load first and last page, respectively.

**Comment by psychobunny** [comment]
Thanks for this, going through it and this is what I got so far

1. Reverse infinite scrolling is broken :-1: 

Home / End might be broken because of above (pretty sure that used to work).

2. Infinite scrolling on category both ways is broken 

btw, didn't get either of the errors you got for tjs on FF but I'll merge it anyways (and reassign all bugs to you :hear_no_evil:)

**Comment by julianlam** [comment]
hahah yeah, it's a chrome only bug since chrome is stricter with object cloning I guess, as functions can't really be stringified.
