### ISSUE TITLE
post order bug

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#2894]
When I write a response-post and so answers while I'm writing sometimes (maybe it's appearance has to do with additional forum-tabs opened in background) new posts don't get added immediately.
After submitting my post ends up being at the very bottom and additional posts that got missed before get added now too but one post ahead of their shoud-be position.

see http://prntscr.com/6l63ef for an example.
The post: https://community.nodebb.org/topic/4044/coinawesome-using-nodebb-for-a-decentralized-content-aggregator-looking-for-a-dev-partner/6

also I've noticed if afterwards (without page-transition, reload, whatever) new posts get pulled they get added above the post I've added. I guess that's a manifestation of the same bug.

**Comment by julianlam** [comment]
Yes, this is a legitimate bug that @barisusakli and I have identified.

It has something to do with the automatic unsubscription to real-time events if you are idle for more than 60 seconds. We save cycles by not sending new post notifications to those idle participants until they are active again by navigating to another page.

@barisusakli, like I mentioned yesterday, perhaps on any socket call (open notifications, trigger infinite loader, etc), the user is marked active again?

The *second* part of the problem is related to improper detection of new posts. :+1:
