### ISSUE TITLE
Problem In Hosting

### ISSUE THREAD

**Issue by abhiklodh** [NodeBB/NodeBB#2948]
Hey There Gud ppl Of NodeBB,
I tried hosting NodeBB on Amazon Elasticache and EC2 instance and ended up failing and paying 162.17$ and tried hosting on Cloud 9 but in vain.

I can't understand what the problem no error is show.
I just am not able to view it on the browser. It may sound funny but it's really irritating.

Here's the link : http://ac-abhiklodh.c9.io:4567

PS:Amazon did refund me all my money cos I was found innocent :-p

As I mentioned, no error is visible:
![ac cloud9](https://cloud.githubusercontent.com/assets/8018018/7017479/906e7ddc-dd15-11e4-9dfa-90b5362eea66.png)

But in the browser:
![desctop screenshot](https://cloud.githubusercontent.com/assets/8018018/7017496/d69728c2-dd15-11e4-957d-914607e717a5.png)

However the npm package ws
![terminal cloud9](https://cloud.githubusercontent.com/assets/8018018/7017548/ad742692-dd16-11e4-94e0-fe06f596c426.png)

And maybe not an issue bet here's the pics of 'npm install' if u like
![terminal cloud9](https://cloud.githubusercontent.com/assets/8018018/7017599/5f98a712-dd17-11e4-8652-db53f2933db1.png)

**Comment by nhlpl** [comment]
As I can see they have a GUI to Clone Projects from URL.
https://docs.c9.io/v1.0/docs/setting-up-github-workspace

Using NodeBB v0.7.0-dev may give some other result.

**Comment by lots0logs** [comment]
I'm using the master branch on a 2GB Linode instance. Works perfectly and I never use all my resources on the VPS. My forum has about 2.5k users. I've been using Linode for almost 2years now and have never had problems. I wouldnt recommend them otherwise. If you do decide to give them a try, I'd appreciate the referral credit (our project is FOSS so we get by on donations and referrals) Anyway, I hope it helps. Cheers!

https://www.linode.com/?r=1caf0505d5b6116dd729541772bc0d0e9cd34f6c
