### ISSUE TITLE
Topic slug in error message

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2952]
Steps to reproduce:

1. Open https://community.nodebb.org/topic/4200/testing-umlauts-äöüß
2. Remove testing-umlauts- and hit Enter
3. https://community.nodebb.org/topic/4200/äöüß
4. /topic/4200/%C3%A4%C3%B6%C3%BC%C3%9F Not Found

**Comment by julianlam** [comment]
Yes, this is intentional, as the slug is incorrect.

To access a topic, you either need to pass in *no slug at all*, or the correct slug. This was to counter a problem with users posting images with no link, which would cause an XHR to retrieve the page's HTML *again*. The more images present, the more calls were made.
