### ISSUE TITLE
Font Customization

### ISSUE THREAD

**Issue by abhiklodh** [NodeBB/NodeBB#2956]
Hey guys,
I had a thought 'Why not have a column in the ACP to customize fonts or add our own by uploading them' and I also wanted to know to to change the default font with say timesnewyorker.ttf
Thanks ahead

**Comment by psychobunny** [comment]
hey, its possible to do something like this if you use [Google Fonts](https://www.google.com/fonts/) (or similar):

```
@import url(//fonts.googleapis.com/css?family=Roboto:400,300,500,700);

body {
    font-family: Roboto,Helvetica,Arial,sans-serif;
}
```

Paste this in your custom html/css section in the ACP. Otherwise you can upload it manually and edit your theme. To do this via ACP we have a similar issue open: https://github.com/NodeBB/NodeBB/issues/1509

After uploading your font you can use the above CSS code to point to that file
