### ISSUE TITLE
link in composer help leaves forum [0.7.0 dev]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#2959]
If you open the help in the composer, and you click on the links, you'll be surprised that you've left the page you were writing on. 

The default setting to open links, is to open them in the current view and not to open them in a new tab. This setting is not available in the ACP as global setting so there's no workaround, to prevent the user from that bug. 

The help should open links always in a new tab or window.

**Comment by julianlam** [comment]
Seems to be the same as #2958

**Comment by NoodleBB** [comment]
No, but it's a sideeffect.

**Comment by NoodleBB** [comment]
Step to reproduce:
1. Create a new user.
2. Create something that opens the composer.
3. Open the Help view (?), and...
4. click on the "click here" or the "emoji cheat sheet".

The result ist an unexpected behaviour, because you don't get a cheat sheet or documentation. You're left the forum.

**Comment by frissdiegurke** [comment]
First of all it's not a **bug**.

Secondly "The default setting to open links, is to open them in the current view" - exactly! So this is default and thereby the correct behavior.

Thirdly since you refer to especially the help within composer this is an *issue* of the plugins that add their help-messages (In this case [nodebb-plugin-markdown](https://github.com/julianlam/nodebb-plugin-markdown) and [nodebb-plugin-emoji-extended](https://github.com/frissdiegurke/nodebb-plugin-emoji-extended)) not of the NodeBB core itself.
Unless you intend NodeBB to add a global setting for opening external links within new tab (in this case it's duplicate request of #2958).

Trust me, the best you can do is adding appropriate indication of external links, actual behavior-changes are contra-productive. Regardless lets see what happens from official side with #2958 :wink:

**Comment by NoodleBB** [comment]
Ohhh gurke. I know how to handle that. But i'm testing nodeBB with a small audience of 40-50 user, and no one of this has IT or Dev background. They are just simple users. 

For them that is that an totally unexpected behaviour, because that forum acts like an "app". Except in that situation. For them it looks like "the app quits itself when using the help". That's unexpected. - So that's an UX issue. 

P.S.: Your suggestions to add decorative elements, doesn't help *them*.
