### ISSUE TITLE
Confirm your email & Back to NodeBB

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2996]
Steps to reproduce:

1. Go to ~~Testing Ground~~ as a guest
2. Register a new user
3. You'll be still there (~~Testing Ground~~)
4. Now activate your account in the same tab/window https://community.nodebb.org/confirm/
5. You can only go to NodeBB forumindex instead of ~~Testing Ground~~

I know many users hate when forum software throws them away from category/topic/post found in Google.

It works fine when a user click on a link from an email (a new tab) and not using copy/paste.

Edit: see below

**Comment by julianlam** [comment]
Testing Ground? Guests shouldn't be able to go to that category...

**Comment by nhlpl** [comment]
Oh yes, you're right. Not intentional. Any visible content that can be reached from Google.

**Comment by julianlam** [comment]
I don't understand the problem, then. Registered users can go anywhere
guests can, but even of they couldn't (this is determined on a category by
category basis), this is  configuration issue, no?

**Comment by nhlpl** [comment]
Google > Node.js Forum
I found it! NodeBB
Google > NodeBB install +forum

NodeBB Community > HOWTO topic
I need to register
I'm a user now & see my HOWTO

They want me to confirm my email
Confirmed
Where is HOWTO?

**Comment by julianlam** [comment]
In this case, the email confirmation is separate from the login/register logic. 

I could update the code so that when an email confirmation request is sent, we record the page to go back to, but because the link can be clicked at any time, and there is no requirement to confirm email before browsing the site, then it would be even more jarring if a user clicked the email confirmation and was then redirected to *a topic they'd browsed 4 days ago*, for example.
