### ISSUE TITLE
Regenerate all SSL certificates with stronger encryption 

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3054]
As first reported by Baris, our sites now throw SSL warnings due to a cryptographically insecure algorithm 

https://shaaaaaaaaaaaaa.com/check/community.nodebb.org

**Comment by ApfelUser** [comment]
@julianlam I am not @barisusakli but I am proud to be equal to him :stuck_out_tongue_closed_eyes: There his some explanation on how to upgrade at [SHA-Check](https://shaaaaaaaaaaaaa.com/check/community.nodebb.org) in section "Getting a SHA-2 certificate" Also it seems more like an outdated signature instead of an algorithm. An algorithm would actually be easier to fix because you could just disable the insecure one in the NGINX configuration.

**Comment by ApfelUser** [comment]
@julianlam It seems like you got your certificate from Namecheap. Here are some articles from them on how to upgrade:

  * [Migration SHA1 -> SHA2](https://www.namecheap.com/support/knowledgebase/article.aspx/9415/38/ssl-certificate-migration-from-the-sha1-to-sha2-algorithm)
  * [Reissue SSL](https://www.namecheap.com/support/knowledgebase/article.aspx/811/70/how-to-reissue-ssl-certificate)

**Comment by julianlam** [comment]
Ah, he noticed it first :trollface:

**Comment by ApfelUser** [comment]
@julianlam Okay, then I am sorry :smile:

**Comment by julianlam** [comment]
![selection_058](https://cloud.githubusercontent.com/assets/923011/7217693/1deccc50-e60c-11e4-9844-971f75e5ee68.png)

:rage2: Can't get an A+, but all of the above issues dealt with, so :+1:

**Comment by ApfelUser** [comment]
@julianlam Do you want an A+? I could show you how.

**Comment by julianlam** [comment]
Nice, but not necessary, I think :smile:
