### ISSUE TITLE
Popular Topics and only 1 topic

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3060]
https://community.nodebb.org/popular
Home > Popular 

I'm checking Popular Topics page frequently and it shows wrong or random data.

![poptop](https://cloud.githubusercontent.com/assets/11160550/7219493/9c45289e-e6a3-11e4-96ec-6d2b6d010098.jpg)

**Comment by julianlam** [comment]
What's wrong in the screenshot?

**Comment by nhlpl** [comment]
Popular topics for 6 hours are probably:
How to distinguish the home page of the category page?
lugin section: Restart & Reload button [v.0.7.0]
Cannot create new topic
"leaving-subdomain" alert when connecting to a rootdomain link

More replies, more views.

**Comment by julianlam** [comment]
Eh, yeah... the algo needs work -- not sure if the topics just aren't selected properly, or are filtered out incorrectly.

Ideally, would be nice to have @barisusakli extend this system so that if there is a listener for `filter:topics.getPopular`, it passes the topics in and lets the plugin handle the popularity algo, otherwise fall back to the core-version, which is much simpler.

Then we could do neat things like use HackerNews algo, or Reddit algo :smile:

**Comment by barisusakli** [comment]
/popular/day shows topics posted in the last 24 hours sorted by post count. The topics you mentioned were posted more than 24 hours ago. If you go to /week it will show those.

**Comment by nhlpl** [comment]
Thanks for your explanation and time spent on checking it.
