### ISSUE TITLE
Choose theme in profile

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3069]
Feature request

Many users prefer dark themes (black background), most of users like light colored themes (Persona, white background) and some wants something in between with a grey bars on both sides (nodebb-theme-material 2.0).

On big boards you have to provide at least two themes to choose from.

**Comment by psychobunny** [comment]
It's possible to do it via Bootswatch (I think I had a play around with it some time ago). But changing the entire theme is probably not going to happen anytime soon because it would take a pretty big architectural change to the theme engine.

Maybe something to think about for post 1.0, but if skins are good enough, I could have a look

**Comment by julianlam** [comment]
I agree -- getting Bootswatch integrated is a fairly trivial task (and is actually a great use case for Bootswatch), but supporting swapping of themes on the fly is a non-trivial task that is a *nice to have*, but not ultimately necessary.

**Comment by nhlpl** [comment]
> EDIT: Also, have a look at 35hz they have a lightbulb on the top right which I think is a neat idea

Yes, this is what many users may want. Is there any chance for adding this feature so users no longer need to adjust monitor's brightness and contrast?

**Comment by pitaj** [comment]
Theme creators could add this feature themselves (a dark mode) if they wanted to.
