### ISSUE TITLE
Can't access plugins through admin panel

### ISSUE THREAD

**Issue by betzerra** [NodeBB/NodeBB#3077]
If I go to account *settings* and then *plugins*, it won't load (hangs there).

This is what I've found on the console (hope it helps):
![screen shot 2015-04-21 at 1 58 05 pm](https://cloud.githubusercontent.com/assets/681600/7257844/e3ea89c8-e82e-11e4-831d-63ab5f6cf873.png)

I'm using NodeBB v0.6.1 (branch: 0.6.x, commit: 7682b56d78998f750fe00aa656dc7870d741e673)

**Comment by betzerra** [comment]
Anyone? :-(

**Comment by Holyphoenix** [comment]
I'd try disabling all of your plugins.  It is likely one of them is breaking it.  Then you will have to enable them one by one to try and determine which it was.  Unless you know a plugin you installed just before this error occurred.  Then you disable just that plugin.  (it looks like it has to do with Markdown, so you can probably narrow your search down to plugins that have some correlation to markdown)

https://docs.nodebb.org/en/latest/plugins/create.html?highlight=reset

**Comment by betzerra** [comment]
@Holyphoenix 

Thanks a lot for your response. 
Unfortunately it didn't succeed. I even tried with `./nodebb reset all` any ideas?

Do you think that reinstalling nodebb and migrating the database to the new install would fix this? If that so, how do I do it? :-)

![screen shot 2015-04-24 at 2 10 01 pm](https://cloud.githubusercontent.com/assets/681600/7324325/da63c31a-ea8b-11e4-89a3-78679d22ef71.png)

**Comment by Holyphoenix** [comment]
Hmmm... I'm not sure a new install would fix it.  It might be caused by an old version of NodeJS or another piece of software NodeBB requires.  Since no one is responding to this ticket, except me, I'm going to recommend posting this issue out on the nodebb community forums to see if anyone else might have any ideas.  Let them know you already tried to reset everything with the reset command to get them up to speed, and you might include anything you remember doing on the forum or with your server around the time you started seeing this error.

Community forums are here:   https://community.nodebb.org/category

**Comment by barisusakli** [comment]
It's already posted here, most likely a config issue. https://community.nodebb.org/topic/4321/can-t-get-into-plugins-on-admin-settings

**Comment by betzerra** [comment]
Thank you guys, I'll keep you posted.
