### ISSUE TITLE
Slug transliteration

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3097]
Please tell me can I use the [transliteration module](https://github.com/andyhu/node-transliteration) in NodeBB core? Without the plugin. So it will be good to others and me.

**Comment by julianlam** [comment]
Hi @atomoc -- by default we leave the unicode titles for topics and categories as unicode, as they do not affect url routing ability. However, I do realise that they are not all that great when they are escaped, since they're percent encoded, in which case a transliteration would be ideal.

I feel it is best made as a plugin, so that topics and categories can have their slugs updated as they enter the database, although I am opening this to others in case they the same way as you do, that this would be best served in core.

**Comment by atomoc** [comment]
%D1%80%D1%83%D0%B1%D0%BB%D0%B5%D0%B2%D0%BE-%D1%83%D1%81%D0%BF%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5-%D1%88%D0%BE%D1%81%D1%81%D0%B5-%D1%84%D0%BE%D1%80%D1%83%D0%BC-%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%B9-%D0%BA%D0%BE%D1%82%D1%82%D0%B5%D0%B4%D0%B6%D0%BD%D1%8B%D1%85-%D0%BF%D0%BE%D1%81%D0%B5%D0%BB%D0%BA%D0%BE%D0%B2

:)

**Comment by atomoc** [comment]
I was very pleased that the native language is used in the address bar , not yet encountered problems in the field of SEO and not see it as above. Since then, I use Latin characters everywhere.

**Comment by leksar** [comment]
Would be nice

**Comment by andrewua85** [comment]
![image](https://github.com/NodeBB/NodeBB/assets/36643871/73eeaa0f-4f85-4cb9-b459-393117fcce64)
