### ISSUE TITLE
password are sent unhashed in the http headers

### ISSUE THREAD

**Issue by niklas-heer** [NodeBB/NodeBB#3099]
Hi folks,

I have search a little bit for this issue in, but I haven't found it so if this is a duplicate I'm sorry.

A user of [my forum](http://linux-statt-windows.org) informed me about this issue. We are using __nodebb 0.6.1__.

### The problem
He has discovered that the password is send without being hashed via the http-headers during login.

I searched around a little bit and found out that the passwords are hashed, but this [happens in the backend](https://github.com/NodeBB/NodeBB/blob/v0.6.x/src/user/create.js#L129), if I understood it correctly.
The [frontend send the unhashed password](https://github.com/NodeBB/NodeBB/blob/master/public/src/client/login.js#L27) to the backend, which is really bad, because this could be used for a man-in-the-middle attack since not all forums use SSL encryption (including myself, which will hopefully not be the case for too much longer).

![](http://linux-statt-windows.org/uploads/files/upload-d0f7b300-06d4-4d96-ba3d-6c846f71a8cd.png)

### My questions
1. Did I understand this correctly?
2. If 1 is true, could the password be hashed at the client-side?
3. If 2 is true, will you change it that way?

Thanks for reading my concerns and I would be very pleased to get a response soon! :)

Cheers,
Niklas Heer

**Comment by julianlam** [comment]
Hello @niklas-heer, thanks for bringing this issue up. I am glad to hear that our community has such dedication towards security.

Let me begin by confirming that **yes, we send the plaintext password in the `POST` request during login**.

I'd like to take some time now to explain *why* this is the case, and why this is an issue that we are not intending to fix. Please be advised that I do not have a security background, so others may be able to explain this more clearly/succinctly:

1. When it comes to password security, we **hash** passwords on the server-side, so in the event of unauthorised database access, the leaked passwords are next to useless as they would be computationally exhaustive to crack. When you set a password on a stock NodeBB installation, not even the admin can discover what the password is after it has been encrypted.
1. When it comes to client->server communication, it is just not possible to have data encrypted in such a way that it is parsable by both client and server. Let's work through a thought experiment:
    * If my password is `abcdef`, and the client *encrypts* it, then it needs to do so using some sort of key that the server also has access to.
    * How does the client get this key? Does it request it from the server? If so, a malicious would be able to ping the same endpoint from the server to retrieve this key, rendering the encryption useless.
    * If you limited it to a computed secret based on IP address (or session key, or something), then it is still insecure in the event of MITM.
    * No matter what you do, you are a) reinventing the wheel, or b) just adding barriers that can be byased, **not** increasing security.
1. The best way to prevent this is through HTTPS. Then the request *itself* is secured, and the data is not suceptible to MITM attacks.

We do stress that all sites be accessed through HTTPS, because of this.

Also, as a point of reference, might I also point out that logging in to Facebook sends my password in plaintext as well? :smile: 

![selection_001](https://cloud.githubusercontent.com/assets/923011/7374073/3c3e5414-ed9e-11e4-8d82-ff487d3f6eda.png)

**Comment by niklas-heer** [comment]
Thank you very much for your fast and detailed reponse @julianlam! :)

Your points really make sense to me. So my only suggestion would be to add a section about a setup with HTTPS e.g. for [nginx](https://docs.nodebb.org/en/latest/configuring/proxies/nginx.html), to make it easier for new users to think about that!

Keep on rockin'! :)

**Comment by sgodwin424** [comment]
@julianlam While your points are valid, in my experience, it is best to hash the password on the client, not encrypt it. In this case, the hash of the password serves as the password as far as the server is concerned. While a middle-in-the-man attack is still possible with this method, it prevents any attacker from retrieving the plaintext password which many people will use for other websites.
