### ISSUE TITLE
can't login as admin nor register a new account

### ISSUE THREAD

**Issue by highestblue** [NodeBB/NodeBB#3164]
I was able to install NodeBB on both my Mac and Windows without a hitch by following the docs. However, on my Heroku installation, I get a forbidden error when I try to login as admin or register a new account.

Following are the error messages I get on the dev console:

Uncaught SyntaxError: Unexpected token &
Uncaught TypeError: Cannot read property 'maxReconnectionAttempts' of undefined
>i @ nodebb.min.js?ae5c77f7:14
>(anonymous function) @ nodebb.min.js?ae5c77f7:14
>(anonymous function) @ nodebb.min.js?ae5c77f7:14

Uncaught TypeError: Cannot read property 'loggedIn' of undefined
>(anonymous function) @ nodebb.min.js?ae5c77f7:14
>w.Callbacks.u @ nodebb.min.js?ae5c77f7:1
>w.Callbacks.f.fireWith @ nodebb.min.js?ae5c77f7:1
>w.extend.ready @ nodebb.min.js?ae5c77f7:1
>P @ nodebb.min.js?ae5c77f7:1

Any help would be appreciated. Thanks.

**Comment by MegaGM** [comment]
I have the same errors, on Linux installation.
http://i.imgur.com/LhguYBf.png

Perhaps it's somehow related to theme. Because while I switch theme from my custom to the latest Persona, these errors are disappearing. I don't have a clue why, yet.

Execute please this command in your terminal, to provide for core developers more information
```
$ npm ls nodebb-theme-lavender nodebb-theme-persona templates.js
```

**Comment by highestblue** [comment]
It works fine if I run it locally using *foreman start web*

**Comment by barisusakli** [comment]
Let us know if you still have this issue on 0.7.x
