### ISSUE TITLE
Favicon configuration

### ISSUE THREAD

**Issue by thelinuxlich** [NodeBB/NodeBB#3302]
The upload works, it's a 32x32px ICO, I can see the new path, but it's not applied to the forum

**Comment by barisusakli** [comment]
Did you restart the forum and clear cache?

**Comment by thelinuxlich** [comment]
restarting the forum did the trick

**Comment by mrgame64** [comment]
I'm asking to reopen this issue, clearing the browser cache and restarting the forum don't change anything, as the default favicon is still the one to be loaded.

NodeBB v0.7.2

**Comment by barisusakli** [comment]
Did you click save after uploading it?

**Comment by mrgame64** [comment]
Upon pressing "Save changes" and refreshing the page, the favicon path is reset

**Comment by mrgame64** [comment]
Ok, it turned out that my server's internal cache wouldn't flush, after a system-wide reboot it's fine

**Comment by benjaminabel** [comment]
Hi, I'm getting the same problem using v0.7.2. I think the problem is caused by the fact that I'm running my forum in a **subdomain** eg <https://lyceum.fr/forum/>.

When I upload the favicon in the admin console and save changes, the path in the input field is changed to `/forum/uploads/system/favicon.ico`, my favicon is saved in `/public/uploads/system/favicon.ico`. And nodeb always use the default favicon as the function [setupFavicon](https://github.com/NodeBB/NodeBB/search?utf8=%E2%9C%93&q=faviconpath) can't find the file in `public/`**`forum`**`/uploads/system/favicon.ico`

**Comment by julianlam** [comment]
Thanks guys I'll take a look at it now.

**Comment by julianlam** [comment]
Confirmed, file path when uploaded is `public/{relative_path}/uploads/system/favicon.ico`, when it should not have relative path at all.

**Comment by benjaminabel** [comment]
@julianlam Are you working on this or you prefer a PR?

**Comment by julianlam** [comment]
I'm working on this right now.

**Comment by benjaminabel** [comment]
Thank you. Nice job:)
