### ISSUE TITLE
Rename "Favourite" to "Bookmark"

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3320]
Favourite seems redundant - we built that feature a long time before creating the "like" / upvote system. In fact, the original favouriting system used to give reputation points, the functionality of which has since been moved to upvoting.

So now, favouriting has no actual additional benefit besides storing the post for later reference on your account page. 

If we make this change, I believe you should be able to "bookmark" your own post as well (currently disallowed).

RFC :)

**Comment by julianlam** [comment]
I have no objection to this, except I should point out we also use "bookmark" to refer to the last read post in a topic.

But we should also export the favourite functionality out of NodeBB core while we're at it :smile:

**Comment by bdharrington7** [comment]
Will this change only remove the `favourite` functions out of the Favourites module, leaving the `upvote` and `downvote` functions intact? Will that module then be renamed?

I would argue that calling it "Favourite" still makes sense, except in the case where a user would be able to favourite their own post. Bookmark then makes more sense, but then that's the same nomenclature as saving your spot in a thread. 

Maybe call it "Watch"? or "Follow"?

**Comment by psychobunny** [comment]
> I have no objection to this, except I should point out we also use "bookmark" to refer to the last read post in a topic.

.

> Bookmark then makes more sense, but then that's the same nomenclature as saving your spot in a thread.

Hmm, actually both of those statements are not fully accurate - first off, the "bookmark" language is currently only written in code.

UX wise, the current functionality is "where I left off" as opposed to "where I decided to return to" (aka bookmark). If you think about it, those are two very different things

**Comment by psychobunny** [comment]
Or did I mean dog-earing? Geez, who reads books anymore anyways.

**Comment by bdharrington7** [comment]
If we continue this book analogy, we could liken a forum to a library,
where each topic is a book. To keep your place in a book (where you left
off), you'd use a bookmark (or if one's not available, dog-ear the page).
So then what would we use to keep track of the status of a book?

I can't really think of a good analogy here, and this is where the analogy
fails, since threads typically are updated more often than books.

Unless you think of it less like a library of books, and more like a
library of magazines: you can subscribe to get updates.

Yeah?

**Comment by martyalicante** [comment]
Totally agree
