### ISSUE TITLE
W3C validator errors

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3444]
If you run the [NodeBB Community Forum](https://community.nodebb.org/) through the [W3C Validation Service](https://validator.w3.org), you'll see quite a few errors. It would be good if NodeBB (this possibly applies to Persona) was able to pass these validation checks.

**Comment by psychobunny** [comment]
This is really a huge meta issue that would never be closed simply because of the amount of work required to fix. I would suggest breaking it up into smaller easily tackle-able issues. Also it's best posted on the theme repo's and not in core, because it is agnostic to markup:

https://github.com/nodebb/nodebb-theme-vanilla
