### ISSUE TITLE
Breadcrumbs missing from various pages

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3475]
I'm not sure if this is a Persona-related issue (or even if it's an issue at all) but it seems some pages don't have breadcrumbs yet some do. It would be nice to keep the breadcrumb trail consistent across all pages.

 - example.com/users
 - example.com/users/online
 - example.com/users/latest
 - example.com/users/sort-posts
 - example.com/users/sort-reputation
 - example.com/users/map
 - example.com/users/search
 - example.com/notifications
 - example.com/chats
 - example.com/chats/_username_
 - example.com/user/_username_
 - example.com/user/_username_/edit
 - example.com/user/_username_/settings
 - example.com/user/_username_/following
 - example.com/user/_username_/followers
 - example.com/user/_username_/topics
 - example.com/user/_username_/posts
 - example.com/user/_username_/groups
 - example.com/user/_username_/favorites
 - example.com/user/_username_/watched
 - example.com/categories
 - example.com/unread
 - example.com/groups

I've been through all of the pages that get generated and that should be all of the ones that are missing them.

**Comment by julianlam** [comment]
:smile: Awesome! Such a nice curated list of pages to add breadcrumbs to :+1: 

@barisusakli just a note -- I recall being unable to use the `account_menu` partials in my own plugins, though right now I can't recall why. Maybe it was because it used data that my plugins didn't send, like `userslug` and `uid`... maybe they can be accessed in other ways?
