### ISSUE TITLE
Suggestion: Add classes to body element

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3505]
Currently the HTML body element has no class:

    <body>

If each NodeBB page were to add a class such as:

    <body class="categories"> 

    <body class="recent"> 

    <body class="user henrywright"> 

We could do things like this in our Appearance > Custom HTML & CSS:

    body.categories h1 {
        // Something.
    }

    body.recent h1 {
        // Something completely different.
    }

The markup necessary in our themes is then drastically reduced because we can just have the following in every template:

    <h1>

Instead of stuff like:

`<h1 class="categories">` and `<h1 class="recent">`

Just an idea.

**Comment by ApfelUser** [comment]
+1

**Comment by psychobunny** [comment]
Right now, nearly every route has it hard-coded:

```
<div class="categories">
```

So that would require removing on each theme + route.

Also we should prepend it with `page-` - I've have had experiences in other projects where a route conflicted with another class, not fun.


Lastly, we also need to append the current bootstrap theme in this same method so we can override CSS. (see https://github.com/NodeBB/nodebb-theme-persona/issues/118 etc)

**Comment by lots0logs** [comment]
+1 :+1:

**Comment by barisusakli** [comment]
`<div class="page-{template.name}">` :angel:

**Comment by henrywright** [comment]
@barisusakli the `template.name` property isn't brilliant because on pages such as user/henrywright/following it outputs `account/following`. I'm thinking a list separated by spaces would be better? Something like `account following henrywright`

**Comment by psychobunny** [comment]
I did this in our other projects by replacing slash with dash so `.page-account-following`

**Comment by henrywright** [comment]
@psychobunny the reason I pointed out the use of separate classes is because that way you can do stuff like target all account pages at once, or target a single account page only etc. For example:

```CSS
.account {
    /* Gets you all account pages */
}
```
```CSS
.account.henrywright {
    /* Gets you my account page only */
}
```
```CSS
.account.following {
    /* Gets you the following page only */
}
```
You can't do those things with a single class like `.page-account-following`

**Comment by lots0logs** [comment]
WordPress makes extensive use of the body classes for theme styling. Each view has a special class that is applied by default plus themes can add additional classes if they want. I know its a little different in this case because the body is only loaded on a cold load, but the same principal applies. For example, with WordPress you have the following default body classes:

**Homepage:** `home`
**Page:** `single single-page page-id-xxx`
**Post:** `single single-post post-xxx`
**Category:** `archive category category-xxx category-cat_slug`

So for NodeBB it might look like this:

**Homepage:** `home`
**Topic:** `topic topic-id-xxx`
**Recent:** `archive archive-recent`
**Popular:** `archive archive-popular`
**Category:** `archive category category-xxx category-cat_slug`
**Child Category:** `archive category category-xxx category-cat_slug category-parent-xxx`

**Comment by henrywright** [comment]
@lots0logs :+1:
