### ISSUE TITLE
ACP: setting for maximum images in one post

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3509]
IMO setting should be 5 as default maximum; everything else renders as a link. Needs to hook into markdown / redactor so pinging @julianlam for thoughts. Currently someone can put 200 images in a post if they wanted to.

**Comment by tedr56** [comment]
I second that.
Even if they're not posting 200 images.
I have a picture based topic, and they just have to share 10 each posts.
The page gets large easily, even in page paging mode.

ps: the post cursor gets rarely to the right place too (on first loading)

**Comment by julianlam** [comment]
@tedr56 As you can imagine, the post scrolling rarely gets to the proper place because we don't have image dimension data until the image itself has loaded. 

On small numbers of images, you could make the argument that we could wait for all images to load (there's a jquery plugin for this, of course.) and then scroll, but there is a noticible delay when this is done. 

Factor in browsers limiting the number of parallel connections, and the 90th of 100 images may not even begin loading until 5 or 10 seconds have elapsed. Simply put, if we waited for all images to load, users would become frustrated and leave. 

We are open to solutions...

**Comment by tedr56** [comment]
Maybe it's possible to read the images properties or headers, to have more information on the picture size?

**Comment by tedr56** [comment]
It's seems that's not possible before file is completly loaded. :/

**Comment by julianlam** [comment]
This got me thinking about the problem again. It may be possible to read the image size server side, cache the result (for speed) and simply append width and height style declarations to the image tag. 

There would still be a slowdown, but it's something we can consider implementing...

**Comment by tedr56** [comment]
It could involve scheduling the server side preview download.
And set the image container size of it.

**Comment by tedr56** [comment]
It would be good to have a safety (cliend side?), to know if the image hasn't change of size.
Unlikely, but possible.

**Comment by barisusakli** [comment]
Another idea, instead of using full size responsive images, just put in thumbnails.

![image](https://cloud.githubusercontent.com/assets/2583394/9585369/76b334d6-4fe4-11e5-90d5-d154af6d9826.png)

**Comment by julianlam** [comment]
That's a neat idea. Imgur can alter the image as it leaves nodebb...

**Comment by julianlam** [comment]
Jelly-potato has been solved:tm: for awhile now in a different issue, and the problem with loading many thousands of images is better handled via plugin, in my opinion...
