### ISSUE TITLE
Searching for links breaks search.

### ISSUE THREAD

**Issue by mastacontrola** [NodeBB/NodeBB#3629]
I don't know if this is limited to the dbsearch plugin or not, and am not up for switching out our current search to simply verify.  If it is the dbsearch plugin, specifically, please let me know and I will post the bug to the appropriate repo.

While there are multiple issues already reported about the NodeBB search functionality being rather, well, limited, I have found that picking key words (if they're long enough) tends to help in finding a relevant thread more easily.

In trying to search a forum post, the words of the title and potential contents were too non-specific and we already are aware that the searching in this manner is rather limited.

One of the things I noticed, however, was that there was a link in the quotation of the thread.  I decided to attempt searching for it, and it just spun and spun.

After 3 minutes, I decided to refresh the page and it returned in an error. The URL had changed, as expected.

The specific link I was attempting to search (but i soon found out it could be any link) was `http://clonezilla.org/livepxe.php`

The url changed to `https://forums.fogproject.org/search/http%3A%2F%2Fclonezilla.org%2Flivepxe.php?in=titlesposts`

Now if you attempt to go to that link (regardless of how it's written) it will present an error page that the information doesn't exist.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/6e66b32fe1277e39db7534792c1791a81ca7b53d

Might resolve some of the search issues. I would wait for the next release to update though.

The problem was the search term was escaped before it was sent to the search plugins so in case you searched for `"some phrase"` it was searched as `&quot;some phrase&quot;` The above commit fixes that.

Another thing to note is if you are using mongodb you can use phrases and seems like searching for a url also works better if you put it in double quotes.

If I search for `http://youtube.com`

![image](https://cloud.githubusercontent.com/assets/2583394/9948370/6ac349b0-5d70-11e5-8625-4fd0889d7d19.png)

If I search for `"http://youtube.com"`

![image](https://cloud.githubusercontent.com/assets/2583394/9948378/7f910b8e-5d70-11e5-86b4-99632ce84207.png)
