### ISSUE TITLE
Firebase auth

### ISSUE THREAD

**Issue by randohinn** [NodeBB/NodeBB#3713]
Would be awesome if this could integrate with Firebase email & password auth, so I could integrate it with my existing setup.

**Comment by julianlam** [comment]
Hey there -- we've had these inquiries before, and while they're great in terms of extensibility, we're not likely to include that in core due to the low level of usage. The best avenue for this would be a plugin, that automatically allowed you to use Firebase to connect to multiple providers, although at present, [the library that I've found](https://github.com/Rigidflame/firebase-passport-login) is not production-ready yet.

Feel free to continue this conversation on our [community support forum](https://community.nodebb.org)! :smile:
