### ISSUE TITLE
Email notifications: very big images

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3717]
Email notifications with images (emoticons) are very big. Style for emoticons should be applied in email notifications.

**Comment by barisusakli** [comment]
https://github.com/frissdiegurke/nodebb-plugin-emoji-extended/blob/master/coffee/email.coffee

It already is what version of emoji plugin?

**Comment by NicolasSiver** [comment]
<img width="828" alt="screen shot 2015-10-08 at 4 32 04 pm" src="https://cloud.githubusercontent.com/assets/135263/10378991/3195bf4a-6dda-11e5-9411-b9e44bada9dd.png">

**Comment by barisusakli** [comment]
0.4.14 is latest but will only work with nodebb master.

**Comment by NicolasSiver** [comment]
Latest is `0.4.15` - https://www.npmjs.com/package/nodebb-plugin-emoji-extended

Is it by design, that current NodeBB `0.8.2` doesn't provide update higher than `0.4.13`?

**Comment by barisusakli** [comment]
Yes 0.8.2 is compatible with 0.4.13 thats why it doesn't show anything higher in acp.

**Comment by NicolasSiver** [comment]
What version do you use on your community forum? 
I have received it 1 day ago: 

<img width="871" alt="screen shot 2015-10-08 at 4 37 50 pm" src="https://cloud.githubusercontent.com/assets/135263/10379166/09567168-6ddb-11e5-8598-ace8df3cf531.png">

same problem ;)

**Comment by barisusakli** [comment]
It's on 0.4.14 so prolly needs updating to .15

**Comment by NicolasSiver** [comment]
I don't think so.

This _change_ around from very previous versions: 

https://github.com/frissdiegurke/nodebb-plugin-emoji-extended/commit/35991320b5c6d60be5241a41237f861bfb385a10

**Comment by barisusakli** [comment]
Its the hook that changed `filter:email.modify` `action:email.send` and `filter:email.send`

**Comment by NicolasSiver** [comment]
So plugin is broken, I assume, plugin author introduced to high compatibility limit:

https://github.com/frissdiegurke/nodebb-plugin-emoji-extended/blob/master/package.json#L22 :)

**Comment by frissdiegurke** [comment]
I actually cannot see why NodeBB shows you `0.4.13` as latest. according to manual check (https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-emoji-extended&version=0.8.2) the NBBPM does provide the correct suggested version.
And `semver.satisfies("0.8.2", ">=0.7.2 <0.10.0") === true` as expected.

**Comment by frissdiegurke** [comment]
I have to admit that `0.4.13` is actually best fit for NodeBB `>=0.8.2 <0.9.0` but since the proper email-support was just introduced within NodeBB `0.8.2` I didn't feel like it could be necessary to limit the version-range for NodeBB `0.8.2` to end with `0.4.13` while `<=0.8.1` would more benefit from later versions.
I'm sorry for that.

The actual reason for not being shown properly may be the emailer filtering styles rather than the plugin not delivering (since `0.4.14` already contained `0.9.x` compatibility). At least within mandrill you have to explicitly enable inline-styles otherwise it just strips styles out. I'm sure the other emailers have similar options.
