### ISSUE TITLE
better looking digest emails

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3755]
:sparkles:

**Comment by pitaj** [comment]
Isn't it already possible to customize the digest template? In the case that it is, this would simply require more data to be passed to the template (like notifications, recent topics, hot topics, etc)

**Comment by barisusakli** [comment]
The defaults that come with a clean install should at least have some better styling. And yes you can customize them in the ACP now.

**Comment by julianlam** [comment]
Yeah, the templates themselves were written in 2014, and I they were really ugly because:

1. I'm not a good designer
1. Google at the time didn't let emails have stylesheets

Not sure if the latter has changes, but after seeing what @psychobunny can do with email templates, I'm more than happy to hand over the reins on this one :smile:

**Comment by julianlam** [comment]
Latest develop has new email templates :star2:
