### ISSUE TITLE
[RFC] Consider Nodemailer instead

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3756]
https://github.com/andris9/Nodemailer

Ghost uses this. Seems better than handrolling our own emailer plugins, and it has a ton of other features as well

**Comment by pitaj** [comment]
:+1: Absolutely. Would make emailer plugins about 2000% easier.

**Comment by psychobunny** [comment]
The other neat thing is that it automatically translates the plaintext version

Right now nodebb requires you to write two templates per email

**Comment by julianlam** [comment]
Wouldn't mind tackling this and moving from RFC to Enhancement.

Main stopping from doing this before was that I didn't have a reliable way to send email without using a dependency (e.g. sendmail, postfix) or third-party service (mandrill, sendmail).

Now, things have changed:

* We have a system set up so that third-party emailers can be used
* [NodeMailer has a direct transport](https://github.com/andris9/nodemailer-direct-transport) so emails can (somewhat unreliably) be sent without need of a dependency
* Mandrill (our preferred emailer) no longer has a free tier, which makes their service less attractive to forums looking to minimise expenses

Also if no emailer is installed, NodeBB simply doesn't do anything at the moment, so I'd imagine doing *something*, even if it doesn't always make it to the inbox, is better than nothing...

**Comment by pitaj** [comment]
:+1: absolutely. If anything, you can just ask people to whitelist the forum email.

**Comment by lots0logs** [comment]
> Mandrill (our preferred emailer) no longer has a free tier, which makes their service less attractive to forums looking to minimise expenses

Mailgun still has a free tier. I've been using their service for a couple years without issue. Would this change still allow use of services like Mailgun?

**Comment by pitaj** [comment]
@lots0logs I'm thinking that's an "of course"

NodeMailer has plugins for Mailgun, Mandrill, etc so it would actually be much easier to keep everything up to date.

**Comment by julianlam** [comment]
I can't find a free tier on their website (last I checked was perhaps a
month ago so maybe things changed)... Maybe it's just not advertised?

**Comment by lots0logs** [comment]
@julianlam I think you misunderstood me. I mentioned Mailgun's free tier as an alternative to Mandrill since they no longer offer one.

**Comment by akhoury** [comment]
+1

**Comment by julianlam** [comment]
@pitaj Right now not entirely sure how we'd hook existing emailer plugins into the nodemailer transport, but I can probably work on a basic version for situations where you have no emailer plugin installed/setup at all...

**Comment by julianlam** [comment]
Using nodemailer direct transport to send emails if no emailer is available.

**Comment by pitaj** [comment]
>Right now not entirely sure how we'd hook existing emailer plugins into the nodemailer transport
Yeah, seems like you'd need a new hook or something for that. 

Anyways, you ought to warn the user about using direct transport, and how it can be marked as spam.
