### ISSUE TITLE
Emailer not working

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3795]
I created the issue in the [nodebb-plugin-emailer-mailgun](https://github.com/julianlam/nodebb-plugin-emailer-mailgun/issues/7), but this problem is more related to the NodeBB. All plug-ins to work with e-mail is not working:
![2015-10-27 19 19 43](https://cloud.githubusercontent.com/assets/465108/10784426/18c0b700-7d6f-11e5-81cf-618f5efe44c9.png)

NodeBB: last version

**Comment by edasque** [comment]
NodeBB 0.0.9 now requires filter:email.send of email plugins instead of action:email.send of its emailer plugins (https://github.com/NodeBB/NodeBB/commit/dbf0f279a2d061a244b0d28a3681fb59e84abb00). Mailgun & Mandrill have been updated but I don't think it necesserarily pulls the latest version, resulting in thinking the plugins haven't been installed.

**Comment by atomoc** [comment]
NodeBB 0.9.0? And where can I get it?

**Comment by atomoc** [comment]
Thanks! I changed the `action:email.send` on `filter:email.send` file **nodebb-plugin-mailer-mailgun/plugin.js** and plug-earned!

**Comment by edasque** [comment]
:+1:
