### ISSUE TITLE
Post image is not scaled properly on mobile devices

### ISSUE THREAD

**Issue by luofan189** [NodeBB/NodeBB#3826]
<img width="384" alt="screen shot 2015-11-03 at 11 16 55 pm" src="https://cloud.githubusercontent.com/assets/1351099/10928665/256793c2-8281-11e5-8044-0c2cd32e50e9.png">

The image (it is a URL) in the post is not scaled properly on mobile devices, see screenshot above. I am running 0.8.2 with them lavander

**Comment by barisusakli** [comment]
Where is this image? In a topic? In a widget?

Also post your theme version.

**Comment by luofan189** [comment]
The image is just an image URL, I use redactor composer, lavender 2.0.13. This is in a topic.

**Comment by barisusakli** [comment]
Can you post the html source for the image? Images should have a `img-responsive` class on them.

**Comment by luofan189** [comment]
<img width="511" alt="screen shot 2015-11-08 at 1 05 27 pm" src="https://cloud.githubusercontent.com/assets/1351099/11021508/6e26031e-8619-11e5-8331-897424f0c07e.png">

Attached source code, it does not have <code>img-responsive</code> class. Adding it to the ```img``` tag does fix it. You could check the source here: http://iduo.ca/topic/883, btw, I am using the readactor composer not the default markdown one, not sure if this is relevant.

**Comment by luofan189** [comment]
Also, after I upgraded to 0.9.x, the name avatar is not displayed properly except on the user profile view. I could create a new defect if you want.

**Comment by barisusakli** [comment]
That's probably why its happening ie no markdown/default composer.

**Comment by luofan189** [comment]
So you suggest this is a bug of redactor composer?

**Comment by barisusakli** [comment]
It is a side effect of not using markdown, the markdown plugin parses images and adds two classes to them here https://github.com/julianlam/nodebb-plugin-markdown/blob/master/index.js#L154

Since you are not using it the images don't have those classes. Either composer-redactor plugin has to add the img-responsive class or we need to find another solution @julianlam

**Comment by luofan189** [comment]
I see. It is best if nodebb could handle the image url rendering properly, as to me, composer-redactor does the composing job properly and adding ```img-responsive``` attrs should not depend on the default markdown composer plugin. But I am glad that the issue has been identified, I will find workaround for my site for now and you guys could determine what the approach is.

**Comment by barisusakli** [comment]
Yeah I agree `img-responsive` should be added even if you are not using the markdown plugin, although it is a bit tricky doing it server side. Since redactor stores plain html and markdown stores well markdown. 

We can do it client side after the page is rendered and add img-responsive, we already do this for posts that are loaded dynamically.

**Comment by luofan189** [comment]
Great, thanks @barisusakli , look forward to the fix in 0.9.1 release.
