### ISSUE TITLE
Re-evaluate app.alertSuccess etc

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3828]
Might be good for editing or admin, but right now it's used in a few places where we should write proper titles (ex. SUCCESS! You unfollowed this user)... Very abnormal msg that you wouldn't get on FB, twitter for ex.

**Comment by julianlam** [comment]
`alertSuccess` and `alertError` were added solely because `app.alert` was too complicated, although I don't recall it being especially complicated at all, since [the method takes a single argument, and all properties are optional](https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/alerts.js#L7-L19)

Here's what happens when you call `app.alert({});` :laughing: 

![selection_019](https://cloud.githubusercontent.com/assets/923011/11045774/87b2d88c-86f7-11e5-9426-d6e5044a777c.png)


IMO deprecate alertSuccess and alertError altogether.

**Comment by julianlam** [comment]
I'll admit that perhaps the property names are hard to remember, so maybe we can deprecate the two helper methods once Visual Studio Code has proper intellisense for Node.js apps :trollface:

**Comment by barisusakli** [comment]
I am against this change. You would have to replace

```
app.alertError(err.message);
```

with

```
app.alert({
	title: '[[global:alert.error]]',
	message: message,
	type: 'danger'
});
```

everywhere, where only the message is changing.

**Comment by yariplus** [comment]
I like having these helper methods. I don't think the 'SUCCESS' title is that unusual, and there could always be an optional second argument for a custom title. The code looks a lot nicer either way.

**Comment by julianlam** [comment]
> an optional second argument

That's a slippery slope @yariplus :smile: That's exactly why `app.alert` got abstracted into these helper functions anyway :laughing: 

I'd prefer cases where @psychobunny's original stated problem occur (e.g. "Success! You've unfolowed a user"), should simply be rewritten to call `app.alert` directly.
