### ISSUE TITLE
Provide ability for plugins touch content (replace) 

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3897]
Markdown plugin is very aggressive, and if you try to replace something before it. Markdown plugin will convert html to simple string.

In long terms, rely on parsing html content, isn't a good choice.
What if user will use something different than Markdown Plugin?..

**Comment by julianlam** [comment]
As you cannot trust any content coming from the userland, html sanitisation is here to stay. 

Open to suggestions, but our traditional advice has been to have your plugin listen  *after* markdown does its thing.

**Comment by NicolasSiver** [comment]
Why Administrators of resources can't decide what they want?
Sanitation? Move it to the core, and do it as a part of security model.
And Markdown plugin have to do markdown, not to introduce dependency for all plugins to parse It's result.

**Comment by julianlam** [comment]
Markdown sanitises at the plugin level because:

1. The markdown parser we use offers it
2. It used to be part of core, but was extracted out into the Markdown plugin

To be honest I don't see a big issue with having Markdown parse it. Either way someone will be unhappy. If I sanitize at the beginning, then you will not be able to detect html code in your plugin as it will have been sanitized already (into `&gt; and &lt; etc), and if I sanitise at the end, then plugins will not be able to output HTML into the stream because it'll get sanitised.

Removing html sanitisation altogether is not a good option for security purposes, but can be toggled off by an admin if desired.
