### ISSUE TITLE
Upvoting banned members

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3943]
It doesnt have sense to uptove/downvote post of a banned member

**Comment by psychobunny** [comment]
On forums I have been at, I've seen banned members (banned not from spam but from violating rules) that still have very valid posts. Sometimes the moderator who banned may have been too harsh but the community at large agree with the banned poster.

I agree with you for spam, but I don't think we should prevent the community from speaking their voice if they disagree with the moderators ban.

Could be an option in ACP, but I definitely don't think it should be default because it takes away from the community's ability to express themselves. 

RFC

**Comment by martyalicante** [comment]
In my opinion is ok banned member keep his reputation but leting it to get more votes while banned is just perfect situation for trolling the reputation system 
Happened already on my forums

**Comment by NukeRusich** [comment]
I agree with Psychobunny.

**Comment by akhoury** [comment]
agree with @psychobunny

**Comment by julianlam** [comment]
I agree as well.
