### ISSUE TITLE
Composer window is cut off

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#4004]
Composer window will be cut off on window sizes with height smaller than X

<img width="591" alt="screen shot 2015-12-25 at 10 13 20 am" src="https://cloud.githubusercontent.com/assets/4553795/12004066/37109262-aaf0-11e5-8ef8-7c40fda7ca71.png">

**Comment by NukeRusich** [comment]
Can you give a better screenshot with a less strict crop? As far as I can tell, the problem is that your browser is not scrolling with the new line. Also, the icon at the top is cropped partially indicating this is the issue. Which browser are you using?

**Comment by julianlam** [comment]
Odd, I typed a reply to this but it didn't seem to post. Either way:

This is intentional, as the composer is "best used" at a certain minimum height, so once it is less than that minimum, it starts to slide away like a drawer.

Ultimately it's up to the composer itself, and possibly the theme to override if desired.

[Might be this line here](https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/less/composer.less#L147)
