### ISSUE TITLE
Some suggest about nodebb

### ISSUE THREAD

**Issue by Xuchenhao** [NodeBB/NodeBB#4042]
As we all know, nodebb had a very prefect Hotlink Protection. If users haven't loggined the server will return 403 for the png,jpg,bmp,etc, and tell CDN node do not cache that.
I think this is bad for some webmasters which they don't have a large Upstream bandwidth like who in China.
Cloud NodeBB use a way to separate Static Resources to a new host like https://cdn.xxx.love to store.

**Comment by Xuchenhao** [comment]
like this image http://moeclub.net/uploads/profile/90-profileimg.png
cdn never HIT

**Comment by julianlam** [comment]
Hi @Xuchenhao -- NodeBB will return a 403 for assets which are considered private, although using a cdn defeats this protection, because then the CDN asset would be directly accessible anyhow.

If you want the CDN to cache the image, you can disable the relevant option in the ACP so the images will no longer be private.
