### ISSUE TITLE
missing default enable sound in user profile

### ISSUE THREAD

**Issue by Pappmann** [NodeBB/NodeBB#4052]
all new users have the option sound disabled, need function in admin/settings/user to enable it by default for new users.

**Comment by Luchanso** [comment]
Yeah, this function is needed

**Comment by Luchanso** [comment]
Maybe have variant how to fast fix this?

**Comment by Luchanso** [comment]
@Pappmann, this <a href="https://github.com/BonchForum/nodebb-plugin-fix-sound">plugin (nodebb-plugin-fix-sound)</a> fix it for new users.

I don't know other solutions how to fix this. But i am searching it.

**Comment by Pappmann** [comment]
thx

**Comment by julianlam** [comment]
@Pappmann Is the issue that the following option is unchecked on user creation?

![selection_098](https://cloud.githubusercontent.com/assets/923011/13224519/f0afb0d8-d956-11e5-8a68-4d2293cc8c43.png)

Or is the value itself wrong? (as in, checked, but user doesn't actually have sounds)...

If the former, then it is done so in order to not surprise users who are not expecting sounds from NodeBB. If the latter, then that is a bug.

**Comment by Pappmann** [comment]
option is normaly unchecked for new users, https://github.com/BonchForum/nodebb-plugin-fix-sound has fixed the problem.

**Comment by pichalite** [comment]
so this can be closed?

**Comment by Pappmann** [comment]
no, the plugin is a temporarily fix.

Best way will be a switch in ACP that override setting for all users.
