### ISSUE TITLE
Fullscreen or 75% composer window by default

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4291]
https://community.nodebb.org/topic/8043/are-there-any-plugins-or-themes-that-change-the-way-the-reply-box-works

Feature Request
Low priority

New users don't know how to resize composer. Please read posted topic link for more information.

**Comment by julianlam** [comment]
@pitaj @pichalite Perhaps if the viewport height is below a certain threshold, the composer should be 75% or even full.

**Comment by pichalite** [comment]
@julianlam probably a better way to do is set it to 50% if it's less than 50?

**Comment by julianlam** [comment]
The problem right now is that those with small viewports, the composer is in "partially closed drawer" mode... that is, the bottom of the textarea is below the viewport.

It's a neat effect since you want to have some sort of minimum height in the composer, but its purposes is defeated if the viewport itself is too small.

We trigger a "mobile" mode if bootstrap environment is xs or s... perhaps we should also do the same on short viewports.
