### ISSUE TITLE
Feature Request: Thread muting

### ISSUE THREAD

**Issue by RaceProUK** [NodeBB/NodeBB#4388]
Apologies if this has already been requested.

Would it be possible to add the ability to mute threads? Ideally in such a way that they won't show on the Unread list, though you could view them on a special Muted list if you really wanted to, just in case you want to unmute in the future.

I don't have a solid design in mind, more a sort of vague concept. But I'm sure collectively we'll come up with something :smile:

**Comment by asdf-tdwtf** [comment]
I think this feature is pretty important for power users. Once a new thread is created, I want to be able to decide whether I'm interested in it or not, i.e. whether I want it to show up on the "unread" tab.

**Comment by Landkeks** [comment]
BTW, not sure "muting" is a good description for the feature I miss most: I mostly want some threads to not show up in the "unread" tab. If I'm specifically @-mentioned in one of them, I might still want to get a notification. "Muting" would probably suppress those notifications.

Basically, my request is: Implement the same thread states (Muted, Normal, Watching, Tracking) as Discourse. ;) Muting is not super-important, but having the "normal" state (i.e. don't show updates) is.

**Comment by asdf-tdwtf** [comment]
BTW, not sure "muting" is a good description for the feature I miss most: I mostly want some threads to not show up in the "unread" tab. If I'm specifically @-mentioned in one of them, I might still want to get a notification. "Muting" would probably suppress those notifications.

Basically, my request is: Implement the same thread states (Muted, Normal, Watching, Tracking) as Discourse. ;) Muting is not super-important, but having the "normal" state (i.e. don't show updates) is.

**Comment by albertdev** [comment]
>  (Muted, Normal, Watching, Tracking)
For those who have been spared from Discourse, here's what each one does:

<dl>
<dt>"Muted"</dt>
<dd>Topic is entirely ignored - the topic is visible in general views where you present all topics in a category but you will not get any notifications if a user replies to your post, @ mentions you or does anything else. The topic does never show up on the Unread list</dd>
<dt>"Normal"</dt>
<dd>Probably a misnomer, this one means that it never shows up on the Unread list. You still get notifications if somebody @ mentions you. This might be called "Normal" because this is the state a topic will change to when you haven't read it within the **x** weeks since its creation (this last bit can be quite nifty to save you from information overload when you went on a vacation).</dd>
<dt>"Watching"</dt>
<dd>This topic will show up in the Unread list and will show the number of unread posts in all other lists.</dd>
<dt>"Tracking"</dt>
<dd>Basically "Watching" with the addition that each new post will generate a notification.</dd>
</dl>

**Comment by RaceProUK** [comment]
You got Watching and Tracking the wrong way round :wink:

**Comment by albertdev** [comment]
Already fixed.

**Comment by julianlam** [comment]
Definitely an issue, especially on large forums.

Related to #3128, so please continue discussion there :smile:

**Comment by asdf-tdwtf** [comment]
@julianlam #3128 has been resolved in a completely different way, so can we reopen this ticket to discuss @boomzillawtf's implementation?
