### ISSUE TITLE
Upgrading custom Builds

### ISSUE THREAD

**Issue by simonmcmanus** [NodeBB/NodeBB#4489]
I'm experimenting with running NodeBB on Azure. 

I think we can get it working but it will no doubt require some changes to the core code. 

In your install instructions you suggest cloning the tag from the github repo:

git clone -b v1.0.0 https://github.com/NodeBB/NodeBB.git

Once I have a tag I can apply my changes on top of that but I want to ensure that it's easy to pick up security fixes and features in the future. 

I'm currently thinking I will just clone from the master branch and reset back to the last release (1.0.2 in this case) and then apply my changes on top. When there is a new release I will stash my changes, git pull and then pop my stash (and deal with any conflicts). 

I realise it's not ideal but wanted to confirm I'm not missing something or if anyone else has a better approach. 

Thanks

**Comment by julianlam** [comment]
Hey there, yes -- this is fine. If you have additional changes to core, you can always stash them and pop once you push, or if you're tracking `master`, you can just `git pull --rebase`.

If you're making theme changes, however, it's probably easier to do this on the theme itself, instead of core (altering `public/templates` is not so good since files there are transient)

**Comment by simonmcmanus** [comment]
Thanks @julianlam
