### ISSUE TITLE
Characters can be appended after email within registration/login

### ISSUE THREAD

**Issue by LewisArdern** [NodeBB/NodeBB#4515]
Users email addresses can include invalid characters, such as a null-bytes.

![image](https://cloud.githubusercontent.com/assets/2419690/14478535/94b7dd70-010e-11e6-8c21-fb8e67927363.png)
![image](https://cloud.githubusercontent.com/assets/2419690/14478556/b722ba2e-010e-11e6-9887-3693edb53dfb.png)

Isn't any kind of issue other than it may cause problems in the future, currently there is no email validation process on users, so someone could create multiple accounts by just appending multiple characters.

e.g.

Someone creates the accounts:

test@test.com
test@test.com%
test@test.com%0
test@test.com%00
test@test.com%000

etc.

**Comment by julianlam** [comment]
It is definitely a deficiency, but not a _bug_, per se. We don't have any overly complicated restriction on email addresses, simply because there are a lot of email addresses that seem weird but are perfectly valid.

Sure, we [could just use this monster of a regular expression](http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html), but a more elegant solution is to simply restrict the regex to the simplest set  (that is, the input needs to have a single `@`), and if the email address is entered wrong, then that user just won't get emails, or be able to validate their email.
