### ISSUE TITLE
Expired CSRF token results in "Forbidden" on login attempt

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4593]
![](https://what.thedailywtf.com/uploads/files/1462238247897-upload-34576da4-06ab-46f8-85b6-351a95dc75f4)
![](https://pbs.twimg.com/media/CggH8ByUUAAzsdc.jpg:large)

It should probably re-obtain the CSRF token and silently try again, or at least give a message along the lines of "please refresh the page".

**Comment by BenLubar** [comment]
This can be verified by deleting the session cookie while on the login page and then attempting to log in without navigating away.

**Comment by julianlam** [comment]
Unfortunately, we cannot re-obtain the CSRF token in the background, since that would be opening up a vector to retrieve a CSRF token via API, which is verboten...

I also hate filling out forms and then seeing the "ok, something went sideways, fill this form again", but it just might be the only solution here.
