### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by patatetom** [NodeBB/NodeBB#4746]
hi,
installed on a private network with no access to internet, the browser (chromium for me) struggle to deliver the requested page because  external resources are needed (https://maxcdn.bootstrapcdn.com/bootswatch/latest/cerulean/bootstrap.min.css or https://fonts.googleapis.com/css?family=Roboto:300,400,500,700 for example).
page finally arrived, but after a while.
regards.

**Comment by yamikuronue** [comment]
This dovetails nicely with a wishlist item I've had for a while: moving the bootswatch themes into your own codebase so you can make updates to the CSS for specific NodeBB features. If you brought everything inside your codebase, it'd all be served from the same host and you could do theme-specific CSS fixes easier.

**Comment by pichalite** [comment]
@yamikuronue check this https://github.com/NodeBB/nodebb-theme-persona/pull/291

this should let you make skin specific CSS fixes easily.

**Comment by yamikuronue** [comment]
I mean, yes, but it's still putting the onus on the site admins to fix problems like poor contrast or clashing color choices, and doesn't offer a way to PR altered skins back into the product...

**Comment by pichalite** [comment]
The fixes for problems related to skins will be different based on themes.There are themes other than persona for NodeBB that support skins (vanilla and others). Don't think you can move the bootswatch skins code into core and expect the same CSS fixes to work for all themes. The fix has to be applied to the theme not NodeBB core.

I think PR's will be accepted to persona's repository for fixing these issues. @julianlam @psychobunny  thoughts?

**Comment by julianlam** [comment]
One could theoretically make a plugin to host bootswatch themes, though the reason we don't maintain the theme files in core is simply because we can pull the most up-to-date version from their CDN.

The majority of the theme conflict problems are not due to bootswatch, however, but due to the fact that we do not utilise the proper LESS variables for branding for custom styled elements, because Bootswatch skins are loaded via CSS _after page render_. 

We cannot add bootswatch LESS into the pre-compiled CSS file because each individual user has the ability to pick their own skin, so we would then have to serve a custom minfile for each user (not happening)

Solution is to either:
* remove bootswatch completely
* remove ability for end users to select a skin (and thus move bootswatch into core)
* keep adding workaround hacks to theme LESS (not ideal, but this is what we're doing now)

**Comment by yamikuronue** [comment]
My preference would be ditching bootswatch in favor of maintaining your own skins,  but you'd need to do them on a per-theme basis apparently, as discussed above. What is your current solution for managing the extensive compatibility testing this opens up (themes x skins x views)?

**Comment by julianlam** [comment]
Maintaining skins on a per theme basis is exhaustive and probably disincentvises theme developers from creating themes... keeping bootswatch on server side only would allow the theme variables to be used properly, so we'd see fewer compatibility issues

**Comment by yamikuronue** [comment]
Sure, but don't you already have that problem, given that every skin can be used in every theme now?

**Comment by julianlam** [comment]
Admittedly, yes, and that's actually probably what led @pichalite to not even allow skins in his theme.

So it stands at 3-0 in favour of removing bootswatch completely at this point...

**Comment by pitaj** [comment]
Does anybody *use* bootswatch skins, would be the next thing to find out.

**Comment by psychobunny** [comment]
Yes, they do. Otherwise we would have removed it by now :p

My proposal is that we add a flag to `theme.json` that states that it will be compatible with skins, if not, then the skin selector for user settings will be removed 

Or even better, the option in acp to disable skins outright.

I'm just not in favour of removing a feature that is used even though it's not 100% great

**Comment by pichalite** [comment]
nodebb-theme-material does not support skins... 
my solution... I don't have a section for skin selection in user settings template... simple :smile:

**Comment by psychobunny** [comment]
Haha yeah. The idea is that a new key in theme.json (default: off if not set) is easier than overriding user settings template

**Comment by julianlam** [comment]
Back to the issue at hand, this is due to Persona requiring external resources, which can be avoided via removal of said items in a custom theme.
