### ISSUE TITLE
Put uploaded files in separate directory (fundamental error)

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#4789]
Hi! In the file upload module there is a fundamental error.

Large community is not do on NodeBB, if all of the uploaded files will be stored in one directory.

If many files in one directory, you will have problems with viewing the directory, file system problems. So CMF (eg, XenForo, MediaWiki, IPB, etc.) create a sub-directories for a specific file set.

**Comment by pitaj** [comment]
You're talking, like a different directory for each file type? Category? Topic? 

It's probably better, at the moment, to just use an external service if you're having troubles like this.

**Comment by psychobunny** [comment]
I agree with @pitaj here, use something like the imgur plugin or Amazon S3 plugin on a large forum

**Comment by MegaGM** [comment]
I would suggest to reopen this issue. Since
> use something like the imgur plugin or Amazon S3 plugin on a large forum

is fairly expensive, when it comes to a pretty large forum.

I believe he's talking about filesystem issues that occur when you have a single folder with a large amount of files, let's say 10k or more. Access time to files starts to be slow, sometimes even *supeer slooow*.

Common approach, that is used in most of all CMF, to avoid the issues is to store files in nested folders that are named by chunks of md5 hash of an uploaded file.
Let's say we have two files:
`1.jpg` `cc8e1c658c81484c51ba5df058f40b56` and
`2.png` `cc8e1c5fd7ff783b6671daed21dd1194`

It should be possible to refactor NodeBB without breaking changes to store these files in a way like:
`./uploads/cc8e1c/658c81/484c51/ba5df058f40b56.jpg`
`./uploads/cc8e1c/5fd7ff/783b66/71daed21dd1194.png`

**Comment by KitsuneSolar** [comment]
@MegaGM yes!
@psychobunny on the big forum it is very bad to use a third-party plug-ins. For example, I wanted to create a large community and upload files (zip / rar ...). None of the plug-in is not suitable for files.

**Amazon S3 plugin:**

> Currently all uploads are stored in S3 keyed by a UUID and file extension, as such, if a user uploads multiple avatars, all versions will still exist in S3. This is a known issue and may require some sort of cron job to scan for old uploads that are no longer referenced in order for those objects to be deleted from S3.
