### ISSUE TITLE
Feature request: merge topics

### ISSUE THREAD

**Issue by huegelc** [NodeBB/NodeBB#4804]
Hi,

one of the most important moderation feature is the ability to merge topics. Are there any plans to introduce this feature?

**Comment by huegelc** [comment]
Any news on this?

**Comment by pitaj** [comment]
It's a good idea. I think its' been suggested before. A good idea to implement for the next major version.

**Comment by pauljherring** [comment]
> Do you just insert posts from topic A to the end of topic B or do you insert them while respecting timestamps?

What happens when you move an individual post? By extension, what would happen if all posts from A were individually moved over to B?

Personally I'd offer both as options since either could make sense depending on circumstance

> In either case I don't think the new topic will make sense.

 - This new thread A is simply a continuation of that old topic B - merge them. - stick them on the end (though preserve timestamps would have much the same effect)
 - These two threads A and B started around the same time - they're talking about the same thing - merge them - preserve timestamps.

Though given the parenthetical on the first, thinking about it, I can't confect an example where 'stick on the end' would make sense where you wouldn't preserve timestamps.

So I'd insert while preserving timestamps (which is an extrapolation of moving a single post as noted above) if not offering an option.

**Comment by barisusakli** [comment]
>What happens when you move an individual post?
It gets inserted using the timestamp of the post.

**Comment by pauljherring** [comment]
Sorry Bariş, that was intended to be a rhetorical question...

**Comment by Deph0** [comment]
Could we please have this feature? It's a really essential thing to have in a forum software.

**Comment by pitaj** [comment]
What should be done about the main post of the topic you are merging in? Should it just be copied over directly as if it were a normal post, or should the original title be added to the post's body?

**Comment by Deph0** [comment]
I would prefer copied over, the original title isn't of importance in my eyes

**Comment by julianlam** [comment]
As I understand it, it would depend on whether topic A or B is older, to determine which post to act as OP (and therefore preserve title).

If you are merging *B* into *A* but B is the older topic, then it should really be *A* merging into *B*, behind the scenes.

**Comment by michaelpfaff** [comment]
Very much agree this is a needed feature. Especially, since I just forked a topic and then realized it was the wrong topic but couldn't merge it back into the old topic. 👍

**Comment by nsuchy** [comment]
+1

**Comment by sp-Carlos-Escura** [comment]
+1

**Comment by dangerusslee** [comment]
My users are asking for this feature as well.  What is the hold up to getting it done?   Are we still collecting comments, or is it just the time to sit down and do it?

**Comment by jimmykane** [comment]
Still?

**Comment by jimmykane** [comment]
Woop woop!

**Comment by TobiTenno** [comment]
so is this a thing now?

**Comment by julianlam** [comment]
😎 Yes.

**Comment by TobiTenno** [comment]
will it be up in 1.7.1/2?
