### ISSUE TITLE
jQuery cannot be required with requirejs

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#4833]
NodeBB version: 1.0.3; git hash: 4c627843584cba2095defb4b963e7f2c2ed1a00f

Paste the following code into the console, which should log the jQuery function, but instead will log the error.
```js
requirejs(['jquery'], function(jq) {
  !!jq ? console.log(jq) : console.error('jQuery can\'t be required');
});
```

I expected to be able to `requirejs` jQuery, but instead I get an error when I attempt to include a jQuery plugin via `require` that `jQuery.fn` is undefined.

**Comment by julianlam** [comment]
We're using jQuery as a global, so $ is set, no?

**Comment by pitaj** [comment]
Yes, but many plugins won't fall back on that if requirejs is being used.
They'll require jQuery instead. I could manually remove the require stuff
and just force the plugin to act globally, but it uses momentjs, which
mandates requirejs.

**Comment by julianlam** [comment]
The flip side of this issue is that if I do allow jQuery to be required, we have a lot of dependencies and libraries that _expect_ jQuery to be a global, and thus break, so there's a bit of a catch-22 there.

There is still the issue where libraries added in plugins via the `scripts` property cause the `mismatched anonymous define() module` error since it detects require.js support, but has no context. The current workaround for this is to use the `modules` property instead:

``` json
{
  ...
  "modules": {
    "mylib": "static/lib/somerjslib.js"
  }
  ...
}
```

At which point `require(['mylib']);` will work fine.

We also have #3543, which is the meta-issue for this, so I'll close this for now.
