### ISSUE TITLE
Deleted posts are still visible to everyone

### ISSUE THREAD

**Issue by Pascal666** [NodeBB/NodeBB#4887]
NodeBB v1.1.0
git hash 296dc77c7bb2bbf92f711089d77e4f32f729951f

Delete a post.  Logout.  Visit the category.  See the post still there, just grayed out.

**Comment by pichalite** [comment]
That's intentional. Not an issue.

**Comment by Pascal666** [comment]
I Googled this issue before opening the bug.  The below comments all indicate that only moderators should be able to see deleted posts.

https://community.nodebb.org/topic/472/deleted-posts-removal/4
https://community.nodebb.org/post/38134
https://github.com/NodeBB/NodeBB/issues/1394#issuecomment-40719206

**Comment by jarey** [comment]
The deleted posts are visible without content for everyone because of pagination issues. It was recently discussed again on the community, but for now i think as @pichalite said the behaviour you are experiencing is intentional.

Maybe its time to re-talk about the behaviour (doesn't know if finally they decided to implement pitaj suggestion): https://community.nodebb.org/topic/8993/why-do-i-see-the-deleted-topic/30

**Comment by julianlam** [comment]
@Pascal666 Admins, moderators, and _the post author_ can see the deleted post content. All other users see a placeholder message.

As @jarey says, this is intention due to pagination concerns
