### ISSUE TITLE
infinite scroll pages don't work

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4999]
go to /tags
try to scroll down
results in
`TypeError: elem.getClientRects is not a function` on chrome and firefox

could be another jquery 3.0 update bug

**Comment by barisusakli** [comment]
Stacktrace points to 
```
// Support: IE <=11 only
// Running getBoundingClientRect on a
// disconnected node in IE throws an error
if ( !elem.getClientRects().length ) {
    return { top: 0, left: 0 };
}
```

In the jquery .offset() method.

**Comment by pichalite** [comment]
@barisusakli https://github.com/jquery/jquery-migrate this can help in identifying the cause of the issues related to jquery 3. jquery-migrate... provides features removed from jquery 3 and throws warnings instead of errors. running `jQuery.migrateWarnings` in the browser console shows what needs to be fixed for jquery 3.

**Comment by barisusakli** [comment]
https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method
