### ISSUE TITLE
Redirect while posting with pagination bug

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5004]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database mongo
* Exact steps to cause this issue
    1. Use pagination and go chrome on mobile
    2. Open a thread with several pages
    3. Go to a page on the middle and post a reply
* What you expected
  - that is sends to my post on last page
* What happened instead
    * it doenst load, instead it tries to load this kind  url but never load

https://exo.do/compose?p=%2Ftopic%2F24775%2Fflood-vol-250-flood-perros-y-cervezas-18%2F621&page=32

tested it and also fails on community,nodebb

Thank you!

**Comment by barisusakli** [comment]
Is this still happening on https://community.nodebb.org/?

**Comment by exomarty** [comment]
Yes @barisusakli

**Comment by barisusakli** [comment]
@exomarty can you post a link to the topic that you reproduced on  https://community.nodebb.org/?

**Comment by barisusakli** [comment]
1. Click reply
2. Composer opens and address bar changes to `/compose?p=/topic/1/replying/20`
3. Submit reply
4. `event:new_post` is emitted to the client, `window.location.pathname` is still `/compose`
5. clientside code tries to load the page the post is on, but since `window.location.pathname` is `/compose` it tries to go to `/compose?p=...&page=x`
6. nodebb-plugin-composer-default calls `window.history.back()` in the socket.emit callback

So this is essentially happening because things are running out of order. What should happen is once you submit the url should change back to `/topic/1/replying/20` and the navigation should happen. But there is no way to do this because `history.back()` just queues a command and `event:new_post` can happen before that.

**Comment by exomarty** [comment]
Any topic with multipage

https://community.nodebb.org/topic/104/hmmm-testing/85

**Comment by exomarty** [comment]
It gets stuck loading the page after the post 
[Imgur](http://i.imgur.com/P682XgW.jpg)
