### ISSUE TITLE
NodeBB cannot connect to redis with password

### ISSUE THREAD

**Issue by setpixel** [NodeBB/NodeBB#5069]
I've set up nodebb with redis and no password - works fine.

With a password, I'm getting the error 
28/9 16:36 [23535] - error: ReplyError: Ready check failed: NOAUTH Authentication required.

config.json is configured correctly with the correct password.

It appears the password isn't being used to connect to the redis server.

**Comment by setpixel** [comment]
TO FIX: insert on /src/database/redis/redis.js line 77:

		if (nconf.get('redis:password')) {
			options.password = nconf.get('redis:password');
		}

**Comment by frissdiegurke** [comment]
```
nodebb@1.1.2
├─┬ nodebb-plugin-dbsearch@1.0.2
│ └─┬ redisearch@0.0.6
│   └── redis@0.12.1 
├── redis@2.6.2 
└─┬ socket.io-redis@1.1.1
  └── redis@2.4.2 
```

I've been able to track this issue down to the dependency jump from `socket.io-redis@1.0.0` to `socket.io-redis@1.1.0`.

These deps are working fine:
```
nodebb@1.1.2
├─┬ nodebb-plugin-dbsearch@1.0.2
│ └─┬ redisearch@0.0.6
│   └── redis@0.12.1 
├── redis@2.6.2 
└─┬ socket.io-redis@1.0.0
  └── redis@2.3.0 
```

Since I'm not familiar with those packages responsibilities, I guess it's best if you guys forward an appropriate bug report to `socket.io-redis` and make the dependency version range more specific for now.
