### ISSUE TITLE
Feature Request: Flag metrics

### ISSUE THREAD

**Issue by yamikuronue** [NodeBB/NodeBB#5085]
As a moderator, I want to be able to see flag history and statistics over time: how many flags we're handling on a day, who is doing all the flagging, what kinds of things people flag for, who is being flagged. Right now if one of us dismisses a flag, it appears to vanish forever, and we can't get information about it later. If we don't dismiss the flag, it sits on the flag screen forever, as if it were fresh and nobody had handled it yet.

**Comment by pauljherring** [comment]
Is this being addressed? ISTR some noise about it previously but not a lot since:

![screenshot from 2016-10-05 18-00-15](https://cloud.githubusercontent.com/assets/3939886/19123213/aa5f7a10-8b25-11e6-81db-9bf9702ce144.png)

![screenshot from 2016-10-05 18-01-18](https://cloud.githubusercontent.com/assets/3939886/19123447/95fec7aa-8b26-11e6-841f-4ec44fd1fc74.png)

[Ignore the date stuff in the square brackets - that's personal CSS]

**Comment by julianlam** [comment]
Yes, that's a "first step" towards building out a more robust reporting/flagging/warning solution.

... though I will admit I'd prefer to see actual text instead of language placeholders 😒

**Comment by yamikuronue** [comment]
Language placeholders are present in EN_US and Pirate, as far as we can tell by comparing notes across mods

**Comment by julianlam** [comment]
Related flagging issues:

* [ ] #5094 
* [ ] #4586

**Comment by julianlam** [comment]
Closed in favour of centralised tracking in #5232
