### ISSUE TITLE
if chat is restricted don't allow others to add user to room

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5115]
If `Only allow chat messages from users I follow` is enabled, don't allow users that we are not following to add us to chat rooms.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/139360ce1895726366aaa4e3f6d6c236f526ca7b

**Comment by glazkoman** [comment]
Sent from my T-Mobile 4G LTE Device










. $y uh vz ml 0. Nppmg
-------- Original message --------From: Barış Soner Uşaklı <notifications@github.com> Date: 10/14/16  2:22 AM  (GMT-05:00) To: NodeBB/NodeBB <NodeBB@noreply.github.com> Subject: Re: [NodeBB/NodeBB] if chat is restricted don't allow others to add
  user to room (#5115) 
Closed #5115.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NodeBB/NodeBB","title":"NodeBB/NodeBB","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NodeBB/NodeBB"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #5115."}],"action":{"name":"View Issue","url":"https://github.com/NodeBB/NodeBB/issues/5115#event-823536961"}}}
