### ISSUE TITLE
Inviting users to the administrators group

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5175]
Doesn't make you an admin :trollface:

**Comment by barisusakli** [comment]
Due to [this](https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/helpers.js#L156-L158) code even if you invite someone to the administrators group, they will not see the `Accept Invite` button.

Removing that code shows the proper button and accepting the invitation makes the user an admin.

**Comment by julianlam** [comment]
I have no preference on either keeping the button hidden and not allow admins to be added via group invitation, or exposing it, _and_ also allowing admins to be assigned via ACP -> Manage -> Users
