### ISSUE TITLE
Not possible to set "Access-Control-Allow-Origin" header.

### ISSUE THREAD

**Issue by rckrdstrgrd** [NodeBB/NodeBB#5230]
* NodeBB version: 1.3.0, git hash: 4db89407c4dbe9850d925bd9529a1d106419531f

When configuring the Access-Control-Allow-Origin in "Admin panel -> Settings -> Advanced" to a domain the browser blocks XHR requests. 

It seems that the header value, including the protocol, is URI encoded and this is not supported by browsers, hence the XHR request is blocked, see: [headers.js#L29](https://github.com/NodeBB/NodeBB/blob/5cd2da43095490814d94aa0824021a1cbc97eea3/src/middleware/headers.js#L29)

Repo steps: 
Set the "Access-Control-Allow-Origin" http://localhost:3000. Make a XHR request from http://localhost:3000 .

Expected result: 
Access-Control-Allow-Origin is set to: http://localhost:3000

Actual result: 
Access-Control-Allow-Origin is set to: http%3A%2F%2localhost%3A3000 .

A solution could be to use `encodeURI()` to keep the protocol in a format that the browser accepts.

**Comment by julianlam** [comment]
Perhaps this isn't properly fixed, can you confirm @rckrdstrgrd ?

![image](https://cloud.githubusercontent.com/assets/923011/20571187/6cc436da-b174-11e6-9dc5-bd7bd2c5cdd5.png)

The ` ` is still escaped to `%20` because we're encoding the entire value, including the stuff NodeBB appends, which is stuff like `ALLOW-FROM` `DENY` etc...
