### ISSUE TITLE
Should topic navigator buttons navigate to the next post in index, or pgUp/pgDn (keep current behaviour)?

### ISSUE THREAD

**Issue by dede5** [NodeBB/NodeBB#5321]
Please make the down and up icons seen here http://i.imgur.com/uEKEaRY.jpg move to up and down by post instead of pageup / page down.

**Comment by pitaj** [comment]
Why?

**Comment by dede5** [comment]
Page up and down can be down by keyboard already, but navigation from one post to next cannot.

**Comment by pitaj** [comment]
Page up and down cannot be done on a mobile device.

**Comment by julianlam** [comment]
I'm generally not a fan of changing established behaviour, but in this case, let's talk it through...

There is no page up/page down on mobile devices, yes... but as an end user, would you prefer hitting a button to scroll a page height's worth of content, or would you just flick your thumb and stop when the page has scrolled enough? I'd argue the latter is easier (though am willing to be proven wrong).

However, navigating by post could be pointless if the posts themselves are short (_especially_ the case because then the amount of page scrolled is dependent on post height), **but** if they're long, and you're tired of reading a long rant, hitting a single button to go directly to the next post is actually quite a nice feature.

**Comment by dede5** [comment]
@pitaj @julianlam I see. I am used to seeing long replies so that skewed my perspective a lot. I wonder if there is a way to combine both features? There is that shortcuts plugin that allows jumping from reply to reply so this isn't urgent.

**Comment by julianlam** [comment]
I'll also put it out there that I _really wish_ Reddit had a "next post" button to go to the next top level reply. Some comment chains are really 😖

**Comment by dede5** [comment]
@julianlam They do have that collapse comment feature. that sorta helps

http://i.imgur.com/W4tUcEr.jpg

**Comment by psychobunny** [comment]
I think the functionality from the shortcuts plugin (although I believe it's up/down or w/s instead of pgUp/down) is good enough if you want that, but happy to re-open if any objections.

**Comment by alfazaz** [comment]
@psychobunny Sorry for the necro but... many of my users ask a navigator by posts and not by pages... Like me, they don't use single arrows to scroll (but mouse or thumb...) and they need to pass quickly a long post which could be easier with single arrows of navigator. @julianlam exposed already arguments for this.

It could be an option to choose in ACP (navigation by page or by post).

**Comment by julianlam** [comment]
I see this was unresolved. To be honest I am still in favour of changing the behaviour to navigate by post instead of by page.

The only downside is that clicking said button would get tedious if you have many short posts, but we can tweak if necessary.

**Comment by alfazaz** [comment]
It can be an admin (or user) choice.

I think users are scrolling with mouse/thumb the major time. In the same time, there is no way to scroll post by post (and the number in navigator is about posts and not pages...).

**Comment by julianlam** [comment]
#8553
