### ISSUE TITLE
post navigation enhancement - post navigation inaccurate

### ISSUE THREAD

**Issue by dede5** [NodeBB/NodeBB#5322]
I notice that links to a specific post will not always load properly as it does on say phpbb. Below is a sample link.

[link removed]

It may load close but not directly. Long posts seem to exacerbate this problem.

**Comment by julianlam** [comment]
Link contains spam. Please re-submit properly.

**Comment by dede5** [comment]
Let's use this link as an example https://community.nodebb.org/post/31542

It should go to here http://i.imgur.com/sbK56H0.jpg

But, it goes http://i.imgur.com/7qv237c.jpg (it's close but not quite there).

The problem worsens if the posts/replies are very long.

**Comment by pitaj** [comment]
I don't see where the problem is based on those screenshots.

**Comment by dede5** [comment]
@pitaj - http://i.imgur.com/V1BBP5w.jpg The post outlined in red normally will sit at the top of the screen. The problem is more pronounced when the posts are longer, but the idea is to have the target post at the top so there's no guessing involved.

**Comment by julianlam** [comment]
Looks intentional. Longer posts whose height is larger than viewport height will position the post to be at the top of the page. Smaller posts will position themselves at the midpoint of the screen (specifically, midpoint of viewport minus half of post element height), so the entire post itself is visible and centred.
