### ISSUE TITLE
Error: test_database is not defined when doing a pull request

### ISSUE THREAD

**Issue by DomLennonZA** [NodeBB/NodeBB#5358]
I am attempting to do a pull request but get `Error: test_database is not defined`. Not sure if this a user error on my part (probably), but not sure how I can resolve this?

Request: https://github.com/NodeBB/NodeBB/pull/5356
Job: https://travis-ci.org/NodeBB/NodeBB/builds/190921933

**Comment by julianlam** [comment]
Do you get the same errors when you run `mocha test/database`?

I have a sneaking suspicion it is because you added this at the top of the database file:

`var meta = require('../meta');`

Meta requires database, and if database requires meta, then you get a circular dependency and one file loses and gets an empty object.

Try moving that `require` statement into the method it is used in?

**Comment by DomLennonZA** [comment]
Ah, I had added it to the method. Forgot to remove it from the top :/
