### ISSUE TITLE
Integrate netdata dashboard (feature request)

### ISSUE THREAD

**Issue by Radiergummi** [NodeBB/NodeBB#5395]
I recently stumbled over [netdata](https://github.com/firehol/netdata), which is essentially a dashboard to monitor one or more servers in realtime with minimum performance impact. In contrary to many other similar solutions, it configures most of its metric sources by itself, allows for custom metric plugins using NodeJS for example and may be integrated into existing web apps pretty painlessly.  
That's when I started to think about whether netdata could be integrated into the NodeBB admin panel. I know this will most likely trigger "better off as a plugin request!" responses 😄 , but I think server monitoring would be better off as part of the NodeBB core.  
That way, we'd be able to have realtime performance monitoring not only for NodeBB, but Redis, Mongo, nginx/apache, disk IO, network and memory for free.

Any opinion on this?

![](https://cloud.githubusercontent.com/assets/2662304/14093195/c882bbf4-f554-11e5-8863-1788d643d2c0.gif)

**Comment by julianlam** [comment]
No, this cannot be core, because it is just one of many alternatives... we want to keep core minimal and that means not including these types of "extra" features, even if they're helpful.

So the best bet is, yes, a plugin -- so server admins can pick and choose. Maybe you guys will want netdata, someone else may want New Relic, etc.
