### ISSUE TITLE
Translation issue in ACP -> Manage -> Flags

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#5469]
latest master branch

![image](https://cloud.githubusercontent.com/assets/10014774/23236744/4d072efa-f90f-11e6-9d05-3e33be229a74.png)

This is when you expand the flag in ACP -> Manage -> Flags page.

**Comment by pitaj** [comment]
This is due to the translator automatically recalling any HTML entities in arguments to a translation token.

Possible fixes: 
- Change behavior of translator to not escape arguments
- Change this particular translation key. Instead of taking this HTML as an argument and passing it through, it would have the link HTML as part of the translation, and just get passed the link URL and other parameters.
