### ISSUE TITLE
Translation issue in ACP

### ISSUE THREAD

**Issue by Alisummer** [NodeBB/NodeBB#5481]
Latest master branch
[Imgur](http://i.imgur.com/qpNAcA0.jpg)
[Imgur](http://i.imgur.com/eal46Pk.jpg)

**Comment by pitaj** [comment]
Confirmed on latest master with any language besides `en-GB`.

**Comment by Alisummer** [comment]
[Imgur](http://i.imgur.com/zwCBL5b.jpg)
There is same issue

**Comment by RoiEXLab** [comment]
@barisusakli I believe this issue should be added to the 1.4.5 Milestone as well

**Comment by julianlam** [comment]
@pitaj, would appreciate your thoughts on this... currently Transifex is tracking the language string found in `develop`. I push these source files manually.

In this particular case, the ACP flags page is missing translations, because those source strings have been removed in `master` and hence removed from tx.

Possible solutions:
* Re-introduce those old strings and mark them as deprecated (but without comments in json, this is hard)
* Change the templates in master to refer to the new strings (if they're more or less comparable)

Latter works, I think...

**Comment by pitaj** [comment]
If you want comments in json, you could do something like 

```
{
  "Key": "value",
  "___": "comment text"
}
```

**Comment by julianlam** [comment]
I'm afraid transifex would still propagate that up to their service 😆

**Comment by pitaj** [comment]
Yes you're probably right. Unless there's a way to exclude keys matching certain patterns. But that's getting messy.

**Comment by julianlam** [comment]
Pending v1.5.0 launch this will no longer be an issue.
