### ISSUE TITLE
Integrate zxcvbn into registration page to gauge password strength

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5521]
After reading Atwood's article on password strength, I figure we should integrate this into our registration page as a crude measure of password strength.

It may be prudent to actually enforce password strength as well... deny registration to those registrants with weak passwords.

https://github.com/dropbox/zxcvbn

Bonus points if you can integrate a persistent notification on login if an administrator/global mod/moderator's password is not good enough 😉

**Comment by RoiEXLab** [comment]
zxcvbn is a great tool for password security!
I think a client side check would be totally sufficient, because what is the benefit in having an insecure password?
Requiring a strength of 1 or 2 (I think the scale goes from 0 to 3) would be totally fine.
We probably want a strength meter too. HTML5 provides a meter tag, which should be added to several templates in order to visually support this feature!
