### ISSUE TITLE
Issue with profile pages and hidden categories

### ISSUE THREAD

**Issue by yamikuronue** [NodeBB/NodeBB#5570]
I have been posting to a private area in our forum, and users are reporting incorrect messaging when they try to view my recent posts but do not have permission to see the private area. 

I am only a moderator, so I don't have access to the git hash of our version. 

The user reports browsing to my profile, clicking on recent posts, and seeing the following screenshot:

![image](https://cloud.githubusercontent.com/assets/1219256/24703402/160ce6e6-19d1-11e7-9b0a-6207ede54d12.png)

I would have expected the posts on page 2 to have been shown on page 1. 

A user with pagination turned off reported the following screenshot of the same view. Note the incorrect messaging followed by posts:
![image](https://cloud.githubusercontent.com/assets/1219256/24703423/2e73d168-19d1-11e7-9863-6d0ac7b3c3a6.png)

(the first user reports seeing the "Bushido Mafia" posts on page 2 by themselves).

**Comment by pitaj** [comment]
Yes, this is unfortunately due to how we handle deleted or hidden posts. We filter them out without fetching more if the ending result is below the pagination length or in your case even zero for some visitors. This is also why we show *this post has been deleted* instead of just hiding the post altogether in the list.

**Comment by yamikuronue** [comment]
Shouldn't you do your filtering server-side?

**Comment by barisusakli** [comment]
It is done server side, fixing this requires some structural changes though.

Right now we display this page by just using a single sorted set, which is `uid:<uid>:posts` which contains all the post ids for that user from all categories. So when a second user tries to view this page and doesn't have access to some categories these gaps occur.

The fix is to first get the category ids the user can view and then only grab the users pids from those categories. This will require adding new sorted sets for each user for each category ie `cid:<cid>:uid:<uid>:pids` and then doing a `db.getSortedSetRevRange(['cid:1:uid:1:pids','cid:2:uid:1:pids'], 0, 19);` assuming the current user can only see cid 1 and 2.

If we were using mongo only we could do.

```
var cidsICanSee = [1,2,3];
db.posts.find({ uid: 1, cid: { $in: cidsICanSee }}).sort({timestamp: -1}).skip(0).limit(20);
```
