### ISSUE TITLE
Handling of obsolete plugins

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5620]
As you all know, every plugin for nodebb needs to specify which nodebb versions it's compatible with.
My file-extension plugin, which is (fortunately) obsolete now, changed it's compatibility tag in the latest version.
I just upgraded nodebb to 1.4.6 and I noticed, that nodebb just stays with the "latest compatible" version (the version that hadn't a strict compat tag).
My suggestion would be to list "incompatible plugins" e.g. plugins which have a newer incompatible version as "outdated". If the author updated the npm description, the forum owner can read this notice and uninstall it then.

What would be even better: If plugin developers had a way to mark a plugin as obsolete in the package.json file. This solution completely avoids false-positives...

**Comment by pitaj** [comment]
In my opinion, this feature wouldn't benefit much at all, especially since it seems like it would only affect a very small amount of plugins. A better solution would be for NodeBB to be more semver-compliant, and just bump the minor version field if we push a plugin to obsolescence, since this implies a new feature or large fix.

**Comment by julianlam** [comment]
Agreed, whenever we release a new minor version, a lot of custom plugins don't make the transition because their compatibility string no longer matches the current version. That's intentional, so the author has to go in and make sure that their plugin is still compatible.
