### ISSUE TITLE
minification doesn't work on uglifyjs 3.x+ 

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5655]

**Comment by julianlam** [comment]
Perhaps it's time to consider alternative minifiers... https://github.com/Rich-Harris/butternut ?

**Comment by pichalite** [comment]
You want to switch and use an alpha version?

**Comment by julianlam** [comment]
Not necessarily 😛  Scared?

**Comment by pitaj** [comment]
Looks like it no longer will allow for passing file paths, but requires that file contents are passed instead. It looks like the source map issue referenced in meta/minifier has been closed. I think after #5664 is merged in it should be easier to implement the change since all of the minification will be in one place.

However, I a lot of outstanding bugs so we should probably wait for things to stabilize.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/5703
