### ISSUE TITLE
New upgrade system needs extra checks?

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5802]
The idea of the new upgrade system is that we don't have to worry about checking out minor versions per upgrade. Currently this script requires that behaviour:

`dismiss_flags_from_deleted_topics.js`

You need to go to 1.1.0 first, run this, and then move on. There is no documentation on that so it could be a pain point.

RFC, because the obvious solution is actually counterproductive :P

**Comment by julianlam** [comment]
Yeah, this is unfortunately something I don't have a solution for, since our code shifts around from version to version (deprecations, etc.)...

Theoretically we could (over time) find some "path" of upgrading that we could save in NodeBB core, then upgrade script would check out the hashes and upgrade, but that's... scary 😬

**Comment by psychobunny** [comment]
Yeah that might be it, a JSON file with an array of stop points during the upgrade....

**Comment by Radiergummi** [comment]
If I may ask, why not build something similar to Laravels migrations? I think it's pretty elegant...
