### ISSUE TITLE
Feature Request: Allow explicitly "not watching" a topic in an ignored category

### ISSUE THREAD

**Issue by TwelveBaud** [NodeBB/NodeBB#5852]
- **NodeBB version:** 1.5.2
- **NodeBB git hash:** f59f48c6e1f8262ddc66f4ad09ed19461156be9e
- **Database type:** mongo
- **Database version:** unknown

In Discourse, when a category is watched (for notifications) or ignored, all topics created therein are also watched or ignored. You can visit an individual topic and change its visibility rule manually, in which case it follows the new rule instead of the category rule. There was definitely some discoursistency when topics were moved from category to category or when a user changes visibility at the category level, but in general new topics inherited visibility from their parent at time of creation and could be individually changed later.

In NodeBB, categories can be watched (for unread) or ignored, and threads can be watched (for notifications), not watched (follow category rule), or ignored. Category and thread visibility are independent from each other, and the system (in general) feels sane. However, there's one small problem:

If a topic is in an ignored category, the three topic visibility options effectively become watch (for notifications), ignore, ignore. There's no way to configure it to show up in the unread list short of manually clicking "Mark as unread". I *could* watch the topic, but that starts adding entries to my notifications feed, which I feel should be limited to items personally pertaining to me (mentions, for example). It *could* be argued that the topic is categorized incorrectly, that if I want it to show up in unread it shouldn't be in a category I ignore, but I can't recategorize threads as an end user, nor would I want to since it's on-topic for that category. It *could* be argued that I should unignore that category, but most everything in it is stuff I don't care about -- aside from the one or two threads I'm trying to track -- and would blow up my unread box like crazy.

I think the best solution is to extend category visibilities to include watch-for-notifications, default a topic's visibility to null (signalling to use category visibility), and allow a manually-set topic visibility setting to override category visibility entirely. This would provide similar intended behavior to Discourse, without suffering from Discourse's unintended discoursistency.

**Comment by julianlam** [comment]
https://what.thedailywtf.com/post/1218269

(wonder if that will expand...)

> We can toss blame around but the reason this is so is because you weren't able to unwatch categories at all, at first.

**Comment by barisusakli** [comment]
I was planning on adding `watching` `not watching` and `ignoring` to category settings as per https://github.com/NodeBB/NodeBB/issues/5172 but even that won't resolve this. The request here is to be able to ignore a category and then change a setting in the topic visibility so that it shows on /unread but replies don't generate a notification. I don't think this is possible without a 4th option in the topic dropdown. 

Watching - show in /unread, notify me of new replies
Tracking - show in /unread, don't notify of new replies
Not watching - follow category setting 
Ignore - dont show in /unread dont notify of new replies

You seem to be asking for tracking. Which is pretty much what Discourse does.

![image](https://user-images.githubusercontent.com/2583394/33744106-9d8987aa-db7d-11e7-92b2-aeb883478865.png)
