### ISSUE TITLE
Certificate issues with plugins

### ISSUE THREAD

**Issue by guateandrew** [NodeBB/NodeBB#5933]
- NodeBB version:1.5.3 
- Database type:redis
 
	1. I am running the forum behind a NGINX https proxy in a subdomain on my website. /community --> is routed to :4567/community
	2. This works find on localhost but when deployed I get the following error on startup

`Error parsing plugins : Hostname/IP doesn't match certificate's altnames: "Host: packages.nodebb.org. is not in the cert's altnames: DNS:[domain].com, DNS:www.[domain].com"`

Is there a way to configure nodebb to avoid this.

**Comment by RoiEXLab** [comment]
I'm really not an expert, but there could be a couple of different reasons for this.
Your Certificate works fine, just as expected, but you probably have something not configured correctly with nginx if it works for you locally.
If the config.json file contains the correct domain, it's very likely an nginx problem.
Technically something tries to pretend it's `packages.nodebb.org`, which of course isn't allowed, because well it actually isn't.
Doing a `grep "packages\.nodebb\.org"` on your installation directory might have some use, posting your nginx config as well.

**Comment by julianlam** [comment]
The certificate for packages.nodebb.org work on both www and non-www subdomains, so I'm not quite sure what to make of this, sorry about that!
