### ISSUE TITLE
Don't allow posting links until reputation level X

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/NodeBB#6021]
- **NodeBB version:** 1.6.0
- **NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e
- **Database type:** mongo + redis
- **Database version:** 3.4.9 + 3.2.4

In our forums we have a recurring problem with people trying to post semi-legitimate posts containing self-promoting spam links. We would love to see an option to use Reputation system to cut this short automatically. Ability to configure NodeBB to reject post if it contains a link when user reputation is lower than X would be great.

Thanks!

**Comment by tomber42** [comment]
Same as #5884?

**Comment by attis** [comment]
Not entirely since the other issue is about links in profile and this one is about posts in general. So these are complementary I would say. I would welcome #5884 as well :)

Given the recent changes in NodeBB (being able to edit posts before releasing them from Post Queue) I would change my original request here. Instead of preventing users with low reputation from posting URLs altogether I would say that:

IF post contains an URL
AND user’s reputation is below certain threshold 
THEN place the post in Post Queue.

This would be more user friendly in rare cases when the URL in post is really needed and warranted, at the same time discouraging spammers. Now can get past Post Queue policy by making one legitimate post (not that hard) and later they can spam all they want and moderation has to catch them manually.

**Comment by antoine-pous** [comment]
In fact this kind of feature is not reliable. When you enable it, users go spam the required amount of messages and then post their links.

To avoid it i have enabled the manual validation for all users posts who have less than 15 reputations points. Now i haven't anymore problems, sometimes users try to bypass the rules but globally we have less 2 spam account each week instead of 50 before.

**Comment by mfalkvidd** [comment]
We have problems with users posting innocent-looking posts and then coming back several days later replace the post contents with spam(-links). Not sure how common that behavior is, but it would be nice if this feature could take editing into consideration.

**Comment by djensen47** [comment]
Let's do this one. It won't solve _everything_ but it will help. Most of the spammers I get are one and done and I think there are probably other moderate traffic forums that would be the same.

cc: @barisusakli @julianlam

**Comment by julianlam** [comment]
Sounds like a worthwhile addition to the new user restrictions.
