### ISSUE TITLE
Floating button overlaps textarea when replying on Mobile

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6112]
- **NodeBB version:**  1.7.0
- **NodeBB git hash:** 97ac4a2e8c800e61af303eb989d1e2709fe92688

- **Exact steps to cause this issue:**
Start typing a reply on a mobile phone. The problem is especially prominent on lower resolutions:

![](https://forums.opera.com/assets/uploads/files/1511467629549-screenshot_20171123-161056.png)

- **What you expected:**

The (+) button should not get in the way of the text input.

- **What happened instead:**

Button floats and covers part of the text.

**Comment by julianlam** [comment]
Thanks for reporting, we're looking into alternate ways to minimize composer. This issue is also present with chat modal on mobile.

**Comment by julianlam** [comment]
For context's sake, I do want to point out the following:

* This was not an issue on older versions of NodeBB because we made the conscious decision to hide the toolbar in Persona and Vanilla if you were on mobile, reason being mobile is _different enough_ in that you wouldn't really run into a situation where you'd want to minimize a chat or a composer to check out something else, and then continue composing... that is, a mobile user tends to single-task rather than multi-task.
* We received some comments that suggested otherwise, so we re-exposed the taskbar.
* Now this issue suggests this may have been a mistake :trollface: 

So at this point, a proper UX review needs to happen with respect to the taskbar and its use on mobile platforms.

**Comment by LindaBadurina** [comment]
Thanks for bringing the issue regarding the button overlapping the text to our attention. 

Another potential issue with this is that the (+) button could potentially be misinterpreted as a “submit draft” button. Especially when taking its placement into consideration. 

A new design that will eliminate both of these issues is in the works.

**Comment by aStonedPenguin** [comment]
I had some users complain about the button a couple days ago. It should be hidden on mobile imo.

**Comment by julianlam** [comment]
> It should be hidden on mobile imo.

Right? Except some users think otherwise, and I'd like to see whether Linda can come up with a design that can accommodate both camps 😄

**Comment by mohammadhassan99** [comment]
@attis Yes I think this is a problem 👌 
And also when you chat with someone, sometimes the floating picture bothers and can't see what you wrote 😄
Specially when your language is right-to-left aligned.

**Comment by julianlam** [comment]
Regressed here https://github.com/NodeBB/nodebb-theme-persona/commit/d816b1659a98861693a17eb5c765f1b126a62b85

Apparently I was too ignorant of the three-line warning and clobbered it 💯

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/f48c6b5e26cf47b4c7c61753883c5906bffac2c9
