### ISSUE TITLE
NodeBB uses Environment Variable PORT. 

### ISSUE THREAD

**Issue by MozJon** [NodeBB/NodeBB#6188]
This should be more application specific such as NODEBB_PORT. In my use case PORT is required by Mesos and then NODEBB uses that port and listens on the wrong port that my port mapping takes care of.
Best practice would be to make your environment variables application specific and much less generic.

**Comment by MozJon** [comment]
Just an FYI I worked around the issue but I still suggest that something as generic as PORT be replaced by something application specific.

**Comment by julianlam** [comment]
Thanks for the comments @MozJon -- we use `PORT` because it is standard across many apps, and the base install assumes you're not executing the app within another environment that passes environment variables in.

Perhaps there's a config in Mesos that can limit the env vars passed on to NodeBB? It's definitely not a common config, and a number of existing cloud providers already pass `PORT` into NodeBB.
