### ISSUE TITLE
Rewrite chat frontend

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6192]
For the following reasons, chat has not been given as much love 😄 

* Built very early on, and has had many modifications made to it, and so is fairly difficult to theme
* Vanilla has not kept pace with Persona's updates to chat
* Mobile has always been an issue, with substandard usage of a bootstrap modal as a stand-in for a responsive view for chats
* `/chats` page was not usable on mobile devices

A foundational rewrite is in progress to address these shortcomings, and is available via the `chat-rewrite` branch. The corresponding theme branch is [`chat-rewrite` on nodebb-theme-vanilla](https://github.com/NodeBB/nodebb-theme-vanilla/tree/chat-rewrite).

### List of breaking changes

_including, but **not limited to**..._

* `expanded-chat/*` components have been renamed to `chat/*`
    * e.g. `component="chat/controlsToggle"`
* `chat/leave` component has been removed
* `chat/room/name` component moved to the modal header (instead of the input, which has now been removed)

**Comment by julianlam** [comment]
**In progress screenshots**

![image](https://user-images.githubusercontent.com/923011/34264968-8f208fae-e642-11e7-898d-01648158c38b.png)

**Mobile view**

![image](https://user-images.githubusercontent.com/923011/34264984-9d158bc8-e642-11e7-8c50-244eb17e7a90.png)

**Comment by aStonedPenguin** [comment]
Fantastic chats really need some work. Some backend changes for chats would be cool too.

- Ability to show users full chat history when adding them to a chat
- Mark all as read in the chats page instead of just the dropdown
- Delete all button in chats page
- Automatically purge chats with no users in them after X amount of time in ACP options
- Alternatively or additionally to the last idea the ability to automatically purge inactive chats after X days; I have 100s of chats open on my forums that neither I nor the sender/recipient will ever touch again. It's useless to store the data at this point.

**Comment by julianlam** [comment]
@aStonedPenguin Thanks for the feedback -- we'll work on building a solid base for chats first and aiming for feature parity before adding in more features.

Specifically in regards to archiving old chats, different admins view this topic differently. Some are very interested in maintaining a historical record, and so we likely won't implement any sort of auto-purging.

**Comment by aStonedPenguin** [comment]
Having it as an optional feature to fit everyones needs would be ideal.

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/34275519-b5b74e68-e66b-11e7-80ff-7a6b0f19fe46.png)

Cog settings menu replaced with dropdown

**Comment by mohammadhassan99** [comment]
@julianlam Good job 😃 
I suggest you to make a search option for messages.

**Comment by julianlam** [comment]
WIP pushed to https://community.nodebb.org -- please leave all feedback here (though remember, we're shooting for feature parity, new features come later!)

**Comment by mohammadhassan99** [comment]
Hello @julianlam , I like it more than the current chat interface 😃 . I think something should be added: 
When you want to edit a message, you click on edit button. But then If you decide not to edit that message and write new message, you have to close the chat and reopen It. I think it is better to add a cancelling button for editing.

**Comment by julianlam** [comment]
> I think it is better to add a cancelling button for editing.

Makes sense 👍

**Comment by FaizanZahid** [comment]
Guys, looks great to see a new re-write for the front-end chat. Btw current chat version is also 100% responsive on mobile, just saying.

Here are the features i think would make chat next level, (like Facebook messenger ;)

1. Allow users to upload pictures/videos and send to each other. (Users will love this), ( we can also host the uploaded images and videos on some 3rd party like imgur or cloud to avoid the burden on server)
https://community.nodebb.org/topic/11770/ability-to-upload-and-send-pictures-videos-in-private-chat/2
We can also make the chat input box HTML5 draggable to let the users drags pics/videos and upload in private chat.

2. Allow users to select from list of Emos or Gifs using lets say from this https://github.com/OneSignal/emoji-picker

3.  Ability to mark individual conversations as read/unread.

4. Ability for users to hit a mic button next to chat, record a voice note and send the voice note,. (I know this is too demanding, but this can be thought of) like whatsapp voice notes.

6. Are you guys also thinking to add a global shoutbox (or global public chat room seen and to be used by everyone on the site) for the site in core (rather than the https://community.nodebb.org/topic/503/nodebb-plugin-shoutbox-shoutbox-plugin ) as the shoutbox plugin has few bugs and its not compatible with the latest node bb updates.

**Comment by julianlam** [comment]
👍 Currently there are some issues with footer and header widgets. Investigating possible workarounds.

**Comment by mohammadhassan99** [comment]
@julianlam I've seen something in old chat system. When you are scrolling up and down in order to read previous messages, if the user writes a new message, the system scrolls down to new message automatically. You know it bothers users, if they are reading messages they have to scroll repetitively! . I think it is better to show a button when a new message sent. Like **[this](https://image.flaticon.com/icons/svg/78/78300.svg)**
I hope you understand what I say.

**Comment by mohammadhassan99** [comment]
Hi @julianlam , I saw some problems in new chat design: 
1- In this screenshot 👇 , I showed design problems with right arrows and squares. As you see, I think something should be changed.

![1](https://user-images.githubusercontent.com/31972226/35068968-fb9d10c4-fbed-11e7-932b-62673e10a519.png)

2- Here when you change the language to fa-IR, you see that the setting icon and other icon ( sorry I don't know the name of that icon 😄) are separated from each other, as I marked with red square. And other design problems. Also we have this problem in chat pop up.

![2](https://user-images.githubusercontent.com/31972226/35069285-fab099dc-fbee-11e7-8981-be8ba81e836a.png)

![2018-01-18_012311](https://user-images.githubusercontent.com/31972226/35069302-05ab765e-fbef-11e7-85df-648fd8705531.png)

3- In old chat design, you could see previous message in chat list. But now you cannot.

![3](https://user-images.githubusercontent.com/31972226/35069358-308efa12-fbef-11e7-887d-233fc395a67e.png)

**Comment by pitaj** [comment]
Looks like you have other CSS problems. The header is larger than it should be.

**Comment by julianlam** [comment]
Hmm, what you said about the header actually suggests my code is using a hard coded top margin, which should be updated.

**Comment by mohammadhassan99** [comment]
@pitaj What do you mean? should I try with other browsers?

**Comment by mohammadhassan99** [comment]
@julianlam As you know, now user can enable or disable receiving chat email in /setting page. I suggest to make this optional for each chat. I mean the user can disable or enable it for each chat room.

**Comment by julianlam** [comment]
* https://github.com/NodeBB/nodebb-theme-persona/commit/29164c74ad0579e295d9c63cdadf8e466ce46942
* https://github.com/NodeBB/nodebb-theme-vanilla/commit/53f7ad396e0ba901993b6a042af01a9e57502143

![selection_241](https://user-images.githubusercontent.com/923011/35115699-16395208-fc57-11e7-9fea-2f112a1d9484.png)

**Comment by julianlam** [comment]
![selection_242](https://user-images.githubusercontent.com/923011/35116200-94116340-fc58-11e7-8902-01bd4755a3a1.png)

**Comment by mohammadhassan99** [comment]
Hi @julianlam , when I want to add new user to room, the button doesn't work! It is noticeable that this problem happens when you open chat pop-up. When you open /chats page It doesn't have any problem

And also the sending button text is vise versa in fa-IR language 😃 

![2018-03-07_021033](https://user-images.githubusercontent.com/31972226/37062855-e1e2d936-21ac-11e8-8297-19d59d44f00f.jpg)

**Comment by julianlam** [comment]
@mohammadhassan99 Darn, I thought I got it right for RTL... what do you mean it is vice versa? I made it so that the button is on the left... should it not be?

**Comment by mohammadhassan99** [comment]
Excuse me @julianlam , I think I didn't mean correct. Yes I think it is backwards as you see.

**Comment by mohammadhassan99** [comment]
@julianlam When you delete your message, It doesn't delete that for user you are chatting with. Am i right?

**Comment by julianlam** [comment]
> Yes I think it is backwards as you see.

No, actually, I **don't** see, as I cannot read any RTL languages :frowning: Can you show me what it is supposed to look like?

**Comment by mohammadhassan99** [comment]
@julianlam It should be ``ارسال``. 
I think I found a bug and you should see **[this GIF](http://uupload.ir/files/wuqp_video_2018-03-07_194355.gif)**.

**Comment by mohammadhassan99** [comment]
Hi @julianlam , it seems like that we have some design problems in new chat system! 👇 

**[Screenshot](http://uupload.ir/files/2bht_screenshot_2018_03_08_13_17_16.png)**

Skin: cerulean

**Comment by julianlam** [comment]
I don't think there will be compatibility with skins. Can you try without the skin please.

**Comment by mohammadhassan99** [comment]
@julianlam Even we have this problem without the skin!

**Comment by julianlam** [comment]
![selection_314](https://user-images.githubusercontent.com/923011/37299041-9109761e-25f8-11e8-8d6f-6598f08b3cbf.png)

Unfortunately I am unable to reproduce. Perhaps you have some custom CSS interfering with the styling, but if I cannot reproduce this locally, then I cannot fix this issue for you.

**Comment by pitaj** [comment]
Also, try running `./nodebb build` and restarting.

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/37439811-3f61aadc-27d0-11e8-9ead-1bf0176a8d96.png)

Ah, there's the backwardness :cry:

**Comment by julianlam** [comment]
fd13f690aedf633254474b7821056920031055a3
