### ISSUE TITLE
Use CSS for logo instead of img element

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6251]
Hi!

Currently the forum set the forum-logo image with an `img` element. This approach is not the same as the rest of the design management.

Can you simply apply a background-image on a div instead of using img? With it we can customize the forum logo for each category without using javascript or an unfully supported css trick.

Thank you!

**Comment by julianlam** [comment]
Hi @antoine-pous -- I'm going to close this because it's not really something we want to do.

**Firstly**, the use of a div with background image breaks semantic HTML, in that it says nothing about the page itself. A basic web crawler or screen reader wouldn't be able to tell that it's an image, or that it is a fairly important image.

**Secondly**, constructing it in such a way to allow proper sizing based on header size and screen resolution requires javascript (or alternatively, additional CSS). Additional code that can lead to bugs and would not work on our "no-js" version of NodeBB.

All in all you should use the `img` element because it is well supported across **all** browsers (except lynx... NodeBB kinda sucks on lynx, but that's ok I think), and purposefully implementing a cumbersome alternative when a perfectly sensible implementation is already present isn't worth it to me.

The best way to implement this would be to fork the theme yourself to modify the image element if you'd like to customise it based on category... but if you're going to go through all that work, I'd rather just add custom js in the "custom js" page to change the logo's `src` on `action:ajaxify.end`
