### ISSUE TITLE
filter:user.whitelistFields is implemented terribly

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#6438]
Issue: 
In order to get some custom data you've set with `User.getUserFields` you need to whitelist it, but what if that data shouldn't be public? Do you bubble gum in your own function? Do you unknowingly whitelist it and expose the data to anyone who knows how NodeBB works?

Suggested fix:
Add `User.getUsersWhitelistedFields` , change  `User.getUserFields` to not be whitelist only and update current code accordingly.

**Comment by julianlam** [comment]
Ran into this issue with GDPR stuff, as it's needed in user profile but shouldn't be accessible in user data.

In the end I just made a direct `db.getObjectField` call to the user hash, but I agree, this is not the best solution as I _should_ be using `getUserData` or some such similar method.

**Comment by attis** [comment]
Stumbled upon this today too... I turns out that our plugin that sets a data through `User.setUserField` cannot read it back through `User.getUserField`. We definitely don't want to expose that field by whitelisting it.

Current behavior is counterintuitive. While I acknowledge the fact that we want to prevent the potentially sensitive data to be leaked, I am forced to use the same workaround @julianlam  had to use by fetching from user hash directly. `get/set` method pair should be excluded from any filtering and a safe (i.e. applying filtering) version of `get` should be created.
Another approach would be to implement some kind of sandboxed, per-plugin user field storage that only code from appropriate plugin could access. Not sure if that's possible to distinguish which plugin the code belongs to, though...

**Comment by julianlam** [comment]
Hooray! We got a comment after I added the RFC label :sweat_smile: 

Suppose I will look into this again and implement the changes as recommended earlier.

**Comment by julianlam** [comment]
Assuming we're going to remove whitelisting from `getUsersFields`, I am auditing the calls to `getUsersFields` (other related methods like `getUserFields` just call the pluralised form and return the first array object).

----

Doing so reveals the following methods call `getUsersFields` without any sort of filtering on arguments (suggesting some filtering or whitelisting would be necessary):

* `Groups.getUsersFromSet` (`src/groups/user.js:9`) via `Groups.get` to retrieve pending and invited users
    * Both invocations of the former send in the same arguments, so these arguments can likely be hardcoded
* `User.getUsersCSV` (`src/user/admin.js:42`) &ndash; arguments are variable based on what is returned from plugin hooks
    * Whitelisting required
* `User.getUserFields` (ditto) via `User.getUserField` via `User.updateProfile` &ndash; fields variabled based on plugin hook return
    * Whitelisting required
* `User.getUsersData` (`src/user/data.js:130`) &ndash; arguments are variable based on caller function
    * Whitelisting required
* Local method `filterAndSortUids` (`src/user/search:83`) via `User.search` &ndash; fields are dynamic but whitelisted already, no action required.

----

A `User.whitelistFields` can be added to `src/user/data.js` and the existing whitelist code can be removed from `User.getUsersFields` and this new helper method can be called on the methods that require it.

**Comment by julianlam** [comment]
Disregard the above, I think I've been going about the entire thing incorrectly. The problem is as described above:

> * The aim is to prevent leakage of information when run in a broad context (e.g. .getUsersData())
> * It is likely safe to assume that when .getUserField() is called, you know what you are doing

If you pass in a set of fields into `getUsersFields` (which is the common method here), you should get back what you requested. Whether or not you should have access to it is outside the scope of this issue, but the goal here is to prevent _accidental leakage_, so the whitelist as is functions perfectly fine, it just is overreaching in that it is invoked on all cases, when it should only be invoked if the `fields` argument is `[]`, in which case it would return all fields (but now correctly only returns those specified in the whitelist).

> Another approach would be to implement some kind of sandboxed, per-plugin user field storage that only code from appropriate plugin could access. Not sure if that's possible to distinguish which plugin the code belongs to, though...

A wonderful idea, but bears some further research :smile:
