### ISSUE TITLE
Subtractive permissions

### ISSUE THREAD

**Issue by kevinoost** [NodeBB/NodeBB#6477]
At the moment, permissions are additive only. We desperately need this to be subtractive as well. 
For our forum, we create a birthday gift topic for each person. This should be blocked for that particular person, but the way this is setup as additive permissions results in a cumbersome process.

**Comment by julianlam** [comment]
Hi there -- we created the privileges/permissions system as additive because  it made the most sense at the time (and it still does as far as I am concerned). With exception to a select few edge cases, such as your birthday gift topic, the system actually does work quite well and it would be a **huge** task to add on a subtractive system that works bug-free in conjunction to an additive system, and replacing one with the other is an absolute no-go at this point.

What I would recommend is creating a plugin to disallow access to specific topics based on uid. Perhaps you can have it automatically search for the topic title `^Birthday Topic for (\w+)$` and then automatically disallow that user access via plugin hooks.
