### ISSUE TITLE
Disable user list

### ISSUE THREAD

**Issue by admiralen1** [NodeBB/NodeBB#6482]
I think there should be an option to completely disable the user list. Currently it can only be disabled for guests and hide the "users" tab, but registered users can still navigate to /users.

**Comment by julianlam** [comment]
Hello there -- we feel that maintaining a users list is an important part of the community experience, and that's why the most we do currently is hide the userlist from guests.

If you would like to remove access, you can create a plugin and override the /users route to not allow access. Alternatively, if you are using a reverse proxy, you can just disallow all requests to `/api/users` or `/users` directly.
