### ISSUE TITLE
Show post time without js

### ISSUE THREAD

**Issue by admiralen1** [NodeBB/NodeBB#6559]
As I'm managing a privacy focused forum, some users would like the ability to view post time without the need of javascript. This seems like a fairly simple addon, though I'm not sure of what the work required for this would be.

**Comment by psychobunny** [comment]
You could fork the theme you are using, everywhere there is a [timeago element](https://github.com/NodeBB/nodebb-theme-persona/search?q=timeago&unscoped_q=timeago) replace that with just the time, ex.

`Edited by X <span class="timeago" title="{editedISO}"></span>`

replace with

`Edit by X on {editedISO}`

Though that would affect all users. So if you're hoping to be able to have an option for both I think that's more challenging than you'd expect because every theme can implement their own way of showing timestamps.

**Comment by pauljherring** [comment]
An alternative is that people could individually change their CSS (under /user/\<username>/settings) to display it:

```
.timeago:after {
  content: " [" attr(title) "]";
  font-size: 11.9px;
}
```
![image](https://user-images.githubusercontent.com/3939886/41158313-61ae5a52-6b20-11e8-8dad-66ad541e2908.png)
