### ISSUE TITLE
Ability to block one or more users from chat

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#659]
and probably the blocked-user will not even see online-status, always offline.

**Comment by FaizanZahid** [comment]
new user statii. ??? i didn't get it. do we have a mute or ignore feature for users?

**Comment by julianlam** [comment]
Whoo, this is an old issue. "New user statii" is just the busy/away statuses for NodeBB. You can appear offline if you don't want to be contacted (although people are still able to send messages to you).

I believe at this time you can limit chats to people who you follow.

**Comment by FaizanZahid** [comment]
agree with you julian, so we have tried installing this plugin , https://www.npmjs.com/package/nodebb-plugin-ignore-users

but it is not compatible and not seems to work with node bb 1.8.1 and i really think this feature should be introduced in node bb core.

Because blocking and ignoring specific users on any modern forum software is a must, so i will appreciate if you guys can mark this issue open and see if we can add it to core?

This will be a very nice and one of the most requested feature from our users.

**Comment by FaizanZahid** [comment]
i have already opened a github issue on that plugin to let the owner know its not working with 1.8.1

**Comment by FaizanZahid** [comment]
perhaps i will rename this, coz we need a global ignore feature such that if a user is blocked or ignored by me, i should not see any posts, replies, topics, or messages from that user. just like it works on reddit and quora.
