### ISSUE TITLE
Private category privelege

### ISSUE THREAD

**Issue by ende124** [NodeBB/NodeBB#6628]
It would be nice to be able to create some sort of private category. Each user in group x would only be able to find and view their own topics in that category. Users in group y would be able to find and view all topics.
This could be useful in some communities where a user can submit for example a report against another user, or player if we're talking gaming community, where that info should not be publicly accessible.

You could disable "access topics" for group x, but group x would still be able to view who submitted what and the latest reply.

**Comment by pitaj** [comment]
How does the current privilege system not cover what you want?

**Comment by ende124** [comment]
@pitaj I'm not sure if I'm doing anything wrong, but I can't figure out how to achieve this with the current privilege system.
If it is possible, please elaborate how.

**Comment by julianlam** [comment]
At current, we don't have this type of privilege functionality (the ability to view your own created topics, but not of others). The reason for this is because it is difficult to resolve pagination issues once you filter out topics that a user shouldn't be able to see.

At present we do not feel that this is a significant enough usage case to warrant additional research.
