### ISSUE TITLE
url, port configuration not DRY 

### ISSUE THREAD

**Issue by LudwikJaniuk** [NodeBB/NodeBB#6670]
Version: 1.10.x

This is not really a technical bug, but rather a design issue. The config.json file has the URL option, which is supposed to include the port according to example (https://docs.nodebb.org/configuring/config/). However, there is also an additional `port` entry which overrides the port.

I find this problematic since now I have to remember two places when changing ports. I happened to have the old port in `url` but override to something different in `port` through env vars, and that gave me some not-so-obvious problems with callbacks from auth services.

I think the config should not make two places available to set the port, however I understand if you feel that changing this wouldn't be worth it for the benefit.

**Comment by julianlam** [comment]
Port in config.json is optional. If not defined it will read from URL and if it's not in url, then it will assume 4567

Passing a port in via environment variables will override the port value in config.json, I think.

Seems like the issue here is you're defining the port in as many places as possible, when they're all optional.

**Comment by barisusakli** [comment]
Another reason we have "port" in config.json is because it can be an array of ports.
