### ISSUE TITLE
Permalinks for posts within a topic should be anchor links instead of hyper links

### ISSUE THREAD

**Issue by vennmann** [NodeBB/NodeBB#6710]
I see the current link permalink structure has /2 /3 etc

eg, https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed/21

Also in the above page I see, links like https://community.nodebb.org/post/58609 if you mouse over on the dates of the posts, which is redirecting to https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed/21

Instead of /21 won't it be nicer and SEO friendly to have anchor links, like #21 appended at end as below,
https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed#21

Also the current permalinks have same title as topic title, so it looks like duplicate. Atleast if we can't achieve above, we can have an option to noindex these pages and also change title to include post ids like post #21

**Comment by julianlam** [comment]
We use discrete URLs because hashes did not work well with pagination and infinite scrolling.

As for SEO penalty, I do not see any evidence that there is anything here that harms SEO... Take a look at page source on a "page 2", there should be a canonical link to page 1. This resolves any duplication as per Google's recommendations. noindexing these pages would be even worse for SEO.
