### ISSUE TITLE
Deleting group with numeral name makes equivalent user id unable to login

### ISSUE THREAD

**Issue by rookwood101** [NodeBB/NodeBB#6942]
- **NodeBB version:** 1.10.2
- **NodeBB git hash:** dbc7c2cc466601321e01714421f28cde6ca6cbd6

- **Database type:** mongo
- **Database version:** 4.0.4

- **Exact steps to cause this issue:**
	1. I created a group called `1`
		a. This happens with any numeraled group
	2. I deleted the group
- **What you expected:**
I expected only the group to be removed

- **What happened instead:**
Instead, I was unable to login to the admin account (user id 1) -- error message "Local login system has been disabled for non-privileged accounts". The group was also removed, as expected.

This seems quite serious but obscure. Only a big problem if users can create groups .
Thanks for taking a look!

**Comment by barisusakli** [comment]
This bug was in the codebase for 4+ years, introduced here by me 🐰 https://github.com/NodeBB/NodeBB/commit/fde8e9d90f92ef1d3cf8379f44eecf8879fcbcbb 

When a group is destroyed we remove it from other groups. This is done so privilege groups don't have deleted groups in them. The code was removing the groupName from all groups (privilege groups , registered-users, administrators, ...) When groups names were non-numeric this wasn't an issue since registered-users and administrators groups only have numeric user ids, but when a group name is numeric it was mistakenly removing the user ids from those system groups.

The fix limits the removal to just privilege groups.

Thanks for reporting 👍

**Comment by rookwood101** [comment]
Thanks for fixing so quickly!
