### ISSUE TITLE
jquery error on ie9

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7164]
![image](https://user-images.githubusercontent.com/2583394/50447893-438b0880-08ec-11e9-8e94-291ad0ffe04a.png)

Possibly has something to do with this 

![image](https://user-images.githubusercontent.com/2583394/50447900-53a2e800-08ec-11e9-973d-1ed246d5d099.png)

Can be reproduced by setting document mode and user agent string to 9 in IE11.

**Comment by pitaj** [comment]
We don't support IE9 do we?

**Comment by barisusakli** [comment]
Not sure, we use jquery 3.2.1 which does support ie9 and up I think. 

Browser Support
As of jQuery 3.0, the following browsers are supported:
https://jquery.com/upgrade-guide/3.0/#browser-support
Internet Explorer: 9+
Chrome, Edge, Firefox, Safari: Current and Current - 1
Opera: Current
Safari Mobile iOS: 7+
Android 4.0+

**Comment by julianlam** [comment]
Nope

On 26 Dec 2018 12:33, "Barış Soner Uşaklı" <notifications@github.com> wrote:

Not sure, we use jquery 3.2.1 which does support ie9 and up I think.

Browser Support
As of jQuery 3.0, the following browsers are supported:
https://jquery.com/upgrade-guide/3.0/#browser-support
Internet Explorer: 9+
Chrome, Edge, Firefox, Safari: Current and Current - 1
Opera: Current
Safari Mobile iOS: 7+
Android 4.0+

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NodeBB/NodeBB/issues/7164#issuecomment-449998357>, or mute
the thread

**Comment by barisusakli** [comment]
```
	<script defer src="{relative_path}/assets/nodebb.min.js?{config.cache-buster}"></script>

	<!-- BEGIN scripts -->
	<script defer type="text/javascript" src="{scripts.src}"></script>
	<!-- END scripts -->
```

Removing `defer` on these fixes the issue on ie9, this is happening because of https://github.com/h5bp/lazyweb-requests/issues/42.

Closing as we don't support :tm: ie9
