### ISSUE TITLE
Option to show all badges by default

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7180]
Via Admin CP, there should be an option where users have all badges selected by default - users shouldn't be setting badges manually.

Especially where we make extensive use of groups (basically every user is in 2+ groups), they should have all badges shown by default.

**Comment by julianlam** [comment]
Display of badges is controlled at the theme level, themes can elect to show all badges, as the data is (or should be, anyway) available for use in templates.

**Comment by tom-rade** [comment]
@julianlam https://github.com/youhosi/nodebb-theme-oxide/issues/8#issuecomment-451770673 Apparently it's limited to the profile view.

**Comment by youhosi** [comment]
@tom-rade Not in the user profile, only in the topic preview. Namely, in the profile it is impossible to display all groups in which the user is located without selecting them in the settings.

**Comment by pitaj** [comment]
Maybe we could send a list of all of the user's labels in addition to what is already supplied. An array of objects, each with a `display` boolean property?

**Comment by julianlam** [comment]
I initially thought maybe we had an issue with being unable to correctly display multiple badges, but after looking into it, the logic is sound (if a little convoluted).

Multiple badges can be displayed in both user profile and topic posts, as long as "Allow multiple badges" is checked in the ACP (under groups settings).

It makes sense to be able to display all badges in a user profile, but I am hesitant to add the call into the posts retrieval logic because it is huge overhead for something that is not used in our themes. It would actually cause a non-insignificant slowdown in our topic rendering pipeline.

You can do this in a plugin (or @youhosi, in your theme, if you wish), by listening to `filter:posts.modifyUserInfo` and retrieving and appending the user's groups there.
