### ISSUE TITLE
Can mobile styles and computer styles be developed separately?

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7190]
We have developed a set of computer styles, which has led to problems in the mobile-side styles. Would you like to ask if the mobile styles can be officially used?

**Comment by pitaj** [comment]
I'm not sure exactly what you're asking. I understand what you mean by "computer" vs "mobile" style, but I don't know what your question means.

In order to target specifically mobile or desktop sizes, you can use Bootstrap media queries to target specific device sizes: https://getbootstrap.com/docs/3.3/css/#grid-media-queries

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
