### ISSUE TITLE
Feature Request: Two-click (or as close as) to add user to StopForumSpam

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#7212]
To simplify adding users to StopForumSpam, since currently it involves copy/pasting three times between at least 2 (3 if the user is already registered) web pages...

https://www.stopforumspam.com/usage > Adding to the Database for details of SFS's API.

Admin/Moderator profiles would require an extra field into which the API Key (generated at https://www.stopforumspam.com/keys) would need to be stored. If this field is empty they attempted usage of the reporting buttons/functions below would generate an error indicating it needs to be filled out.

Anyone without privileges to view another user's IP address and email would not have this entry visible, nor would the reporting features be visible.

![image](https://user-images.githubusercontent.com/3939886/50892796-37786e00-13f7-11e9-92f9-b753015981ab.png)

A report button would, at a minimum I suggest, be required on

- Registration Queue ([/admin/manage/registration](#))
![image](https://user-images.githubusercontent.com/3939886/50892325-1fecb580-13f6-11e9-8d1e-8cdd86beae43.png)

- User page ([/user/$USERNAME](#))
![image](https://user-images.githubusercontent.com/3939886/50892412-56c2cb80-13f6-11e9-9934-ecddd2d27e67.png)

Clicking those would take user to a new page listing the three known items about the user that will be reported (username, email, IP address) and would have an extra field for any evidence, and that page would submit to SFS.

**Comment by pitaj** [comment]
Perhaps this is better handled by the spambegone plugin? It deserves some pretty significantly improvements, at the moment SFS isn't even used by it I think.

**Comment by pauljherring** [comment]
I thought the underlying data retrieved from SFS for the registration queue was in core?

**Comment by pauljherring** [comment]
@barisusakli - thoughts? :)

**Comment by pauljherring** [comment]
I meant, would that be a better place for this request? :D

**Comment by barisusakli** [comment]
The stomforumspam code is in core actually https://github.com/NodeBB/NodeBB/blob/master/src/user/approval.js#L238

**Comment by julianlam** [comment]
We've reached out to @akhoury directly to discuss moving all this into spam-be-gone :smile:

**Comment by akhoury** [comment]
So i started working on this but i could use a little bit of guidance @julianlam 

* Since stopforumspam was being used by nodebb core by default, I think it should be enabled by default in spam-be-gone, but
    * What happens when someone hasn't installed spam-be-gone? how should the Registration Queue page handle this? since right now, it relies on the result object `spamData` and `ipMatch` in the [template](https://github.com/NodeBB/NodeBB/blob/ff290880e279fbc448c0a9d0271bf11996b0a4f3/src/views/admin/manage/registration.tpl#L29-L60)
    * Do plugins have an "upgrade" process, if i were to enable this by default, I need to "update" this plugin's stored config object under [Meta.settings](https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/54b06581d6a8540e92880386c19e4a3226caf854/library.js#L30)
![screen shot 2019-01-15 at 9 38 06 pm](https://user-images.githubusercontent.com/1398375/51205165-eba15980-190d-11e9-8da0-e16c946a4e1d.png)

* I have no idea how to, __from the spam-be-gone plugin [load](https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/9fd042d88b99f593786df99b714f67187bdb7092/library.js#L23-L93) callback__, add the "Report to StopForumSpam" buttons, one in the Registration Queue, and the other on the user's profile, just like the last 2 screenshots that @pauljherring shared
![img](https://user-images.githubusercontent.com/3939886/50892325-1fecb580-13f6-11e9-8d1e-8cdd86beae43.png)
![img2](https://user-images.githubusercontent.com/3939886/50892412-56c2cb80-13f6-11e9-9934-ecddd2d27e67.png)

if that's in fact what we want to do, I really shouldn't be updating the core templates for this, no?

**Comment by pauljherring** [comment]
> if that's in fact what we want to do

Those were only suggestions  as to how I'd think it could work - they're not set in stone :)

**Comment by pauljherring** [comment]
> What happens when someone hasn't installed spam-be-gone? how should the Registration Queue page handle this? 

I'd go with don't show anything (extra) - same as if:

> Anyone without privileges to view another user's IP address and email would not have this entry visible, nor would the reporting features be visible.

**Comment by akhoury** [comment]
also related commit https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/8001ab16db8c69bba74da903bae17629c55fe952

**Comment by akhoury** [comment]
Ok, so this is 99% ready, I just have to actually test the final request "reporting a spam to stopforumspam", i tried to register so i can get an API key, but they didn't send me the initial email, i just contacted their administrator.

As of now, ONLY administrators and Global Moderators can actually report someone as spam.

### If StopForumSpam is enabled and API key exists

![screen shot 2019-01-19 at 12 50 33 pm](https://user-images.githubusercontent.com/1398375/51462308-efe3d180-1d68-11e9-9ac9-a5ed498ad40e.png)

![screen shot 2019-01-21 at 11 46 50 am](https://user-images.githubusercontent.com/1398375/51466224-5ae5d600-1d72-11e9-97dc-b07c5e158a42.png)


The error in red is because i used a fake key

### If StopForumSpam is enabled but no API key

![screen shot 2019-01-19 at 12 59 53 pm](https://user-images.githubusercontent.com/1398375/51462317-f5d9b280-1d68-11e9-9fe5-bc2aa2bcbcbf.png)

### If StopForumSpam is disabled or spam-be-gone not activated

![screen shot 2019-01-19 at 11 36 42 am](https://user-images.githubusercontent.com/1398375/51462327-fb36fd00-1d68-11e9-856c-83163dd881af.png)

**Comment by akhoury** [comment]
related commits: 
https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/d16f13c0900d71d823977f573a1c59263c353992 & https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/69145267d9172ddff83336d15dc39422a406a001 

![screen shot 2019-01-23 at 2 40 12 pm](https://user-images.githubusercontent.com/1398375/51607884-9e7d4300-1f1e-11e9-9ff3-29e69a1f1372.png)

**Comment by akhoury** [comment]
pending https://github.com/NodeBB/NodeBB/pull/7284
