### ISSUE TITLE
Meta dateModified is not updated

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7218]
Hello, I would like to report that there is no update when editing the post:

```html
<meta itemprop="dateModified" content="">
```

I checked it in my forum as well as on the official NodeBB.

**Comment by julianlam** [comment]
Hi @youhosi -- this should be of no consequence. The value need not be updated on the client-side because the purpose of the `meta` tags in the post body itself is for Google to read when they crawl the post itself.

During the crawl attempt, the page is loaded and the html scraped, so it will always reflect the latest value.
