### ISSUE TITLE
Cannot find module when run nodebb.bat

### ISSUE THREAD

**Issue by persevereVon** [NodeBB/NodeBB#7263]
- **NodeBB version:** master
- **NodeBB git hash:** c831ff0de39a0cd731e29abf633999e4ed990609
- **Database type:** mongo, redis, or postgres
- **Database version:** 
- **Exact steps to cause this issue:**
on windows.
```
git clone https://github.com/NodeBB/NodeBB.git
./nodebb.bat setup
```
- **What happened instead:**
```
PS D:\workspace\NodeBB> ./nodebb.bat
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './package-install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Module.require.main.require (D:\workspace\NodeBB\require-main.js:8:10)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\workspace\NodeBB\src\cli\index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by pitaj** [comment]
I'm not sure what causes this issue, but I can reproduce it.

**Comment by persevereVon** [comment]
because of this 
https://github.com/NodeBB/NodeBB/blob/c831ff0de39a0cd731e29abf633999e4ed990609/require-main.js#L7-L9
./nodebb.bat the `require.main` is `./src/cli/index.js` not `./nodebb`

**Comment by pitaj** [comment]
From the stack output, it looks like that, but I don't see how that could be.

- `require.main.require` is not used to import any modules in core
- and plugins are not activated before setup
- nor is `require-main` required in `package-install.js`
- the path relative to which `require.main.require` resolves paths should always be the top nodebb directory, since `require` in the `require-main.js` file should always be relative to the file, not the working directory
- `node ./nodebb` should be identical to `node ./src/cli`, the first one just requires the second, and I don't see how working directories could come into play, since `require` doesn't care about that

**Comment by pitaj** [comment]
I can reproduce this with a minimal set of cut-down files. It's very odd behavior, that only occurs after `require.main.require` is overridden. I thought this might be due to that process resulting in `require` in `src/cli/index.js` being overridden as well, but that doesn't seem to be the case either. I'm going to open an issue on the nodejs repo about this. It's very odd.

**Comment by persevereVon** [comment]
> When a file is run directly from Node.js, require.main is set to its module. That means that it is possible to determine whether a file has been run directly by testing require.main === module.

The difference of `node ./nodebb` and `node ./src/cli` is `require.main`.
https://github.com/NodeBB/NodeBB/blob/cb8650e8e0f3d4a8ffd11c9f6f49b482b94249f5/require-main.js#L6-L10

The code above is changing the `require` in `src/cli/index`.

https://github.com/NodeBB/NodeBB/blob/cb8650e8e0f3d4a8ffd11c9f6f49b482b94249f5/src/cli/index.js#L8

this `require` is the `require` in `require-main.js`, so the module can't found.

emm... sorry for my english, I don't know if I make it clear.

**Comment by pitaj** [comment]
> The code above is changing the `require` in `src/cli/index`.

But that doesn't make any sense. JavaScript just doesn't work that way. Also, I specifically checked for that case, and it isn't happening.

Only through some crazy bug could something like this happen in the first place.

**Comment by persevereVon** [comment]
Ok, if you find the problem, please let me know?
