### ISSUE TITLE
validate e-mail feature using MX records on registration to prevent fake e-mails.

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7285]
Syntax checking is fine, but nothing beats validating e-mail addresses using MX records on registration to prevent invalid e-mails. Please implement this.

**Comment by pauljherring** [comment]
You cannot validate email addresses using an MX record. 

The best you can do is verify that _someone_ has _claimed_ that there is a mail server that will try to handle any email address with the bit after the `@` sign.

Granted, checking for an MX record is a cheap check to see if it's worth even trying to send the email to begin with, and for catching certain types of accidental typos, but it in no way guarantees that the bit **before** the @ is at all valid.

As for 'preventing fake e-mails,' what this purports to prevent is easily worked around by supplying a host part that does have an MX record. Like, to pick a random example, `fakeemailaddress@kh` which is both 
- a valid email address and 
- apparently has a host that will take delivery of it:

```
 dig mx kh

; <<>> DiG 9.11.4-3ubuntu5-Ubuntu <<>> mx kh
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44602
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;kh.                            IN      MX

;; ANSWER SECTION:
kh.                     7190    IN      MX      10 ns1.dns.net.kh.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jan 23 14:30:40 GMT 2019
;; MSG SIZE  rcvd: 59
```

**Comment by tom-rade** [comment]
@pauljherring I meant invalid, not fake. And kh is invalid becausd it's server is apparently 127.0.0.1 according to dig. But gmail for example doesn't get 127.0.0.1.

Many users got emails like claudia@ or claudia@gmail

**Comment by pauljherring** [comment]
> I meant invalid, not fake

There's a substantive difference in this context? 

It doesn't change the fact that all it's checking is the bit after the @ and does nothing to check 'invalid' bits before the @, and all someone has to to subvert this check if they're being malicious is simply provide a valid mail host.

As I said, it's a quick check that could catch typos, but beyond that it doesn't get you very much, and certainly won't prevent fake emails.

> And kh is invalid because it's server is apparently 127.0.0.1 according to dig

It really isn't. The MX server for `kh` is `ns1.dns.net.kh` which resolves to `203.223.32.21`. 

You're probably looking at the `A` record, or something that isn't the `MX` record, the latter of which I provided in my previous post, along with the dig command I used to obtain it.

Or feel free to pop over to https://mxtoolbox.com/SuperTool.aspx?action=mx%3akh.

**Comment by tom-rade** [comment]
@pauljherring Well ok, but what about checking for a letter after the @ and a dot after that? Basic syntax email checks.

**Comment by julianlam** [comment]
@PJH is correct, we don't regex validate addresses because it's pointless and bad user experience on registering. If they don't want you to email them, they're going to get around whatever limits you place anyway, and it's a waste of system resources (I mean, google "email regex" and see if you want us to implement that monstrosity into our codebase)

> Well, yes. I'm surprised that doesn't happen at the moment, and probably needs addressing (pun not intended.)

If it's part of spec that `@` is followed up with at least one `\w`, then we can add that in, though I'd prefer if we avoid using regex at all.

**Comment by pauljherring** [comment]
Well we could come full circle and simply run an MX check on anything after the `@`.

Presuming of course there is only one @ in there...

**Comment by pitaj** [comment]
The industry standard is to check for a single `@` character, and user email validation thereafter to check if the email is correct.

IIRC, `adbjivdtib@` is a valid email address according to spec.

**Comment by julianlam** [comment]
@tom-rade Think about _why_ you are wanting real email addresses... it's so that if you need to get in touch with them, then you have an email address, right? In that case, then requiring email verification is the easiest way to achieve that.

Adding email address syntax checks and all sort of shenanigans only complicates things and increases the odds of a perfectly valid email address erroring out. It is **specifically** why we only check for `@`: If your users don't want to be contacted, they will make sure they are not contacted, otherwise they will just not use your site at all.

**Comment by tom-rade** [comment]
@juliamlam Ok, fair enough. But in that case, users with unverified emails like "haha@" should not be able to read in the forums without verification.

**Comment by julianlam** [comment]
Yes that's the idea. If their emails are not verified then they can't post
(if the setting is enabled in the ACP)

We don't restrict viewing if the email is unverified.

On 23 Jan 2019 16:17, "tom-rade" <notifications@github.com> wrote:

@juliamlam Ok, fair enough. But in that case, users with unverified emails
like "haha@" should not be able to read in the forums without verification.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/NodeBB/NodeBB/issues/7285#issuecomment-456969546>, or mute
the thread

**Comment by tom-rade** [comment]
@julianlam That's the problem. Closed forums really need this.
