### ISSUE TITLE
No permission in Advanced > Database, shared hosting

### ISSUE THREAD

**Issue by r0v** [NodeBB/NodeBB#7385]
- **NodeBB version:** 1.10.1
- **NodeBB git hash:**  c8d3c3197ba3025ed395e400f8cb0b312fac790e
- **Database type:** mongo
- **Database version:** v4.0.3
- **Exact steps to cause this issue:**

    - First I logged into ACP
    - Then, I clicked on Advanced > Database.

- **What you expected:**

Database info???

- **What happened instead:**

Huge red alert: 
```
Internal error. 
/api/admin/advanced/database

Oops! Looks like something went wrong!

not authorized on moXXXX_nodebb to execute command { serverStatus: 1, lsid: { id: UUID("6c10e4d1-9171-402a-1069-4de20fd0fs60") }, $db: "moXXXX_nodebb" }"
```
I'm using shared hosting based on [Passenger](https://www.phusionpassenger.com/) software.

I contacted with my hosting provider and their support reply me: "this is not the correct implementation of the solution on the nodebb side due to the requirement to perform activities not provided in MongoDB for the user level".

I don't know what I can do in this case.

**Comment by pitaj** [comment]
NodeBB expects to have permission to retrieve certain information from the DB. If the mongodb user you've selected for NodeBB doesn't have those permissions (in your case, this is likely set by the shared hosting provider) then fetching that data fails, resulting in the error you see.

It might be better for NodeBB to display a special error message instead of just a 500 code in that case.
