### ISSUE TITLE
Latest bootstrap and fonts

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7396]
Hello, I would like to know if NodeBB is planning to upgrade to a newer bootstrap and fontsawesome? This would diversify the whole forum and added new icons.

I guess it would be a lot of work, so I could always help in some way.

**Comment by julianlam** [comment]
Hi there -- bootstrap updating is something we're keen to do, but it's quite difficult because there are many breaking changes, the biggest of them all being that it is no longer built on LESS, but on SCSS. That means we really ought to switch our own code to SCSS if at all possible.

It also means that practically every plugin that depended on bootstrap 3 would break (in unexpected ways)... things like `col-xs-12` and `.panel` don't even exist anymore :frowning:

**Comment by julianlam** [comment]
It's my understanding that FA5 is a for-profit project, and so I am hesitant to update to it. We might use ForkAwesome if it gains traction.

**Comment by julianlam** [comment]
Looks like FA5 might be free, no objections to updating to it, I think.

**Comment by youhosi** [comment]
@julianlam Well, bootstrap will be a big change, but for the better, it will give more opportunities to other developers.

You can always use [octicons](https://octicons.github.com/), also these icons are great :)

**Comment by pitaj** [comment]
FA5 is a breaking change IIRC

**Comment by PostMidnight** [comment]
This article might be interesting: 
https://hub.packtpub.com/bootstrap-5-to-replace-jquery-with-vanilla-javascript/
Looks like BS5 also dumps jQuery, as others do.

**Comment by julianlam** [comment]
Updating to latest bootstrap (and possibly FA5) is on the roadmap, but there are no targeted dates as of yet. It will likely involve replacing Persona theme with a new theme, so we will track the issue outside of this bug tracker.

**Comment by youhosi** [comment]
@julianlam I can help you create a new theme :)

**Comment by pitaj** [comment]
Just FYI everybody: Updating bootstrap will require updating practically every plugin, every ACP page, and every theme.

This is a huge undertaking requiring cooperation between core and community developers.
