### ISSUE TITLE
 QPS reached 120， Is there any other solution besides expansion?

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7455]
NodeBB version: : 1. 11.1
NodeBB git hash:
Database type: mongo
Database version: v4.0.1
Exact steps to cause this issue:

When doing activities, the QPS reached 120 and the number of people online was more than 1500, which led to 503 pages. Is there any other solution besides expansion?

**Comment by julianlam** [comment]
Hi there -- you have a couple options here: MongoDB is almost **never** the bottleneck. It's fairly high performant, and the last step you want to do is shard the database. It comes with its own set of problems and is best left alone :smile: 

Have you tried upping the number of cores? Additional cores allow NodeBB to not compete with other system applications for resources. e.g. A two core server is ideal because then NodeBB can run on one and MongoDB on another.

Likewise, you can run NodeBB listening on multiple ports to handle more traffic via the `port` argument in config.

You can also horizontally scale (and we'd suggest this after scaling up to 2 cores).

For more information, please see https://docs.nodebb.org/configuring/scaling/
