### ISSUE TITLE
Docker image questions...

### ISSUE THREAD

**Issue by tilllt** [NodeBB/NodeBB#8022]
I have some questions regarding the NodeBB Docker image.

There seems to be an official docker image, here:
https://hub.docker.com/r/nodebb/docker/

Unfortunately there is NO documentation i could find, literally NOTHING. I managed to get the image running, using the docker-compose.yml from an inofficial docker image.

But the image doesnt seem to follow some very basic Docker "laws" which is persistance. Updating the docker with "docker pull" will delete your config and present the Installation GUI again. Is there some kind of documentation that i didnt find about this image? Or any contact to the maintainer to ask how to use this mystery image?

imho if nobody has the time to write docs or build an image that can be used safely, its probably better not to offer it in the first place.

**Comment by julianlam** [comment]
@tilllt I'd recommend you re-post this on our community forum, but the gist of it is that the maintainers of NodeBB do *not* use Docker simply because we decided not to, but not for any particular reason. We don't oppose it, but we also do not support it beyond providing a Dockerfile because we have limited expertise in the area.

So to that end, for Docker-related support inquiries, we'd direct them to our community forum at this time.

The ideal installation candidate is Ubuntu on a VPS, though we definitely _strive_ in principle to be installable on as many devices as possible.

**Comment by tilllt** [comment]
Just a quick feedback: the crowd on the nodebb forum is unreasonably hostile towards nodebb as a docker, which is pretty weird. in any case: the official docker image is broken, it overwrites persisent data (aka the database) on restart, i'd suggest removing it unless you find someone who will maintain it. which is pretty unlikely given your users attitude towards docker.
