### ISSUE TITLE
blocking a user should block them to see you as well

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#8109]
If it is possible,
  
* "ignore user" function
* "block user" function 
should both exist in the forum.

Especially a "block user" function that block people to see your posts will be very beneficial for our community. 
Thanks, 

https://community.nodebb.org/topic/14466/ignore-and-block-user-functions

**Comment by julianlam** [comment]
I believe "block user" functions more closely to your interpretation of "ignore user", but in our point of view, both those terms are the same... you're putting up a blinder against content you don't want to see, but it should not affect the experience of the other user (no matter how much you dislike them).

In my experience, if you block someone, you can trash talk them all you want, and then they can reply, but you just won't be able to see their replies ;)

**Comment by oplik0** [comment]
Started writing a post on forum before you've added the post about moving the discussion here :D 

You're right about Twitter. It seems they changed it when they added "mute" option. Earlier a block was fully transparent for the blocked person if your profile was public and only DM's didn't work, now it works both ways.

But Facebook mentions the exception in groups on their [help page about blocking](https://www.facebook.com/help/1000976436606344):
> Keep in mind that blocking someone may not prevent all communications or interactions (example: in apps or groups)

And I'd also argue that blocking on forum is different than on a social media platform, because forums usually aren't about user specific content (so no timelines, for example), but focus on topics instead. For example - take this topic. It really isn't at all about who you or me are, but about a specific feature (blocking) of a specific product (NodeBB) and most people won't be looking specifically at what's whose opinion is what.
Social media platforms focus on people instead. You don't have titles for discussions on Facebook or Twitters - you just have posts on user timelines. Many features there are focused on users specifically - that's why you have share buttons to show that you found something interesting.
On forums you don't usually share a post around the forum. Because the discoverability of content isn't based on users you're friends with, but categories and tags you're interested in.

Other forum software works the same way as NodeBB here: in phpBB you have foes list, that is essentially a block list and it is one way too. SMF and MyBB has ignore option.

But I agree that perhaps naming the option "ignore" instead of "block" might be better for clarity. Or perhaps just adding a confirmation box with description of what it does when you try to block someone. Right now it seems to just work on a button press, so an accidental block is actually possible.

**Comment by yariplus** [comment]
Facebook has the "Visibility" option for posts. "All users except..." results in blocking view of your posts.

Seems like that would be a possible capability to add.

**Comment by AliCihan** [comment]
> I believe "block user" functions more closely to your interpretation of "ignore user", but in our point of view, both those terms are the same... you're putting up a blinder against content you don't want to see, but it should not affect the experience of the other user (no matter how much you dislike them).
> 
> In my experience, if you block someone, you can trash talk them all you want, and then they can reply, but you just won't be able to see their replies ;)

Yes, that is correct... I did not write it explicitly since I thought it is clear. "ignore user" is what current blocking function does, that is why I asked both functions should exist. 

I understand your experience, but when other people replies posts of the blocked person, you can still see what he/she wrote about you. Additionally, since blocked person sees your post, even if you are not trash talking, they can try to interact with you. So, in our forum this is what many people are asking for. They do not want some people to see them or to write about them...

**Comment by AliCihan** [comment]
@oplik0 Thanks for the explanation, but I think other platforms should not be the focus of discussion. I feel they are just acting as red herring in this case. 

I believe I have explained why people are asking for it well enough, but if it is still not clear please let me know.

**Comment by AliCihan** [comment]
Hi @julianlam , will "blocking" function come? Since "quoting" in replies still can be seen by everyone, "ignore" function is not doing its job in our forum. People still can see messages from "ignored" people...

**Comment by oplik0** [comment]
Blocking won't fix the quoting issue though. Fixing it would require a change in how quoting works - since right now quotes are really just text styles by whatever formatting plugin you're using (usually markdown). They aren't linked to actual contents of the post you're quoting in any way.

**Comment by AliCihan** [comment]
It will solve the problem though...
because A blocks B, because A does not want to interact with B. But B still sees A's posts and replies to them... A does not see the replies until someone quotes them, and this starts an argument... When A blocks B, if B also does not see A's posts... that will solve the whole issue. Since both parties cannot see each others posts, there will be no replies and no quoting...

**Comment by oplik0** [comment]
If no one is quoting either of these parties the problem doesn't exist.
If A doesn't see posts by B and B doesn't see posts by A, but they both see posts by C and C quotes A - B can now see the quote and reply. Then if someone quotes B, A can see the quote.

Though I have a question - if A decided to block/ignore B, why don't they "manually" ignore quotes of B's replies? Just pretend that they didn't see it?

But oh well, just because I don't see the problem doesn't mean it doesn't exist.  So since I don't agree that two-way blocking should be added to core, may I propose a middle ground to NodeBB team? Plugin hooks somewhere in [src/user/blocks.js](https://github.com/NodeBB/NodeBB/blob/master/src/user/blocks.js).
`User.blocks.add` and `User.blocks.remove` - either action or filter - so that the plugin can make a block add the uid of blocking person to blocklist of the blocked person too, or `User.blocks.filter` so that the plugin can add uids to filters...

Though after another look it seems that it's possible to achieve the second option anyway by using `filter:post.getPost` hook and filtering posts there. It would probably require checking the blocklist for every uid in posts that are returned.
If there was an action filter on `User.blocks.add` (and remove) the plugin could keep track of "users who blocked you" which would speed it up - since now you'd just need to get one entry from DB and filter the posts based on just this one document, so I'd still be for adding that.

**Comment by AliCihan** [comment]
> If no one is quoting either of these parties the problem doesn't exist.

Yeah, but I guess it is impossible to control users this way. It is a forum and a lot of people are joining discussions...

> Though I have a question - if A decided to block/ignore B, why don't they "manually" ignore quotes of B's replies? Just pretend that they didn't see it?

Yeap, this is what I am telling them to do for months, but I can tell it is not working :) Additionally, many people are asking "both way block". You could be surprised :) But I have to mention that we are a very social group and also have lots of forum meetings in several cities, so for many people in the forum, other users are more than just a random person in a website, many people know each other personally because of these meetings and we could expect some people are not bffs :) 

Moreover, if this is too much work, I can ask about this option... I believe this will solve our issue... If an admin adds a user to another user's block list, that user shouldn't be able to remove it (It will be basically like post deleting, if an admin deletes a user's post, that user cannot bring it back). If this is possible to do, we can solve our issue this way...

**Comment by gotwf** [comment]
Came to this late.  Bummer.  And yes, I know it's a done deal.  That said, I agree w/Julian and oplik0 on this one.

Now unclear whether two way blocks are option or mandatory.  If latter, I presume mods and admins are exempted from such madness?

There is the ban button you know - trolls who don't play nice can always be given a spanking.  In my experience it does not require many temp bans, and maybe only a couple perma-bans, for miscreants to get the message.

Of course then you also must run the gauntlet of AI driven sock puppet accounts....

**Comment by AliCihan** [comment]
It is optional...

If you want to implement, you have to install this plugin:
https://github.com/oplik0/nodebb-plugin-two-way-block

Otherwise, everything in the forum will be as usual.

**Comment by gotwf** [comment]
Ah,  thanks for the clue bat.  Good to know.  I missed the "plugin" bit from the OP and should have done a bit more clickery here.  

Thanks for your indulgence. :v:

**Comment by oplik0** [comment]
Well, the plugin was my idea and implementation - while I was against adding this to core, I see no problem with allowing users to implement that themselves.
So I added hooks in #8286 and created [a plugin that implements what was requested here](https://github.com/oplik0/nodebb-plugin-two-way-block)
