### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by ghost** [NodeBB/NodeBB#8208]
I'm not sure if it's a better idea to create an issue for each feature request, so here is a list of improvements that I would love to see in NodeBB:

- Add ``Delete User content only`` button in ACP ``/admin/manage/users``. This is useful against users that spam the forum, but you don't want to delete the user entirely: just ban and delete his contents.
![](https://i.imgur.com/m6Iu6VA.png)
- Allow custom plugins to retrieve the raw BODY somehow. More info here: https://community.nodebb.org/topic/14521/getting-raw-body-for-hmac-sha256
- Re-add ``Delete events`` button that used to be in ``/admin/advanced/events``. More info here: https://community.nodebb.org/topic/14585/safe-to-delete-events-and-event-keys
- Add button in ACP to cleanup database, deleting keys like "analytics", "events:", "event:", "ip:recent", etc. More info here: https://community.nodebb.org/topic/14474/safe-to-delete-analytics-documents
- Allow us to Delete/Lock/Purge posts directly in the /recent. I'm asking this because of spammers that join the forum and post in all categories. I need to enter in each category, select each post and delete/purge each one instead of doing it all from /recent.

Regards

**Comment by julianlam** [comment]
Hi there!

1. I'm having a hard time coming up with a use-case for a situation where you'd want to delete the entirety of a user's contributions, but retain the account. If they made quality content in the past, you'd have already scrubbed it all away, and without content a user account is essentially pointless anyway, in which case a user deletion would essentially be the same.

1. Re: raw body -- was this about the Stripe thing?

1. Ability to delete events should be added back -- let's ask @barisusakli why it was removed :smile: 

1. A database cleanup task could be added, although one wonders whether stuff like this should be automated away in the background anyway. Technically, it is still useful for some forums that like the historical data to be saved in database.

1. Good idea :+1:

**Comment by barisusakli** [comment]
I think delete events was removed to prevent admins from covering their tracks after they mess up the forum. Obviously only applies to forums where there are multiple admins and one of them goes :rage1:

**Comment by rdomzim** [comment]
1 - I use NodeBB with a custom plugin that offers some products, so I have paid users and regular users. Sometimes the paid users break the rules, so I need to delete their contents, ban them, but at the same time allow them to continue using the forum and the product that they purchased. To give another example, it's like a gaming forum where the user pays for the game, then goes to the forum, breaks the rules, gets banned on the forum only, all his content is deleted, but he can continue playing the game. Right now, the only option that I have with NodeBB is to go on every single post that the user made and delete each one, instead of hitting a "Delete user contents only" button.

2 - I don't use Stripe, but yes, I'm asking this raw BODY for another payment service that I use in my NodeBB plugin.

3 - @barisusakli Interesting. In that case, I think there should be a separate permission for admins instead of completely removing the button. Or the admin shouldn't even be an admin in the first place, but a moderator without this specific privilege. I'm the only admin in my forum so I really don't have these issues.

4 - A cleanup task makes sense if you can configure this task, for example, how long to keep analytics data, how many "events" documents should be stored in the database and if you go over a certain limit, delete the older documents, etc. Maybe have a setting for all these keys that can be safely deleted without causing bigger problems in NodeBB as they will just be recreated. Or a button to delete everything. Or some ``expire_at`` field to tell the database to delete the document after a certain time. 

5 - I have never used that post queue. From what I quickly looked, it does seem like a nice tool to moderate all the spams **before** they happen. I will play with it.

**Comment by julianlam** [comment]
A cleanup db event, we're not going to do (low value for us)

The other have been implemented, save for topic tools in `/recent`, which I will break out into a new issue.
