### ISSUE TITLE
fix gdpr link in translation file

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8283]
https://github.com/NodeBB/NodeBB/blob/master/public/language/en-GB/admin/settings/user.json#L12

language key has link to site that is under construction

https://eugdpr.org/the-regulation/gdpr-faqs/

**Comment by julianlam** [comment]
Probably best to point to the official site? https://gdpr.eu/faq/

**Comment by oplik0** [comment]
https://gdpr.eu is **not** an official site. It was co-founded in Horizon 2020 programme by EU, but Proton Technologies AG, the owners of this website (mostly known for ProtonMail and ProtonVPN) have a couple of projects co-founded there and it's far from making their projects representative of EU government (as far as I know other than controlling whether the funding was spent in declared manner the founding doesn't give EU **any** control over these projects).
You can find this information on the bottom of the page:
> GDPR.EU is a website operated by Proton Technologies AG, which is co-funded by Project REP-791727-1 of the Horizon 2020 Framework Programme of the European Union. This is not an official EU Commission or Government resource. The europa.eu webpage concerning GDPR can be found [here](https://ec.europa.eu/commission/priorities/justice-and-fundamental-rights/data-protection/2018-reform-eu-data-protection-rules_en). Nothing found in this portal constitutes legal advice.

Though I actually found out about this website because they ironically had a [security problem](https://www.pentestpartners.com/security-blog/gdpr-eu-has-er-a-data-leakage-issue/) recently (it wasn't dangerous since at least according to proton the website doesn't contain any user or other important data and access to database is limited to their internal network, so even knowing the password for that doesn't do an attacker much good, but still a bit ironic :)

**Comment by julianlam** [comment]
ah, suggestions on a good link?

**Comment by oplik0** [comment]
I'm not saying [gdpr.eu](https://gdpr.eu) is a bad site as it seems to be a great resource on gdpr compliance. And it does link to the official website in the disclaimer about it not being one. 
If you prefer said official website, however, it can be found at https://ec.europa.eu/info/priorities/justice-and-fundamental-rights/data-protection/2018-reform-eu-data-protection-rules/eu-data-protection-rules_en - it does have FAQs for businesses (https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations_en if you want to link it directly) and citizens.

There is also this official infographic/FAQ for businesses: https://ec.europa.eu/justice/smedataprotect/index_en.htm (it links to the first EU website I mentioned near the end)
