### ISSUE TITLE
Minimum Character Requirement for Usernames not checked when using SSO for login

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#8418]
- **NodeBB version:** 1.13.3

One of our community members registered using the GitHub SSO plugin and wanted to change their email.
However it turned out that having a 3 character username (in a forum where 4 characters are the minimum length) led to this error message:
![Error](https://user-images.githubusercontent.com/8350879/85204749-df95a480-b316-11ea-81e4-b2b651f860b2.png)

I'm not sure what an appropriate fix would be in this case, but there shouldn't be an error message in any case.

**Comment by AliCihan** [comment]
I believe the problem is that SSO plugins are not checking the username length... 
Then, users (since they cannot change their usernames) cannot change any info about them on profile page... 

We are also having problems regarding username beeing too long... 

https://community.nodebb.org/topic/14362/username-length-problems

**Comment by AliCihan** [comment]
It would be great if forum settings were respected by SSO plugin registrations... we had people registering with username "a" to the forum because of these plugins... 

Biggest problem is that when they have either very long or very short name, they cannot do any change to their profile because it keeps giving errors, so an admin had to be involved...
