### ISSUE TITLE
update ALLOW-FROM

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8432]
Looks like `ALLOW-FROM uri` is no longer a valid directive

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

https://community.nodebb.org/topic/14856/error-invalid-x-frame-options-header

**Comment by julianlam** [comment]
@samt Can you also take a look at this.

We use helmet [here, but we do not use helmet.contentSecurityPolicy](https://github.com/NodeBB/NodeBB/blob/master/src/webserver.js#L167-L177).

The reason we don't is because plugins can specify pulling of content from multiple sources (as can themes, etc.) and there wasn't any easy way to implement it, so we didn't for now.

Not sure if we can implement helmet CSP with no restrictions, but add in the `frame-ancestors` directive, as MDN recommends.

**Comment by julianlam** [comment]
[Helmet CSP docs](https://helmetjs.github.io/docs/csp/)
