### ISSUE TITLE
Can no longer reduce the size of the text area

### ISSUE THREAD

**Issue by jdaviescoates** [NodeBB/NodeBB#8858]
- **NodeBB version:** 
- **NodeBB git hash:** 
- **Database type:** mongo, redis, or postgres
- **Database version:** 

I'm not sure, but it's been since https://forum.cloudron.io/ updated to the latest version.

### What happens

1. I hit reply on any thread.  
2. I want to read some of the thread to double check what it says, or to quote or copy/ paste it.
3. I try to reduce the size of the text area box to enable me to see more of the rest of the screen
4. I can't. I can only increase its size.

**Comment by julianlam** [comment]
Hi @jdaviescoates -- we tweaked the logic that dictated the minimum size of the composer because there were issues with certain themes when they tried to override the composer template.

In particular, those using the composer on short viewports (either smaller or lower-resolution laptop screens, or a resized window) would end up with a composer that was too small to function. We wanted to adjust the logic so the textarea would be large enough. In some cases, it does mean the minimum ratio was automatically adjusted from before (which was a hardcoded 30% of the viewport) to something slightly higher (somewhere between 30-40% of the viewport)

In your particular use case, you'll want to minimize the composer in order to review the thread again. You can do this by clicking on the composer icon at the bottom right:

![image](https://user-images.githubusercontent.com/923011/98485247-092a6c00-21e3-11eb-98f2-a1a052f8ee78.png)
