### ISSUE TITLE
receiving notification when the followed user posts something

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#9145]
https://community.nodebb.org/topic/15209/receiving-notification-when-the-followed-user-posts

I think it would be useful if it works as in the other social media websites...

**Comment by barisusakli** [comment]
We had this but was removed in https://github.com/NodeBB/NodeBB/commit/9e8be432b32a4f0caedc9f58954a633f2e8fd3ae#diff-e979757e3e7d1889b93a47dbb014aeac45ea5388d2b0cff5984ec211aa3310c9

If I remember correctly it was due to performance reasons, user is followed by 1000s of users, they post regularly => tons of notifications sent to each user on every reply.

**Comment by AliCihan** [comment]
@barisusakli do you think a separate page can be created for this purpose? 

just like a page in the groups section, like forum.com/groups/X ... this page shows the post summaries by the people only in the group...

so in the page I proposed, you will only see posts from the people you are following, so it will be easier to catch up what they have written

**Comment by julianlam** [comment]
Kind of like a feed :thinking:

**Comment by barisusakli** [comment]
Time for nodebb-plugin-feed 😆

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-feed

It will display posts from users you follow. Has 4 wigdet areas to further customize it.

![image](https://user-images.githubusercontent.com/2583394/109236356-7287b800-779d-11eb-8bce-00d8a5abdffb.png)

Once I find more time I will add filtering by category/user etc.
