### ISSUE TITLE
Vulnerable database

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#9152]
- **NodeBB version:** v1.16.0

- **Database type:** mongo, redis
- **Database version:**  mongoDb 4.2.3 , redis 5.0.7

We recently received a message,  that I will share with you:

"Your database is really vulnerable to any attack, and hacking into it is very easy.
It is better to use a shield.
During last week, any harmful attempt and attack on your forum was very likely which could ban the access of all members to the forum with your account (adminstrator account)"

I'll be really greatful if you inspect the problem as soon as possible.
 Beside the probable attacks, during last week we had connection problems and getting high ping. Is it because of intrusion?

**Comment by julianlam** [comment]
Unfortunately the attacker didn't give much information for you to work off of.

That said, update `mongod.conf` and `redis.conf` so that they only listen to the loopback address (if the database is on the same server as NodeBB), and restart both services.

That's the easiest way to make sure nobody can access those services unless they already have shell access, or are using another vulnerable app as a side channel.

Also password protect MongoDB if you have not already.

**Comment by julianlam** [comment]
Unfortunately, vulnerabilities with MongoDB or Redis are outside our purview, and if there is a vulnerability there, I am sure those upstream package managers will want to know about it :smile:

**Comment by oplik0** [comment]
If for some reason you can't bind the databases to IP addresses, I'd recommend checking your MongoDB installation with [mongoaudit](https://github.com/stampery/mongoaudit).

But once again - if you can, bind the IP in database configs. If the databases are on the same server as the website, bind them to localhost and also it's generally good practice to just use a fireall to filter out traffic on unused ports, which in that case would include database ports.

This essentially eliminates every security problem that'd allow attacker to connect to database, leaving just attacks that utilize bugs in the application which is much harder to find than running NoSQLMap on buch of IPs

**Comment by julianlam** [comment]
Ah yes, `ufw` is so helpful and dead simple to set up. Unless you need a port open, it should stay closed.
