### ISSUE TITLE
Awaiting moderation

### ISSUE THREAD

**Issue by freestylemaster** [NodeBB/NodeBB#9164]
Perhaps it'd be nice to have an option to hide a post (similar to how spoiler works) in case it's flagged or there is certain number of flags by users  until a moderator resolves or just clears it.

**Comment by julianlam** [comment]
Hey there,

Thanks for suggesting this feature. I feel that this would be best implemented as a plugin :smile: and not in core NodeBB.

If you're interested in sponsoring this plugin, please reach out to us at sales@nodebb.org, otherwise you can suggest it in our [community forum](https://community.nodebb.org/category/18/plugin-requests), where someone might take on the project for you.

If you're interested in creating this plugin yourself, feel free to ask questions in our [plugin development category](https://community.nodebb.org/category/17/plugin-development).
