### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by RocketNinja15** [NodeBB/NodeBB#9323]
Hi!

I was just wondering if it was possible to deploy to github pages, and how I would do that

**Comment by pitaj** [comment]
It's not possible to deploy NodeBB or pretty much any forum software to Github pages.

**Comment by oplik0** [comment]
Just to add "why":
GitHub Pages is a static website hosting. This means essentially all it does is serve files with right metadata and under right routes.
You can do a lot with static websites. A browser is essentially an app platform so as long as your "app" can work purely on the client device it can be static.

But forums are a good example of applications that **do** need a server to handle a lot of things.
You need it to handle user authentication, to save posts somewhere, for notifications etc. Essentially everything that makes forums different from, say, a personal page or even a blog (as it can be reasonably handled by writing for example markdown files on GitHub and rendering them with JS). You just can't do these things without the server handling a lot of stuff - and NodeBB specifically needs a server running Node for it.
(though note that there are services that essentially will give you an API to a server that does them for you - for example Google Firebase or AWS Amplify have a lot of services that you can make your "static" website interface with. But, as I said, it's essentially someone hosting a server for you and just giving you simple interfaces to use it, and you'd need to design your software specifically to interface with them. A quick search yielded me [this](https://github.com/hoppula/refire-forum) for Firebase, though it's much more basic than something like NodeBB, Discourse or other major forum software)

If you want to host NodeBB for free there are a few services that can work with NodeBB:
- [Heroku](https://www.heroku.com/) - it's a platform as a service provider that offers hosting with Node and you can get a single "server" ("dyno") for free. There are [official installation docs for Heroku](https://docs.nodebb.org/installing/cloud/heroku/), but they're quite outdated (you'll need to follow through a few links to find instruction on using MongoDB Atlas instead of mLab)
- [GCP Free Tirer](https://cloud.google.com/free) (F1-micro Compute Engine instance) - it's essentially a free VM. You'll need to set it up according to instructions for the flavor of Linux you chose (and you'll need some domain for it, though you can get domains with some TLDs like .tk for free)
- [Oracle Cloud Free](https://www.oracle.com/cloud/free/) - it's essentially 2 free VMs. Essentially the same as GCP for this purpose.

I also had *some* success testing NodeBB on [Glitch](https://glitch.com/), but it was, well, a bit glitchy :) Maybe I didn't do something right or it works better now though.
