### ISSUE TITLE
Deleting Chat Message/Rooms through API

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9428]
I can see in the V2 documentation there is a way to send chat messages but is there a way to delete chat messages (or even rooms)? As far as I can tell currently the only way to delete them is through the Sockets implementation on the Chat page. Is this correct? Could this be added to the API in the future?

**Comment by spin0us** [comment]
Any news about implementation ?

**Comment by julianlam** [comment]
Not yet, unfortunately, but thank you for the reminder!

**Comment by julianlam** [comment]
@uplift @spin0us Half a year later, I am still wracking my brain as to _why_ the lone route wasn't migrated over.

My best guess is that it was only a single `POST` route, and I had some issues with its organization.

* It's part of the write api's `users` space, which puts chats as a subset of user/accounts, but that really isn't how it is best represented -- chats would be better served as a first-class element of the write-api.
* Perhaps the way it is routed in the write-api (`/api/v2/:uid/chats`) means that the actual` uid` is in the path as opposed to inferred from the bearer token, as most routes are handled in v3... in v2, you have ...

----

... okay, I figured it out.

The `uid` parameter in the v2 Write API messaging route refers to the **recipient**, not the **sender**, which makes no bloody sense because because you're not `POST`ing a message to _their_ chat, it's _your_ chat, and _they_ are a part of.. :shipit:

**Comment by julianlam** [comment]
* v2 write API only supports user-to-user chats, as it looks like it was created _before_ the concept of chat rooms. This also explains the weird organization.

**Comment by julianlam** [comment]
:weary: Look at the work you guys are making me do.

https://github.com/NodeBB/NodeBB/blob/1550a0a2b7b3be394761646936cc08cc89330255/src/routes/write/chats.js#L13-L26

**Comment by uplift** [comment]
@julianlam I look forward to updating all my socket calls to API routes 😄

**Comment by julianlam** [comment]
@uplift Are you explicitly needing the ability to delete a room?

**Comment by uplift** [comment]
@julianlam Its not something we require currently. The only use case I can think for its use is for clearing up data in the database for unused rooms (i.e. no users in the room) but then from an audit/moderation point of view the permissions for such an action as delete/purge rooms could mean users send a message and purge room with no log of it being sent

**Comment by spin0us** [comment]
@julianlam For my part, I have a greater need to be able to create a chat and add messages to it through the API.

**Comment by julianlam** [comment]
@spin0us That is available in the `chats-api` branch now, although no guarantees that that API won't change between now and when that branch eventually gets merged :smirk:

**Comment by spin0us** [comment]
@julianlam Any idea when it will be merged?

**Comment by julianlam** [comment]
It's still my currently active project... You can see how far along I am by going to the routes file:

https://github.com/NodeBB/NodeBB/blob/chats-api/src/routes/write/chats.js#L13-L27

It looks like I'm about halfway through right now :smile: 

For every route, I have to:

* Write the controller, or migrate it from an existing websocket method
* Deprecate the websocket method
* Abstract it into a `src/api` library if needed (since as part of the deprecation, we want both socket and api calls to call a common library method)\
* Test that the updated websocket call still works
* Migrate the client-side call to use the API route
* Update tests to test the API route instead of the websocket route

So, given that I've started 10 days ago, we're looking at mid-January, probably... assuming I won't _add_ routes to this file, which is not a guarantee, heh.

**Comment by julianlam** [comment]
That said, the `chats-api` branch is kept up-to-date with latest master, so you can switch to it if you like. I don't anticipate changing any of the routes, so they should be safe to integrate against.

... but I reserve the right to completely upend everything :imp:

**Comment by julianlam** [comment]
It has been merged :shipit:

**Comment by julianlam** [comment]
Some sample code to delete a message:

``` js
require(['api'], (api) => {
  api.delete(`/chats/${roomId}/${mid}`, {})
    .then(() => {
      // do things here.
    })
    .catch(alerts.error);
});
```
