### ISSUE TITLE
Flags - only allow global moderators/admins be able to view them.

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/NodeBB#9484]
Can you incorporate permissions to select who can see forum flags?

The scenario we have is that we give groups on our gaming server their own forum categories and give them local moderator access to purely moderate their own category, so they don't need to keep asking admins or global mods to keep doing stuff for them. However, we have noticed that they can see the flags system which also gives them access to see member information they wouldn't normally see, such as email changes etc..

Ideally, we would want the forum flag information to be only accessed by global moderators or admins.

**Comment by saesrpg** [comment]
Is this possible?

**Comment by julianlam** [comment]
Yes, I believe so, I'll have to look into this possibility when I have time.

**Comment by julianlam** [comment]
A "view flags page" privilege can be added to facilitate this.

**Comment by saesrpg** [comment]
Brilliant, would really appreciate it

**Comment by julianlam** [comment]
@saesrpg Hi again, I apologise for the delay for me to look at this (it's literally been sitting in my inbox for 8 months).

Upon reflection, I don't necessarily agree that breaking apart the "moderate" privilege into "moderate" and "manage flags" privileges makes sense. If anything, it would introduce confusion because then it is not immediately clear what "moderate" covers<sup>1</sup>.

Reading your post again, it seems the impetus of the issue was the following:

> However, we have noticed that they can see the flags system **which also gives them access to see member information they wouldn't normally see, such as email changes etc..**
>
>**Ideally, we would want the forum flag information to be only accessed by global moderators or admins.**

(emphasis mine). I'd consider that a bug, so I can hide that particular set of information from moderators.

Would that be an acceptable compromise<sup>2</sup>?

<sup>1</sup> I'll admit it doesn't do a good job of telling you what it does _right now_, but I digress...

<sup>2</sup> It doesn't matter what you say, I'm going to do this anyway, but the question is whether you _really_ need that separate privilege.

**Comment by saesrpg** [comment]
Don't really need it separating but just used it as an example due to other features being branched out into its own privileges over the past few years.

Your idea seems a sensible approach to it.

Cheers.
