### ISSUE TITLE
Google pagespeed score is getting lower and lower

### ISSUE THREAD

**Issue by charizzrd** [NodeBB/NodeBB#9515]
Version: 1.17.0 Google pagespeed score mobile: 24
Version: 1.16.0 Google pagespeed score mobile: 46

Note: tests were repeated several times and averaged.

**Comment by oplik0** [comment]
This seems like it might be a problem with your plugins/themes.

Running pagespeed insights on https://community.nodebb.org/ results in scores of around 65-78:
![image](https://user-images.githubusercontent.com/25460763/116319217-68dafa80-a7b6-11eb-83f6-e21916559628.png)

Running on my own website on 1.17.0 I got 60-72, though the performance tanked mostly due to the amount of category images visible on load.
A test site that is still running on 1.16.2 gave me scores between 65-80. Though note that there is almost nothing there outside of the default right now - so it probably had a positive effect on the score.

**Comment by charizzrd** [comment]
I did this test while there were Google Adsense ads

**Comment by julianlam** [comment]
@charizzrd Hmm... So if the pagespeed score is 60 without Adsense, and 24 with Adsense... Then it's not exactly NodeBB that is causing a reduction in score, is it? 😉 

What are the scores without Adsense, on 1.16.x and 1.17.x?

**Comment by charizzrd** [comment]
but I did 2 tests with adsense, I had a 1.17.0 drop.
