### ISSUE TITLE
Generating token requires a session

### ISSUE THREAD

**Issue by shayanYousefi** [NodeBB/NodeBB#9517]
- **NodeBB version:** 1.17.0
- **NodeBB git hash:** 32c20806bc8467953ba354042b870ed8794f8517
- **NodeJS version:** v14.15.1
- **Database type:** mongo
- **Database version:** 4.4.0

I'm trying to generate a token for a user with the route https://myforum.com/api/v3/users/{uid}/tokens by providing it with a password:
`curl -d 'password=mypass' http://myforum.com/api/v3/users/{uid}/tokens`

but nodebb requires a session to generate that:
`{
    "status": {
        "code": "not-authorised",
        "message": "A valid login session was not found. Please log in and try again."
    },
    "response": {}
}`

Is seems like a bug cause it makes the token kinda redundant. If I already have a session why would I need a token for authentication?

Furthermore, when using the  route "api/v2/users/{uid}/tokens" (with [nodebb-plugin-write-api](https://github.com/NodeBB/nodebb-plugin-write-api) installed) it generates the token fine.

**Comment by michalclarke** [comment]
Hi , I know that a lot of people are **making** websites and most of them are facing the problem of a good **webhosting** . SO, I have a solution for them because I have just###  found a website which **provides** the node [JS hosting](https://wphostinggeeks.com/hosting-for-node-js/) for your website . They **### provide** the best services and I testify to that services and I testify to that. You can recieve the services _**### [b]here[/b].**_

**Comment by julianlam** [comment]
Ah it seems `/api/v3/utilities/login` already authenticates the session.

So you can use the session generated by this route to generate your first token.
