### ISSUE TITLE
error in nodebb-plugin-node-ldap

### ISSUE THREAD

**Issue by ZibaBahari** [NodeBB/NodeBB#9566]
Hi

 [plugins/nodebb-plugin-node-ldap] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
[plugins] Unable to load library for: nodebb-plugin-node-ldap
 Error: Cannot find module './user'

- **NodeBB version:   *1.17.0* 

- **Database type:**    mongo

	1. I installed nodebb-plugin-node-ldap
	2. Then, I saw this error in log and there is not Plugins>LDAP settings

Thank you

**Comment by oplik0** [comment]
This isn't a problem with NodeBB, but with the plugin: https://github.com/ink-blot/nodebb-plugin-node-ldap/issues

But after a quick look it seems that the main reason for the error is using the old method for requiring dependencies. `module.parent.require("./<module>")` should be changed to `require.main.require("./src/<module>")`.

The plugin was not updated since 2019, though that import method was already deprecated by then (though it only showed a warning then). I doubt the author will fix it anymore, but it seems someone made a fork fixing this issue: https://github.com/csturiale/nodebb-plugin-node-ldap - so just use this instead.

**Comment by ZibaBahari** [comment]
> This isn't a problem with NodeBB, but with the plugin: https://github.com/ink-blot/nodebb-plugin-node-ldap/issues
> 
> But after a quick look it seems that the main reason for the error is using the old method for requiring dependencies. `module.parent.require("./<module>")` should be changed to `require.main.require("./src/<module>")`.
> 
> The plugin was not updated since 2019, though that import method was already deprecated by then (though it only showed a warning then). I doubt the author will fix it anymore, but it seems someone made a fork fixing this issue: https://github.com/csturiale/nodebb-plugin-node-ldap - so just use this instead.

thanks, i used this fork, but i do not have a correct example about LDAP Settings options , Someone can help?

**Comment by roger-zhao** [comment]
@psychobunny @ZibaBahari , I'm also doing with LDAP, seems that still not work for me, how about you?

**Comment by julianlam** [comment]
Please provide error messages in order for us to debug.
