### ISSUE TITLE
Allow creation of folders in the upload section of the admin panel

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/NodeBB#9638]
As per the title, would be useful to be able to create / delete / edit folders within the uploads directory via admin panel to allow users to create a useful structure of files.

**Comment by julianlam** [comment]
Hi, thanks for the suggestion!

We don't really have a lot of tooling in this part of the ACP because it's not really _meant_ to be a full fledged file editor, but I can definitely see the use case of a "New Folder"-type button here.

This is not something that regular users can adjust, just admins, that's ok?

**Comment by saesrpg** [comment]
Yep sorry, should have put it across clearer, purely for admins yes.

**Comment by gasoved** [comment]
This will be available in v1.18.1.
