### ISSUE TITLE
Flags list via API without privileges causes Server error

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9670]
Nodebb 1.17.1

When accessing /api/flags without a valid admin or mod session, it throws the below server error instead of returning a 401 or 403 response.

https://github.com/NodeBB/NodeBB/blob/6c47a060c1ba98904ec303ccfbf8eb6d88f9b539/src/controllers/mods.js#L29-L31

Same for the detail page

https://github.com/NodeBB/NodeBB/blob/6c47a060c1ba98904ec303ccfbf8eb6d88f9b539/src/controllers/mods.js#L116-L120

**Comment by julianlam** [comment]
This is a breaking change as it contains an API change.

Flag **details** route will return 404 across the board (instead of 500) for guest or unprivileged users. This is to protect against enumerating the URL to discover how many flags exist on the system.

Flag **list** route will return 403 instead of 500 if guest or unprivileged.

In the case of the flag **list** route, the API return format has changed to v3 style, with `status` and `response` properties.
