### ISSUE TITLE
Topic event deletion

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#9684]
I think topic events being optionally possible to delete by moderators could be useful for keeping topics "neat" - while some events (like deletion or locking/unlocking a topic) feel important enough to warrant being permanent,

I'd say that pins, post queue, or some events that can be added by plugins wouldn't lose much if they could be deleted by moderators.

I noticed this issue when working on a event-based dice rolling plugin - while being undeletable by normal user was one of the reasons for using topic events, the issue with potentially spamming a topic with such events seems impossible to prevent without building a deletion mechanism. 

However, currently the only way to do so in a plugin would be to directly interact with the DB, as `topics.events` doesn't export any method for modifying or deleting events (other than `purge` which deletes everything in a topic).

I think at least offering an API for deleting would be useful, but the full implementation of event deletion feels like something that could fit in the core itself (+ theme for the frontend of course)

**Comment by julianlam** [comment]
Certainly, that rationale makes sense. 

 The reason why we don't currently support a topic events deletion API is because these topic events were not exposed to the front end in any way prior 🙂 therefore there was no incentive to add in event deletion, except for perhaps keeping the database clean and tidy.

Well look into adding a topic events deletion api
