### ISSUE TITLE
last reply goes before topic event

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#9729]
When the last item in the topic is an event, making a new reply will go above it.
![image](https://user-images.githubusercontent.com/2583394/130480039-4f0db09a-b941-4708-a459-dceb09bf3cb9.png)

**Comment by julianlam** [comment]
Ideal solution here is to refactor topic events so that they are rendered server side.

He would resolve the content shifting issue, as well as this issue at the same time.

For future reference, the best way to achieve this may be through the use of a helper, instead of rendering the post block via benchpress include.
